### ISSUE TITLE
Option to auto-increment build number based on cached packages

### ISSUE THREAD

**Issue by asmeurer** [conda/conda-build#102]
_Issue by **[ijstokes](https://github.com/ijstokes)** from Saturday Apr 26, 2014 at 14:12 GMT_
_Originally opened as https://github.com/conda/conda/issues/696_

---

As a specific feature related to the more general issue brought up in #485, it would be great if the `meta.yaml` file allowed me to specify `build: auto` that would default to 0, but if an existing package in the local conda package build directory already exists with all parts of the package name identical _except_ for the build number, to auto-increment to the next build number.

**Comment by msarahan** [comment]
This is a property to be incorporated into a CI system or package hosting service.  It could be done with implementation of a new jinja2 context function to get the desired number.  I'm closing this issue, as I really don't believe it's the right way.  I think it would be better to include the git information for the source, including the number of commits since the last tag.  That number of commits should be equivalent to this functionality, and it's a lot easier to obtain/implement.

**Comment by teake** [comment]
x-ref: https://gitlab.com/gitlab-org/gitlab-ce/issues/57955
