### ISSUE TITLE
cannot build scipy using 1.21.2

### ISSUE THREAD

**Issue by ilanschnell** [conda/conda-build#1050]
Using `1.20.3-38-gc885390`, I am able to build https://github.com/ContinuumIO/anaconda-recipes/tree/master/scipy just fine.  However, using the latest release `1.21.2`, I get (on OSX):
```
+ source activate /Users/ilan/minonda/envs/_build
++ [[ -n 3.2.48(1)-release ]]
+++ basename /Users/ilan/minonda/conda-bld/work/scipy-0.17.1/conda_build.sh
++ [[ conda_build.sh == \a\c\t\i\v\a\t\e ]]
++ [[ -n 3.2.48(1)-release ]]
++ _SCRIPT_LOCATION=/Users/ilan/minonda/envs/_build/bin/activate
+++ dirname /Users/ilan/minonda/envs/_build/bin/activate
++ _THIS_DIR=/Users/ilan/minonda/envs/_build/bin
++ /Users/ilan/minonda/envs/_build/bin/conda ..checkenv /Users/ilan/minonda/envs/_build
Traceback (most recent call last):
  File "/Users/ilan/minonda/envs/_build/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/ilan/conda/conda/cli/main.py", line 48, in main
    activate.main()
  File "/Users/ilan/conda/conda/cli/activate.py", line 119, in main
    shelldict = shells[shell]
KeyError: '/Users/ilan/minonda/envs/_build'
++ return 1
```

**Comment by ilanschnell** [comment]
In my opinion, conda-build should never attempt to modify `build.sh`, and not try to call `source activate`.  If there are important environment variables which need to be set, the recipe author should set them in `build.sh` itself.

**Comment by ilanschnell** [comment]
See also https://github.com/conda/conda/issues/2866

**Comment by msarahan** [comment]
You are seeing these errors, because as you show in #2866, you have a corrupt conda installation.

I added the --no-activate option for you: https://github.com/conda/conda-build/blob/1.21.x/conda_build/main_build.py#L133-L138.  The help option is wrong there, but the functionality is right - there is a test for it.  Everyone else who has commented on this capability is excited about it.

Closing this issue - if you still have issues after sorting out your conda install, I'm happy to reopen it.
