### ISSUE TITLE
help text for --no-activate is wrong

### ISSUE THREAD

**Issue by ilanschnell** [conda/conda-build#1123]
https://github.com/conda/conda-build/blob/master/conda_build/main_build.py#L136

@msarahan I think that activate for *testing* is useful and necessary, and should always be on, just not for *building*.

**Comment by msarahan** [comment]
Fixed at https://github.com/conda/conda-build/pull/953/files#diff-c79cbf0306ce864b4ea844b108e06d4dR134

Thanks again for your opinion on this.  However, I think that problem recipes such as GDAL are much easier to deal with this way, and rather than omitting this behavior for the sake of reproducibility, we should do other things, such as https://github.com/conda/conda-build/pull/1119/commits/90db013dae41fbb9b831762dd264c4b586b93c80 to maintain reproducibility while improving ease of use and flexibility of recipes.
