### ISSUE TITLE
Import not found in v 3.21.6 during template rendering

### ISSUE THREAD

**Issue by mwcraig** [conda/conda-build#1138]
I am getting an import error during template rendering on the CI services (all platforms) I have not, unfortunately, been able to reproduce it locally.

The error can be seen at: https://travis-ci.org/astropy/conda-build-tools/jobs/146711769#L357

It goes away if I pin conda-build to 1.21.5; see https://travis-ci.org/astropy/conda-build-tools/builds/146721355

**Comment by msarahan** [comment]
This one is very tricky.  I'm pretty sure that it is because astropy-helpers needs to installed *before* the rendering phase.  We don't have a good way to express that kind of dependency right now.  The build environment has not yet been created, so this is something that the user would need to install manually before starting the build.

I think the problem has showed up in 1.21.6 because I tweaked load_setuptools, and this got exposed somehow - or an exception is raised earlier, where it slipped by before.  I'll try to make an execution path that tries rendering again *after* the build environment has been created.

**Comment by mwcraig** [comment]
I think it is fine for it to not automatically pick up the dependency from the recipe. What was surprising was that I installed astropy-helpers manually before launching the build, so it seems like load_setuptools isn't seeing the current environment, either.

**Comment by msarahan** [comment]
Fixed by #1140 - closing, but will happily reopen if the problem recurs.

**Comment by mwcraig** [comment]
Thanks!
