### ISSUE TITLE
Recipe customization / variants / better pinning

### ISSUE THREAD

**Issue by msarahan** [conda/conda-build#1142]
This issue is to track progress on an issue that has already spanned several PRs and issues.  Since this issue has already spread across several PRs, this issue is being proposed to be the central discussion point, and any discussion on PRs should strictly be review of code, more than discussion of concepts.  

The idea is that we need a better way of customizing recipes.  When the numpy x.x style of pinning was added ( #573 ), people appreciated it, but wanted to generalize it.  Jinja2 is already flexible enough, but we lack configuration schemes for reusable data, as well as some syntactic sugar to make configuration sufficiently easy.
## Design goals:
- support config files at 3 levels, with lower levels overriding the upper ones:
  - included with conda-build
  - user's install-wide
  - per-package
- Identify key confiugration types:
  - pinning versions (versions that must match between build and run)
  - variants of a particular feature (BLAS: MKL/OpenBLAS/ATLAS/etc.)
  - Specifying compiler / toolchain options
- Specify how to distinguish builds: how do different variations end up with different filenames?
  - Probably can't just have all variations contribute to build string directly.
  - Hash instead?  Installation would need to access metadata, not rely on build string

Current PR for implementation: #966 

Past issues/PRs where much discussion has occurred: 
- #911: @mwiebe suggests a batch/bash file-based approach to lining up compiler
- #908: @msarahan added conda render command, moving towards all version and recipe metadata being required to be present pre-build
- #857 @kalefranz's proposal to add a separate jinja2 syntax for each jinja pass
- #848: @ukoethe's proposal to improve pinning
- https://github.com/conda/conda/issues/1959: @ukoethe's proposal of customization of compiler, to enable non-standard Python distributions on Windows (to support C++11)
- #747 @pelson's recommendation that build dependencies be resolved before build id is computed
- #728 @johanneskoester's generalization of the x.x syntax to all packages
- #653 @mwcraig's 
- #650 @pelson's proposal that the x.x numpy pinning syntax need only be in the run requirements, allowing the build requirements to be more meaningful (such as lower/upper bounds)
- #573 @ilanschnell's original inclusion of the numpy x.x syntax

**Comment by pitrou** [comment]
Is there an explanation of what the "config file" contents would be?

**Comment by msarahan** [comment]
That's up for discussion.  My thoughts thus far have been to support sections with some meaning, such as:

```
pinned_packages:
  - hdf5
```

for things where we'd need to pin a runtime requirement to be the same as whatever was used in build.  There was also the notion of providing an "installed" dictionary that might be useful for this: https://github.com/conda/conda-build/pull/848#issuecomment-212641321

We also need to support matrices of versions, such as for numpy.  I'm not sure exactly how this should look.  Perhaps:

```
versions:
  numpy:
    - 1.10
    - 1.11
```

and then in meta.yaml:

```
requirements:
  build:
    - numpy  {{ version }}
```

with some code behind the scenes looking up the version based on the package name?

I'm hesitant to leave things as completely free-form, but I also don't see compelling reasons for overly structuring this, other than to support special functionality that requires code behind the scenes.  I think it is fine to allow arbitrary user key/value settings, so long as we standardize how they behave somehow.

**Comment by pitrou** [comment]
> We also need to support matrices of versions, such as for numpy. I'm not sure exactly how this should look.

Perhaps look what was done for anaconda-build? (binstar build)

**Comment by pitrou** [comment]
I think this is missing some use cases. We have at least two use cases which force us to have several recipes right now:
- different build sources (e.g. git clone vs. source tarball vs. local path)
- different test procedures (e.g. CPU tests vs. CUDA tests)

**Comment by jasongrout** [comment]
CC @sylvaincorlay, who has expressed interest in having a runtime dependency be pinned by what was used at buildtime.

**Comment by johanneskoester** [comment]
I post here as a followup on conda/conda#3721.
* @msarahan I agree with you that pinning versions and compiler flags should do the trick.
* I wonder if your second point at the top (variants of a particular feature) is not simply contained in pinning to compiler flags

If so, I propose the following:

## Add a build_args section to recipes:

Add a section to define build arguments to meta.yaml, e.g.
```
build_args:
  - "--with-some-ABI-changing-option"
  - "--with-some-other-option
```
When the build script is executed, these args are available as environment variables ``$BUILD_ARG0``, ``BUILD_ARG1``, `BUILD_ARG2`, ...

## Create a fingerprint of the build args

* Build args are lexicographically sorted and hashed
* the hash is available together with the version in the package metadata

## Replace the current build string

Build string is replaced with the build arg hash (see above), and a hash of the lexicographically sorted pinned dependencies of a recipe.

## Allow to pin to build args in runtime dependencies

In addition to the version, one may pin to the hash of the build args.

# No config file infrastructure for now

I think my proposal would solve the current issues with binary incompatible packages, while not introducing too many changes in conda and conda-build. I guess most projects already have their own config file/matrix build infrastructure. That can always be replaced later, but seems not to be necessary in order to solve the compatibility problem.

What do you think? Please apologize if I am missing something or just repeat what was considered already, the discussion seems to be quite scattered and I might have missed some threads.

**Comment by msarahan** [comment]
@johanneskoester this is a reasonable interim proposal, and I'm behind it.  I want to emphasize a few points:

1. Please include build-time dependencies and their versions in your hash, not just build arguments.  This is important, because versions of build-time software are often critical to the outcome.  I hesitate to specify run-time dependencies here because that would overconstrain this.  Perhaps it is adequate to include run-time dependencies, but not any exact versions - only more broad pinning.  Including these in the hash means you'll need to compute the hash probably immediately after the build environment is created, so that the exact versions of packages at build time are known.  There is a rendering path for this, but it will need enhancement.  A dry run of the environment creation is probably preferable to actually carrying it out.
2. Please make sure that jinja templates are usable for config values.  This also ties in with 1 - the hash needs to be computed after templates are evaluated.
3. A composite build argument makes more sense to me.  I also wonder about a syntax to allow targeting of particular arguments to particular programs.  Perhaps something like:

```
build_args:
    gcc:
        - some_arg
    git:
        - other_arg
```

with these being accessible like your scheme, but grouped by program: ```GCC_ARG0```, ```GIT_ARG0``` and so on.

**Comment by johanneskoester** [comment]
Ok, here is an alternative, that won't change the syntax and would work out of the box for any recipe:

* instead of the build_args stuff, automatically create a hash from the exported symbols in each .so library of a package and store it in the metadata.
* for dependencies, use the mechanism from `conda inspect linkages` to obtain the hash, for each runtime dependency that is linked against. Automatically pin to this hash.

Again, the dependency resolution only has to look up if the package provides the hash in addition to the right version.

I am not a C/C++ expert, but I would think that the symbols should suffice to catch differences between builds from different channels, as long as the channels otherwise agree to use the same or a compatible system for building (in terms of gcc and llvm usage and so on). This is the case for conda-forge, bioconda, r and anaconda, right?

I must say that I would prefer this solution. What do you think, am I missing something?

**Comment by msarahan** [comment]
I don't know enough about these things.  I tried to think up things that would break this.

- optimization flags: will symbols differ when somebody builds with -march=native vs. something more broadly compatible?
- what is the Windows story?  Maybe this is too much for you to take on, but there needs to be compatible analogs that are readily identifiable.
- using dependencies for the hash forces us to exact pinning, which greatly increases the chances of unsatisfiable dependencies.  My idea for pinning was to keep build dependencies pinned exactly, but keep as much flexibility as possible in the run dependencies.  Can the pinning expressions for runtime dependencies be hashed reliably somehow?  Some kind of standard formatting, plus some sorting rules?

I'm also still not clear how one would specify which package to install.  The hash is OK, but your proposal depends on having the final package to construct the hash.  I'm pretty sure we need to be able to compute the hash without the complete package, or use a completely different key system (probably some ugly composite key).

**Comment by johanneskoester** [comment]
### Restrictiveness
> using dependencies for the hash forces us to exact pinning, which greatly increases the chances of unsatisfiable dependencies. My idea for pinning was to keep build dependencies pinned exactly, but keep as much flexibility as possible in the run dependencies. Can the pinning expressions for runtime dependencies be hashed reliably somehow? Some kind of standard formatting, plus some sorting rules?

Indeed, such pinning would tie to exactly the same symbols. This might be too restrictive, in the sense that updated versions could only add symbols but not remove them, such that a linked package could still work with the newer version. On the other hand, it avoids cases of incompatibility where a package was built with a certain config option that is not present in the same package of another channel.

### Windows
I have to admit that I have no idea about windows. That's why I can only make proposals here, but I am (also time-wise) not the person to implement any of these.

### Optimization flags
That could be I think, at least if some code is removed or inlined. This makes me think that it might indeed be dangerous to rely on symbols...

### Conclusion
Indeed, at least from this perspective it might not be a good idea.

**Comment by johanneskoester** [comment]
## Alternative: Channel dependencies

### Observation 1: Within a channel, history tells us that package incompatibilities are not really an issue.

* The channel teams are capable of making sure everything works properly, just like teams maintaining a linux distribution.
* The current possibility to pin a package version is sufficient here, because there cannot be two copies of the same package with the same version in one channel.

### Observation 2:

Problems occur when people combine channels in a different way than what was used during builds.

### Solution

Instead of trying to extend pinning, we can allow channels to have dependencies. That would mean that conda-forge and r would define anaconda as a channel dependency, whereas bioconda would define anaconda, conda-forge and r as a dependency.

Then, the simple rule that any package can only pull its dependencies from ancestral channels  and its own should avoid all problems we currently see.

### Side benefit
It would no longer be necessary to specify all channels in a defined order when e.g. using a package from bioconda. Instead, we people could write `conda install -c bioconda bwa` again, and conda would automatically use the channels that were used during build.

**Comment by msarahan** [comment]
#1585 is merged.  Closing.
