### ISSUE TITLE
unclear documentation on how to version post-build

### ISSUE THREAD

**Issue by janssen** [conda/conda-build#1151]
I don't understand this section of the documentation:

"NOTE: Post-build versioning: In some cases, you may not know the version, build number, or build string of the package until after it is built. In this case, you can perform Templating with Jinja or utilize Git Environment Variables and Inherited Environment Variables."

I don't see how I can do any of this _after_ the build (post-build versioning, after all).  Aren't all the substitutions in the YAML done before the build?  Please include an example if I'm just not getting it.

**Comment by marscher** [comment]
These statements do not hold any more. In conda-build-2.0.1 the templates are substituted only once. Maybe it is because I used os.environ.get (in order to have a sane default value), but then this breaks the logic of post-build-versioning? Does environ provide defaults?

The problem I'm facing is that the recipe is itself git maintained, but this repo is not versioned by tags. So the first jinja substitution of GIT_DESCRIBE_TAG fails. This can only be valid, as the the source is available.

**Comment by msarahan** [comment]
Closing - templates are substituted iteratively in conda-build 3.  You may also find the load_file_regex function helpful for getting data from files that exist in the source pre-build.

https://github.com/conda/conda-build/blob/master/conda_build/jinja_context.py#L152

example:

version: {{ load_file_regex('path/to/somefile', '\d+\.\d+') }}
