### ISSUE TITLE
implement --json with conda build --output, remove stderr output

### ISSUE THREAD

**Issue by davidslac** [conda/conda-build#1178]
Per https://groups.google.com/a/continuum.io/forum/?utm_medium=email&utm_source=footer#!msg/conda/KlajMoAorZY/VqYwF4ZWAAAJ

I suggest that the command 

conda build --output xx

not print anything to stderr unless there is a warning or errror 

and that the --json flag be implemented so users don't need to parse the outtput of conda-build --output

**Comment by msarahan** [comment]
I'm not sure that ```--json``` is the answer.  ```--json``` is meant to output dictionaries as JSON, so that they're easier to import somewhere else.  I think the relevant code you're hoping for is the elevation of the logger to ERROR: 

https://github.com/conda/conda/blob/7f71024d6df9d7c2b3b184efe4f6c54e2e05c138/conda/cli/main.py#L126-L130

but to say we need --json for a string output is a little bit confusing to me.

conda-build outputs this entry to stdout, not stderr: https://github.com/conda/conda-build/blob/master/conda_build/main_build.py#L329-L331 - I think the root of this issue is that we need to know where the ouptut "subprocess exiting" is coming from.  It seems to be at https://github.com/conda/conda/blob/588eb4108c8138c55154813a1210a3355597255e/conda/exceptions.py#L90  - it is possible that the conda-build entry points could set the logger level for conda stuff to error, but that seems like improper separation of program domains.  I'm happy to put that in as a workaround, though.

There is a python API in the works at #953.  For now, you could also use conda_build.render, as is done in main_render.py: https://github.com/conda/conda-build/blob/master/conda_build/main_render.py#L124-L127 - though please replace this with the proper API when that is released.

**Comment by msarahan** [comment]
CC @kalefranz

**Comment by davidslac** [comment]
I think your right, I just wanted a programatic way to get the output 
file from conda build, maybe json is overkill - conda build --output 
just prints one line to stdout that is easy to work with, it is just 
that there is more output on stderr now.

best,

David
