### ISSUE TITLE
Released version includes commit and is dirty

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#1187]
Maybe something funky related to `versioneer` or `auxlib`. Appears the version is `1.21.11+0.g5b44ab3.dirty` when using `conda-build` version `1.21.11` from `defaults`. See this [log]( https://travis-ci.org/conda-forge/setuptools-feedstock/jobs/150508708#L345 ) for an example.

**Comment by pelson** [comment]
xref: https://github.com/conda/conda-build/issues/1188

Ping @msarahan.

**Comment by msarahan** [comment]
This is expected with the defaults builds.  As discussed in https://github.com/conda/conda/issues/3236#issuecomment-237953770, @ilanschnell needed to revert conda-build's move to setuptools entry points in order to build with his old recipe.  We need to resolve why conda-build or conda is not creating valid entry points for conda-build.  Thus far, the 2 builds we've had at conda-forge have incomplete functionality: https://github.com/conda-forge/pyferret-feedstock/pull/8#issuecomment-236740370

One other thing to keep track of is that as-is we need conda to support pip-created exe entry points for conda-build's entry points to work on Windows (because I have conda-build using pip to create its entry points, because without pip, we get entry points that use eggs and don't work).  This PR is at https://github.com/conda/conda/pull/3224

**Comment by jakirkham** [comment]
Closing as explained and intentional. Hoping this will go away in `2.0.0`. 🍀
