### ISSUE TITLE
Multiple license files

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#1247]
Is there a way to include two (or potentially more) license files within a package? Sometimes things are dual licensed or are under the LGPL. In both cases, there are two license files. How do we go about handling these cases.

cc @goanpeca

**Comment by jakirkham** [comment]
One naive solution would be to `cat` all the licenses into one big file. Note that some people already effectively do this if they have multiple licenses. Unclear on how this fits with things like the LGPL case, but figured it should be mentioned.

**Comment by jakirkham** [comment]
Any thoughts on this? It is a surprisingly common problem, but we lack any real way to address it yet.

**Comment by msarahan** [comment]
I see the usefulness of this, but I don't have time to do this myself.  This is less important to me than split packages ( #1338 ) and build customizabilty ( #1142 ).  PRs welcome.

**Comment by jakirkham** [comment]
FWIW we don't seem to be the only ones struggling with this. ( https://github.com/pypa/wheel/issues/138 )

**Comment by hmaarrfk** [comment]
What about a License folder? there might be cases where the license isn't a text file, or probably forbids modification, a License folder would overcome all these issues and we wouldn't have to worry about formatting things.

**Comment by msarahan** [comment]
A license folder seems like a reasonable solution.  Perhaps the license_file field could be adapted to support glob patterns, as several other fields are.  PRs welcome.

**Comment by hmaarrfk** [comment]
FYI, this seems to be what pypa did:
https://github.com/pypa/wheel/commit/59976ab294e1b118f42cab404d95df66ed55f7e4

**Comment by CAM-Gerlach** [comment]
Its also worth noting that some licenses explicitly require other file(s) (e.g. ``NOTICE``/``NOTICE.txt`` for Apache, or a full copy of the GPL for the LGPL) be preserved and included with any distribution, otherwise it is in breach of the license. Therefore, as it stands today, any Apache or LGPL packages built by conda that had these files originally included with them are technically illegal to distribute, including on conda-forge, with Anaconda, etc. and are thus infringement, therefore creating the theoretical potential for infringement (of course, I'm not a copyright lawyer myself and this is not formal legal advice).

Therefore, I'd think this is a pretty high-priority issue. For someone like me its doubleful I'll be able to submit a PR, since on one hand the solution would be simple enough fit within my limited bandwidth, familiarity with the project and general lack of expertise, but on the other hand would require a large amount of fixed overhead including the whole "signing away my rights" thing with the CLA, setup a proper environment to test it in (I don't see any contributing guide), find an appropriate package to test it with, figure out how everything works, etc just for a relatively small change.

If you do so, I would somewhat naively recommend doing something similar to what PyPI did, with a list of filenames (with glob support) under a e.g. ``license_files`` attribute and deprecating but retaining (for now) the old one, and to ensure legal compliance and intelligent behavior by default, including the following globs in the root directory: ``LICEN[CS]E*', 'COPYING*', 'NOTICE*', 'AUTHOR*`` (i,e. using this as the default value of ``license_files``, which of course are overriden if a non-empty list is passed to ``license_files``—but if only ``license`` is set, any files matching these globs *would* be included as well to automatically bring existing packages into compliance.

**Comment by isuruf** [comment]
@CAM-Gerlach, conda-build now adds the licenses to a folder called licenses and preserves the relative path so that `a/COPYING, b/COPYING` are copied with the path. `wheel` doesn't do that and the second file overwrites the first one.
