### ISSUE TITLE
conda-build suggest to install beta version

### ISSUE THREAD

**Issue by hainm** [conda/conda-build#1291]
Hi,

should it be always the released version?

```bash
WARNING: conda-build appears to be out of date. You have version 1.21.11 but the
latest version is 2.0.0beta4. Run
```

**Comment by msarahan** [comment]
To make this suggestion, conda-build looks at your package index.  Since 2.0.0beta4 is not in the default channels, you must have a conda-build 2.0.0beta4 package locally - one that you either built, or one you perhaps downloaded from the canary channel.

As far as always preferring released versions, that message comes from https://github.com/conda/conda-build/blob/master/conda_build/build.py#L490-L495 which looks pretty naive.  I agree with your inclination that it should prefer released versions.  It should be using whatever logic conda uses to prioritize versions.  I will add this to the milestone for the next release.
