### ISSUE TITLE
Mechanism for excluding distributions from an index

### ISSUE THREAD

**Issue by pelson** [conda/conda-build#1321]
It would be useful if it were possible to provide an "exclude list" to `conda index` so that some packages don't get indexed (for a local index, where you don't want to delete a distribution, but also don't want it to be part of the options when conda resolves). It is a trivial change to `conda index` - just wondering if Continuum already do something similar to this, and if not, whether it would be accepted in conda-build?

Note: I am explicitly not talking about Anaconda channels/indexes here - this is entirely local.

**Comment by msarahan** [comment]
I'm pretty certain that we do not do such a thing.  I'd be fine to include it here, but I'd like to understand more of a use case.  Would you exclude everything but the package you're building?  In some cases, I see that as a disadvantage, because I often need to build dependencies for a package, but don't necessarily want to upload the dependencies until I have everything working for the main package.

Also, the ```conda index``` command does not get used internally in conda-build - are you planning on changing just the outermost behavior, or implementing this in a way that would potentially affect the indexing operations that happen during builds (particularly, in create_env, and at the end of build.py:build)
