### ISSUE TITLE
Visual Studio 9 2008 Win64 builds fail on AppVeyor: `The specified configuration type is missing.  The tools for the configuration might not be installed.`

### ISSUE THREAD

**Issue by shadowwalkersb** [conda/conda-build#1327]
VC9 Win64 build fails on AppVeyor. The rest build OK.  I have it in two different projects, [here](https://ci.appveyor.com/project/GorgonCryoEM/gorgon-hello-feedstock/build/1.0.26/job/tydlxxejcxurisq2#L353) and [here](https://ci.appveyor.com/project/GorgonCryoEM/freeglut-feedstock/build/1.0.23/job/gbns8m3e2f6btt3i#L306). Is it maybe, because [setup_x64.bat](https://github.com/conda/conda-build/blob/b1a33f2e54aa6b13f28881534934bbe5e741d69c/appveyor/setup_x64.bat) is not run?

**Comment by msarahan** [comment]
Those are both CMake's fault.  There's a not-very-nice-but-workable solution, used in conda-build's appveyor configuration: https://github.com/conda/conda-build/blob/master/appveyor.yml#L72-L73

I learned about these from @patricksnape.  As far as I know, we don't presently have a better way than to include code like this in our appveyor builds.

**Comment by shadowwalkersb** [comment]
Any idea why the builds fail, then?

**Comment by msarahan** [comment]
Because CMake does not find the compiler it needs without that fix.

**Comment by shadowwalkersb** [comment]
I remember having to do the same fix for Visual Express 9. It did not show x64 configuration options before applying the fix which I found [here](https://pixinsight.com/forum/index.php?PHPSESSID=38312df5f9a216341c8fe338303ceb9e&topic=1902.msg11778#msg11778). 

Back to the problem. If the fix is run, why would the builds fail only for VC9 x64 configuration? Do I need something in my `bld.bat` or `conda-forge.yml`?

**Comment by msarahan** [comment]
No, if you have the fix (which is slightly different from the link you posted - we are copying the vcvars64.bat to a different location, in addition to the registry changes that your link shows), then this should work.  It only fails for VC9 x64 because that's the only compiler that has this issue.  It is the VC compiler for Python, *NOT* VC9 for 64-bit, but it's only a partial collection of what CMake wants to find.  So we have to help CMake find it.  Because system locations are involved, we can't really apply this fix in conda-build.  Please mimic the parts that I linked to, and let us know if that sorts things out.

One other possible workaround might be to use the NMake generator in your recipe's bld.bat, rather than the visual studio generator.  The compilers and nmake are on PATH - I'm pretty confident there, as I have specific integration tests for that, and they run on appveyor.

**Comment by shadowwalkersb** [comment]
Sorry, I thought the link you sent was from conda-build internals! It is, actually, from appveyor configuration. I'll give it a try. Sorry for the noise!

**Comment by shadowwalkersb** [comment]
Sorry, I thought the link you sent was from conda-build internals! It is, actually, from appveyor configuration. I'll give it a try. Sorry for the noise!

**Comment by patricksnape** [comment]
Yes, unfortunately there is nothing conda-build can do here as we don't want to touch the user's `Program Files` etc - so you must call the script yourself as part of your `appveyor.yml`.

**Comment by jakirkham** [comment]
Yeah take a look at this PR ( https://github.com/conda-forge/staged-recipes/pull/617 ) as well, @shadowwalkersb. This basically uses the same trick. We were trying to find the best way to package it. At this point, adding to [`conda-forge-build-setup`]( https://github.com/conda-forge/conda-forge-build-setup-feedstock ) is probably the most pragmatic way forward.

**Comment by msarahan** [comment]
Thanks for closing this.

**Comment by jcfr** [comment]
To follow-up on this, we bundled the `patch_vs2008` add-on in `scikit-ci-addons`. It is now quite easy to have Visual Studio behave as expected on Appveyor.

```
pip install scikit-ci-addons
ci_addons appveyor/patch_vs2008
``` 

See http://scikit-ci-addons.readthedocs.io/en/latest/addons.html#patch-vs2008-py
