### ISSUE TITLE
--force not respected in run_test

### ISSUE THREAD

**Issue by jgmorrison** [conda/conda-build#1433]
When using run_test to conda install a package after the build it does not respect the "-f/--force" flags. All others appear to work(-y, --no-deps, --override-channels, etc.). Being that it is just a script it is expected to use the flags given just as any standard "conda install -f <package>" would. This can be desirable for users that want to test a known to work package they built that may have a dependency conflict by forcing the installation.

This happens on Windows with run_test.bat and Linux with run_test.sh and is true for conda-build 1.21 and above.

**Comment by msarahan** [comment]
This is **really** not advisable.  This is a terrible band-aid for packages that were not pinned correctly (overly constrained) at build time.  I understand this may be a paying customer.  If so, I'll grudgingly add this feature.  Otherwise, people should be keeping with the specs established by the packages, and if they really need a hacky workaround, they can edit the metadata inside the package itself.  We call that "hotfixing."

**Comment by msarahan** [comment]
Closing this issue.  If this needs to be raised again, please reopen it or open a new issue.
