### ISSUE TITLE
Should MACOSX_DEPLOYMENT_TARGET be defined or left empty?

### ISSUE THREAD

**Issue by shadowwalkersb** [conda/conda-build#1441]
I have been getting the following error when doing local builds on Mac 10.10.

```
  CMAKE_OSX_DEPLOYMENT_TARGET is '10.7' but CMAKE_OSX_SYSROOT:

   ""

  is not set to a MacOSX SDK with a recognized version.  Either set
  CMAKE_OSX_SYSROOT to a valid SDK or set CMAKE_OSX_DEPLOYMENT_TARGET to
  empty.
```

I had to unset `MACOSX_DEPLOYMENT_TARGET` in build.sh to make it work. Wouldn't it be better if it is not defined in conda-build, but specified in meta.yaml or set in build.sh? When not defined cmake picks up the system root and it works. When defined, though, the user needs to have the specific SDK and needs to specify the path via `sysroot`.

**Comment by shadowwalkersb** [comment]
This problem may not be reproducible. However, this happened while trying to fix `undefined symbols` errors during linking a project that uses `boost.python`. That problem is more serious (I think) and I was planning to submit some results of an experimentation. Before delving into that I just wanted to check if it is something already known.

In short, depending on how deployment target is specified, cmake uses `libstdc++` or `libc++` internally to link. Cmake stores the detected results in variables like `CMAKE_CXX_IMPLICIT_LINK_LIBRARIES`, `CMAKE_CXX_IMPLICIT_LINK_DIRECTORIES` and `CMAKE_CXX_IMPLICIT_LINK_FRAMEWORK_DIRECTORIES`. Results depend on if environment variable `MACOSX_DEPLOYMENT_TARGET` is defined, if defined then if it is defined through the shell or through cmake, if it is defined through cmake then is it defined in CMakeLists.txt or via command line arguments.

**Comment by msarahan** [comment]
I really don't like the hardcoding of this variable in conda-build.  This has been raised also in #1269.  Conda-build should at a minimum step out of the way when a user sets the variable, but currently that only happens if one sets the variable in build.sh.  Unfortunately, I'm afraid that simply yanking that setting may have unforeseen negative consequences, and I'm hesitant to change it without significant tests in place to mitigate the risk.

Longer-term, I think that this problem will be solved as part of the notion of "core dependency trees," which we're proposing as descriptions of system dependencies.  These will be defined at both build time and run time, and will capture things like this variable, GCC versions, C++ ABI versions, library versions, symbol versions (for Fortran, for example, where SO version is not the whole story).  At build time, it will determine what tools are used to build with, and at run time, it will define the compatibility range of a package ecosystem.  We are hoping to flesh out this idea into a formal proposal soon.
