### ISSUE TITLE
Multiple sources

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#1466]
Would be nice if we had support for downloading multiple sources and combining them in some fashion.

**Comment by minrk** [comment]
Since my case the extra packages happened to be Python packages, I was able to do it relatively simply with a requirements.txt with hash checking in build.sh.

https://github.com/conda-forge/fenics-feedstock/pull/1/commits/556756f9a7e265afaad50536f158cff710b090e6

This should have similar caching / hash checking to the source item, so ends up only a minor degradation from having multiple sources in meta.yaml.

**Comment by mwiebe** [comment]
Some more references about this:

https://groups.google.com/a/continuum.io/forum/#!topic/conda/vxK2dnQzNz4
https://github.com/stuarteberg/conda-multisrc-example

The cases I've run into where this would be nice are LLVM + clang + friends (as in the email referenced), cases where there is a cmake build system separate from the main repo like https://github.com/python-cmake-buildsystem/python-cmake-buildsystem, and https://github.com/bkaradzic/bgfx which wants to be built together with https://github.com/bkaradzic/bx right beside it.

**Comment by jakirkham** [comment]
cc @stuarteberg

**Comment by jakirkham** [comment]
CC-ing @kain88-de @isuruf based on similar [discussion]( https://gitter.im/conda-forge/conda-forge.github.io?at=58f33e8408c00c092a862622 ) on Gitter.

**Comment by msarahan** [comment]
There is an implementation of this at #1929 - Mostly working, but I want to add one more test of what happens when two tarballs that each contain a single folder get extracted into the same place.  They should both get "hoisted" but I'm not sure that is done right in the code right now.

I don't currently have plans to backport it to 2.1.x, but if anyone else wants to, go for it.

**Comment by jakirkham** [comment]
Looks like that PR was merged. Does that mean this is solved in `conda-build` 3?

**Comment by msarahan** [comment]
I think so.  Would be nice to have more testing by other people, though.  This should be in the current rc0 release on conda-canary.

**Comment by jakirkham** [comment]
Closing as this has been solved in `conda-build` 3.
