### ISSUE TITLE
conda-build 2.0 is ignoring detect_binary_files_with_prefix

### ISSUE THREAD

**Issue by gqmelo** [conda/conda-build#1475]
After updating to conda-build 2.0 I noticed that some packages were being build with prefix detection even though they were setting ```detect_binary_files_with_prefix: false```

Checking out the code, I found that this commit removed the handling of this: https://github.com/conda/conda-build/commit/2b611bc4bb58f354abb5c5e1f52c6f75ac02380b#diff-ac55d744935b1f37a3369258b88e8f1fL278

Was this intentional? The documentation stills refers to this setting

In this package specifically (```gcc``), I don't want conda to replace prefixes in binaries because basically all gcc binaries have them. So when installing gcc in an environment conda needs to make a copy of every binary and this occupy a lot of space

**Comment by msarahan** [comment]
Sorry, that's a regression.  It should respect that setting when it is false.  I tore it out because I changed the default behavior from not detecting to yes detecting.

As a workaround, there is a new argument, ignore_prefix_files that you can use right now.  I will restore the behavior for detect_binary_files_with_prefix being set to false in the next release.

http://conda.pydata.org/docs/building/meta-yaml.html#ignore-prefix-files

**Comment by gqmelo** [comment]
> As a workaround, there is a new argument, ignore_prefix_files that you can use right now. I will restore the behavior for detect_binary_files_with_prefix being set to false in the next release.

Yeah, but I still want the other relocation stuff. Also there are too many files to ignore. I will just use ```1.21.14``` to build ```gcc``` for now as this is the only package where I need to explicitly ignore this feature.

Thanks!

**Comment by msarahan** [comment]
OK, clear.  Thanks.  I think tying the relocation stuff to ignore_prefix_files was a mistake, anyway.
