### ISSUE TITLE
"Placeholder" repeat many times when doing conda-build

### ISSUE THREAD

**Issue by brendancol** [conda/conda-build#1482]
when building a package via conda build `placeholder` was repeated many times and ended up breaking builds for an Ubuntu user.  When repeat was changed to `2` in the conda-build config.py then everything worked as expected

**Comment by msarahan** [comment]
This is intentional.  It is there to make the prefix length 255 characters.  The error happens because your user has encryption enabled on the folder where miniconda is installed.  Encryption changes (increases) the effective path after conda build creates it as 255 characters.  It is not clear to me whether there is any way to detect this setting, or whether encryption even returns a deterministic length result, so that we could shorten the prefix accordingly.  There are at least 2 workarounds:

1. install miniconda to a location that is not encrypted
2. pass the ```--croot``` argument to conda-build, with the value being some folder in a path that is not encrypted.

This is in conda-build's FAQ:

> `OSError: [Errno 36] File name too long:` - This error has been seen on Linux computers with encrypted folders. The solution is to install miniconda or anaconda to a location that is not encrypted. This error occurs because the encrypted form of the path that conda-build creates can be too long.

**Comment by dhimmel** [comment]
I've run into this error as well when trying to build a bioconda package on Linux:

```
BUILD START: wkhtmltopdf-0.12.3-0
Traceback (most recent call last):
  File "/home/dhimmel/anaconda3/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/home/dhimmel/anaconda3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 342, in main
    execute(sys.argv[1:])
  File "/home/dhimmel/anaconda3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 333, in execute
    noverify=args.no_verify)
  File "/home/dhimmel/anaconda3/lib/python3.5/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/home/dhimmel/anaconda3/lib/python3.5/site-packages/conda_build/build.py", line 1522, in build_tree
    config=config)
  File "/home/dhimmel/anaconda3/lib/python3.5/site-packages/conda_build/build.py", line 1028, in build
    create_env(config.build_prefix, specs, config=config)
  File "/home/dhimmel/anaconda3/lib/python3.5/site-packages/conda_build/build.py", line 734, in create_env
    os.makedirs(join(prefix, 'conda-meta'))
  File "/home/dhimmel/anaconda3/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/dhimmel/anaconda3/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
OSError: [Errno 36] File name too long: '/home/dhimmel/anaconda3/conda-bld/wkhtmltopdf_1500920416572/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol'
```

The suggested workaround seems like a really ugly hack:

> The solution is to install miniconda or anaconda to a location that is not encrypted

How can there not be a better solution? What is the purpose of adding the placeholder content to the filename? Why can't the placeholder add only 100 characters rather than 255?

**Comment by jjhelmus** [comment]
The choice of a 255 character prefix is to allow sufficient space inside binaries which have hard coded paths which must be adjusted when these files are installed into a conda environment.  Prior to conda-build 2 the prefix length was 80 characters but this was found to be insufficient to accommodate the directories that users were installing Anaconda and Miniconda into.

You can adjust the length of the prefix using the `--prefix-length` argument.  If you do this, please be aware of the argument documentation concerning binaries with embedded path.  The [detect binary files with prefix section](https://conda.io/docs/building/meta-yaml.html#detect-binary-files-with-prefix) and the next few sections of the conda documentation also has some information on this topic that should be reviewed when building packages with a non-standard prefix length.

**Comment by ReimarBauer** [comment]
run in that today too. A very simple fix is to just move the conda-bld dir to som not encrypted place and link it back to its origin.

Can that be done by a config var oder env var?

**Comment by oleg-alexandrov** [comment]
I understand the problem with having sufficiently long paths. But I'd think that the solution is not: 

_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho 

The worst part is that this madness gets replicated very many times in every single compiler command to the point that it becomes painful to read the compiler output. 

If I am not wrong, a single compile flag -Wl,-rpath,xxxx (where xxxx gets repeated 255 times) can be used to bake a placeholder into libraries and binaries which can be later replaced with a shorter name.

**Comment by mingwandroid** [comment]
> I understand the problem with having sufficiently long paths. But I'd think that the solution is not:
>
> _h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho

For nearly a year now (since [this commit](https://github.com/conda/conda-build/commit/7595e4fe0dd5da1c9b2e16f42111177c639f47cd)) conda-build has been post-processing the logs and replacing these values with e.g. ${PREFIX} and ${BUILD_PREFIX}. Does this not work for you?

> If I am not wrong, a single compile flag -Wl,-rpath,xxxx (where xxxx gets repeated 255 times)

Unfortunately you are. We specify this path via -I and -L to our compilers and linkers respectively. Each compilation unit needs -I passed and everything created by the linker needs -L passed.

Logs from anything sufficiently complex *should* be somewhat verbose (though I am 100% into reducing redundancy as @minrk's change does) because the point is to be as informative as possible about exactly what happened.

**Comment by oleg-alexandrov** [comment]
I understand about complex logs (and spending weeks chasing obscure system and library issues). I am a developer myself. But that string shows up as -I<ugly> -L<ugly>many times for each line because it gets concatenated from the flags of your dependencies. Conda may clean those logs but if the build succeeds. If it dies in the middle and I have to resume by hand, I am back to terribly ugly logs. 

I know about -I and -L. I don't think you need long and ugly names there, it will accept any (short) path. Please correct me if I am wrong again, but you need an ugly and long string only when you burn its path in whatever libraries or executable you create. And, if that path is not long enough, later you can't replace it, because of the peculiarities of chrpath or whatever tool you use to edit your binaries. 

Hence, your issue I think shows up not at compile time but at link time. You can pass to -I and to -L a short path always, then, if you want, you can symlink that to a long and ugly path, and pass that to the linker via -Wl,-rpath,<the ugliness goes here> only once per invocation. 

I do apologize if I confuse something. I am of course interested in improving the tools, and maybe learn something along the way.

**Comment by mingwandroid** [comment]
I explained everything carefully. I am sorry you did not understand.

Your concern / this bug *has* been fixed for a long time.

**Comment by oleg-alexandrov** [comment]
I am sorry if I appear as if I don't understand. Please bear with me. 

You explained that you fix the long path in post-processing. You did not explain why you need it. A compiler normally does not need a long path for -I and for -L. Hence, why do you have it to start with?

I have been a maintainer of an open source software for many users for 8 years, and a professor for 10 years before that. I prefer to gently explain things and teach people rather than retort to "you are just not getting it".

**Comment by mingwandroid** [comment]
I am sorry, I cannot read your mind, you need to explain carefully what you think binary prefix replacement is because I do not think we can be talking about the same thing here given your suggestion of using rpath (which is only of interest to the Linux ld.so loader while the matter of binary prefix replacement is quite different and to do with what happens *after* ld.so loads the binary).

Have you read https://docs.conda.io/projects/conda-build/en/latest/resources/make-relocatable.html ?

Is there anything in it you do not understand or needs clarification?

**Comment by mingwandroid** [comment]
BTW when I replied with https://github.com/conda/conda-build/issues/1482#issuecomment-522301524 I had failed to spot https://github.com/conda/conda-build/issues/1482#issuecomment-522284028 so I apologize for that, but your rpath suggestion still identifies a fairly fundamental disconnect here. 

.. still, I hope you appreciate that all of this takes time and it takes time away from things that are more important and it upsets me that people appear not to do basic research before taking up other peoples' time. If that's not the case here I apologise, but it feels that way.

.. and we are *only* discussing aesthetics here and frankly I would rather not devote a lot of time to that versus fixing bugs.

You seem to have kind of (maybe?) accepted that this issue is fixed, but you then raise a point about dealing with failed builds suggesting symlinks as a fix. Symlinks cannot be used because the -I and -L flags are nearly *always* sourced from 3rd party build system metadata (pkg-config .pc files, CMake module files, Autoconf generated files) which are then stored in the dependended-upon packages themselves. conda-forge have many thousands of packages, do you propose to rework the build system of each so you can use symlinks so there's less text?

You also mentioned RPATHs, RPATHs affect the RPATH entires in the .dynamic section and are only ever looked at by the Linux loader *at load time*. Binary prefix replacement is about strings in the .text (or .rodata) section, read and processed by the code itself *at run time*. These are very different things and the former cannot be used as a proxy for the latter.

> Please correct me if I am wrong again, but you need an ugly and long string only when you burn its path in whatever libraries or executable you create

Passing -I and -L do not burn anything into the executable (unless you ask the compiler to record invocation commandlines), they tell the compiler and linker where to look for files.

Maybe this example is illustrative? It bit me very recently in some Python 2 builds, and that is what I am about to get back to fixing.

ssl.c
```
#include <stdio.h>

#define TOSTR_(x...) #x
#define STRINGIFY(c) TOSTR_(c)

char const * cacerts_pem_path = STRINGIFY(CERT_LOCATION);

int main(int argc, char * argv[])
{
    printf("cacerts_pem_path: %s\n", cacerts_pem_path);
    return 0;
}
```

.. and compiled with:
```
${CC} -DCERT_LOCATION=${CONDA_PREFIX}/lib/cacerts.pem ssl.c
```

Thanks!

**Comment by oleg-alexandrov** [comment]
I so much appreciate you taking time to explain these things. I hope future users will find this helpful too.  Thank you. 

> Passing -I and -L do not burn anything into the executable

I know that. This an elementary thing. I did not say that. All I said is that to -I to -L you can path any path, it does not need to be 255 character long as you do with _placeholder_placeholder. 

>  the -I and -L flags are nearly always sourced from 3rd party build system metadata (pkg-config .pc files, CMake module files, Autoconf generated files) which are then stored in the dependended-upon packages themselves.

I know that too. That is also a simple thing. And it has nothing to do with _placeholder_placeholder as this is an install prefix, which you chose, independently of your input third-party paths. 

The document you pointed out is very helpful. In fact we are getting to the core of the problem. Thank you for your patience. The key text is what you pointed out:

> The registered files will have their build prefix replaced with the install prefix at install time. This works by padding the install prefix with null terminators, such that the length of the binary file remains the same. 

All, I wrote, and this is where you misunderstood me, is that if you want to create a placeholder long prefix of 255 characters, which you later replace it by the real one by shortening and padding it with zeros, you can do the following:

gcc -o tmp tmp.cc  -Wl,-rpath,/placeholder_placeholder_placeholder_placeholder

I will suggest you try it, followed by checking that this ugly string was burned in the binary as:

objdump -x tmp | grep RPATH     

(I tried this on Linux.) This is how in my work I create a temporary install dir which I later replace. Then, as in the document you mention, I also use install_name_tool or patchelf or chrpath to replace this burned arbitrary install directory with the final install directory. 

I am aware that likely the RPATH is not the only location in your binary files that need to be replaced. I do understand what you wrote. 

Hence, I would like to state, for the record, the only point I made in this discussion. If you do want to create placeholder text in binary files, maybe you don't need a long install directory, but rather a tool to insert that placeholder text. I mentioned how I do it with RPATH.

Can you give me the name of any other variable in your binaries where the placeholder_placeholder_placeholder_placeholder gets stored and which you later rename to something shorter? The documentation does not explain that.

**Comment by mingwandroid** [comment]
> I know that. This an elementary thing. I did not say that. All I said is that to -I to -L you can path any path, it does not need to be 255 character long as you do with _placeholder_placeholder.

Since the files the compiler and linker are looking for are in that location, it is essential to point the compiler to that location to them. I hope you would agree with that? So the -I and -L are shorter you suggested sylinks, as I said, great, but please submit 10k PRs to conda-forge first (actually not great at all, we don't want to carry and maintain 10k patches to modify build system metadata output to transform long paths to symlinks, nor do we wish to rebuild everything for purely aesthetic reasons that I would hope people can ignore).

> Hence, I would like to state, for the record, the only point I made in this discussion. If you do want to create placeholder text in binary files, maybe you don't need a long install directory, but rather a tool to insert that placeholder text. I mentioned how I do it with RPATH.

Insertion of strings into binary files is (outside of a tool that is 100% aware of the structures within and is able to relocate them pefectly - such a tool doesn't really exist in my experience) impossible without corrupting those files irreperably. Do you disagree with that statement?

> Can you give me the name of any other variable in your binaries where the placeholder_placeholder_placeholder_placeholder gets stored and which you later rename to something shorter? The documentation does not explain that.

I do not understand what you mean. The code snippet I invented is meant to be representative of code we'd find in the wild in packages we try to build. So it's not possible to change a handful of variables in one project and make this 'problem' go away.

Also,that you even asked about variable names in compiled code indicates to me that this is not really your field of expertise because variable names (and actually, variables themselves) do not exist in compiled binaries in any non-transitory way - i.e. variables do 'exist' conceptually inside the running program, but that is only conceptual). The other place where you *could* say variables exist is in debug info, but that's not relevant to runtime.

Finally, if this *isn't* your field of expertise I would appreciate you take the time to read about how C, C++, linkers and loaders work in detail before continuing to take up my time.

**Comment by mingwandroid** [comment]
Given what you re-hashed about RPATHs in your most recent comment and given the fact I already spent a large effort trying to fix that particular misconception (ELF .dynamic section vs .text/.rodata section etc) and given you still think it is appropriate, it is clear that we cannot communicate in a 
good enough way to make any progress here and for that reason too, I will do other things instead.
Please just accept that your suggestion is impossible.

**Comment by mingwandroid** [comment]
> The document you pointed out is very helpful. In fact we are getting to the core of the problem. Thank you for your patience. The key text is what you pointed out:

The point is, I expect people who want to discuss things at this very technical level to have done some Googling beforehand and read all of our documentation, or at least the bits relevant to the thing you wat to talk about. When people clearly do not do that, I have an big issue.

**Comment by oleg-alexandrov** [comment]
I am sorry if this is starting to look as a petty dispute. I have no time for that either. 

I am only asking two questions. The documentation at https://docs.conda.io/projects/conda-build/en/latest/resources/make-relocatable.html says: _Binary object files are converted to use relative paths using install_name_tool on macOS and patchelf on Linux._

Are you aware of how patchelf works? Particularly its --set-rpath option? This is where the long long placeholder string gets edited. 

Are you aware how the linker inserts that placeholder path (that later needs editing and shortening) into the binaries to start with?

**Comment by oleg-alexandrov** [comment]
(This is the second post. See my earlier above.) I do know that actual variables are not stored in binaries. Those are optimized away. Once you read the man page of patchelf and install_name_tool (which your documentation says it is being used for relocation) you will understand what I mean by changing the value of RPATH. That is an actual thing stored in the binaries, not just at conceptual level.

**Comment by mingwandroid** [comment]
RPATHs have *nothing* to do with binary prefix replacement, nor can they be engineered to be of use for this purpose. I cannot seem to instill any understanding of that fact in your mind so I really will not respond again.

**Comment by oleg-alexandrov** [comment]
Fair enough. Note that the documentation does not explain how binary prefix replacement is done, except that patchelf and install_name_tool is used. Hence you cannot claim I don't understand something that was not documented to start with. I do agree that this discussion is no longer productive. Thank you for your time.

**Comment by mingwandroid** [comment]
> Are you aware of how patchelf works? Particularly its --set-rpath option? This is where the long long placeholder string gets edited.

Yes, I am very aware of patchelf and how it's pretty buggy. Our recipes allow selection of either patchelf or LIEF to do rpath manipulation because both are buggy in their own ways.

> Are you aware how the linker inserts that placeholder path (that later needs editing and shortening) into the binaries to start with?

Yes, I am very familiar with how compilers and linkers work. I have been a C/C++ software engineer for the last 25 years. I look after compilers for Anconda, Inc. and have hacked on GCC and binutils on and off for about 15 years now, and on clang/llvm for about 5. I'm not an expert though, far from it but I have a good working knowledge and can roll my sleeves up when necessary.

One final point:

You confuse two similar but distinct concepts and that's the problem here:

1. Making software relocatable at the binary, operating system loader level where it pays attention to RPATHs. We set our RPATHs to be relative to RPATH_ORIGIN. When RPATHs have been setup correctly, you can move an entire software tree from one folder to another and it will still be loadable by the operating system.

2. conda's concept of binary prefix replacement. This is this fairly unfortunate literal string replacement stuff that changes the code of the binaries. It's unfortunate because it prevents us from using hardlinks for those files and it also changes any checksums that anyone may have recorded.

Hopefully with those concepts untangled you can make progress?

**Comment by oleg-alexandrov** [comment]
Thank you. :)

**Comment by mingwandroid** [comment]
No problem!

**Comment by mingwandroid** [comment]
If you were willing, our docs (and software) are open and we would accept PRs to clarify these details!

**Comment by oleg-alexandrov** [comment]
In the meantime I did my own googling (see, homework does happen :) and ran into this: https://github.com/conda/conda-prefix-replacement

That confirms what you explain above. I know this is all arcane stuff for developers, but if anybody cares, the page https://github.com/conda/conda-prefix-replacement/blob/master/README.md could explain the issue (packages are first built into a temporary directory, then relocated to the final destination), the approach (in text files one does a simple string replacement, in binary files one has to be careful to not modify its length and hence one must start with a reasonably long placeholder), and what happens before (how the placeholder string makes it to the binaries to start with, presumably there is a linker command for that). 

I am not knowledgeable enough to submit a pull request. This is all the feedback I can give and you folks can see for yourself and in your own time what needs to be clarified.

**Comment by mingwandroid** [comment]
> how the placeholder string makes it to the binaries to start with, presumably there is a linker command for that

Well, I showed you [exactly](https://github.com/conda/conda-build/issues/1482#issuecomment-522370554) how these strings make it into the binaries.

**Comment by oleg-alexandrov** [comment]
It was not stated back then that that particular example is how things actually happen in production. Good to know.

**Comment by mingwandroid** [comment]
To be clear, incase there's doubt, my example was intended to be representative of code we find in the packages we build, in the wild. It is not representative of any code in any conda tools.

**Comment by oleg-alexandrov** [comment]
Thank you. I appreciate your time. Here I will be trying your patience, but I would like to remark that the nice thing about passing a string to a future binary via -DMY_VAR=MY_VALUE where MY_VALUE is an ugly thing of length 255 that you will later replace anyway is that you can avoid the error "File name too long" mentioned above by using a short install directory as the ugly long thing is passed via that define directive and the two don't have to have the same value until after the install and prefix replacement happens. Am I missing anything? Again, I am trying to be of help, and I hope for a better response than just "you don'get it". :) There are probably scenarios that I am missing.

**Comment by mingwandroid** [comment]
Ok, before I respond properly can you list which build systems you are must familiar with in order of familiarity? This should help tailor my response to your knowledge a little better.

Ideally you'll respond that you are familiar with Autotools or cmake.

However I still assert that all the information you need is here already., but let's see if I've overlooked something!

**Comment by oleg-alexandrov** [comment]
Thank you for your time. I do understand all of us have jobs, etc. 

I am familiar with both cmake and autotools. I guess the answer to my question is that there are many ways in which a software developer can use the provided install path to bake a string into the produced binaries that may point to libraries, data, config files, etc. Even with your trick above, one user may use -DCERT_LOCATION, another may use -DMY_SILLY_VAR. It would be infeasible and even pointless for conda build to intercept all this, hence the only solution left is perform surgery after the fact and hope for the best. Cmake could have its own macros to enable such trickery. 

Is this anywhere close? If that is so, things are bleak. :) So one has to use such an ugly and long install dir and hope it is long enough.

**Comment by mingwandroid** [comment]
> one user may use -DCERT_LOCATION, another may use -DMY_SILLY_VAR. It would be infeasible and even pointless for conda build to intercept all this, hence the only solution left is perform surgery after the fact and hope for the best. Cmake could have its own macros to enable such trickery.

It's not up to 'users' though, these things are coded into the build system metadata of individual projects and have nothing to do with `conda-build` per-se. The crux of the problem is that a *lot* of software, particularly on Unix (both Linux and macOS) and in particular stuff that uses Autotools is frequently built in a non-relocatable fashion through the very act of running `configure --prefix=<SOME_PATH>`. Through various convoluted processes (shell script, M4, perl code in automake and libtool) the compiler ends up seeing something like `-DPREFIX=<SOME_PATH>` and it snarfs that up into the binary. If this binary were to be placed into `<SOME_PATH>/bin` (and, for example, some data file in `<SOME_PATH>/share/foo.conf` then it would work just fine, but if they were to be placed anywhere else, then this string in this binary would be incorrect and the program would fail to load.

This is clearly, what happens when a user installs to a certain location. Now, if the user had chosen to install to e.g. `/c` then, in the default case (i.e. if we were to not pass a long prefix) `conda` would, at install time, be able to replace e.g. `/opt/conda/conda-bld/foo-build-path/prefix` (made up example) with `/c` (and a bunch of zeros up to the original NULL terminator and things would be fine, but if someone else tried to into `/opt/conda/envs/my-really-really-really-really-silly-and-long-environment-name` then there is not enough room to replace the strings in the binary and nothing works.

For this reason we do our builds in really long prefixes so we have head-room for replacement of them at install time.

Cheers Oleg!

**Comment by oleg-alexandrov** [comment]
Ray, thanks a lot. Cannot get more clear than that.

**Comment by mingwandroid** [comment]
Great!

**Comment by olavurmortensen** [comment]
The `--croot` solution, as suggested by @msarahan, works perfectly for me. My problem was, as others have suggested, that I had my conda installation on an encrypted home folder. I simply created a new folder in `/home` and point `--croot` to that.

```
mkdir /home/[user]_nocrypt
sudo chown [user]: /home/[user]_nocrypt
conda build --croot /home/[user]_nocrypt .
```
