### ISSUE TITLE
Build environment path too long in Anaconda 4.2.0

### ISSUE THREAD

**Issue by jehturner** [conda/conda-build#1559]
Could the "_placehold_placehold..." padding to build env paths in Anaconda 4.2.0 somehow be made optional in meta.yaml, please (hope I'm not overlooking some existing option)?

We have been re-basing our distribution of astronomy software on Anaconda, a major part of which is repackaging the old "legacy" system (IRAF) on which our community is still heavily dependent. This has taken quite a lot of work, given factors such as the limitations of conda's post-install scheme (which I should put in another issue for), but I finally had it working rather well ... until Anaconda 4.2.0, which breaks our package builds because IRAF simply can't cope with the long path under which build dependencies get installed.

This is arguably IRAF's fault, since it seems to have problems even with path lengths significantly shorter than 255 characters, but it probably isn't the only such case in the wild and may be difficult for us to fix in a very complex, decades-old code base that the original authors are no longer really supporting and we're trying to move away from.

In the meantime, I have been able to restore build functionality by changing the DEFAULT_PREFIX_LENGTH from 255 to 67 in conda_build/config.py (thanks for making that straightforward). It would obviously be better, however, if 1) we don't have to maintain our own modified version of Anaconda and 2) we don't have to shorten the build path for other packages that don't need it (or which might have the opposite problem).

Thanks a lot!

James.

**Comment by jehturner** [comment]
cc: @jhunkeler (a collaborator)

**Comment by msarahan** [comment]
This has quite a lot of history.  Most of the problems have been with encrypted folders on Linux: https://github.com/conda/conda-build/issues/1331 I'm not opposed to adding a command line argument for this parameter.  A PR would be most welcome, and should be easy.  Otherwise, I'll get to it for the next bugfix release in a couple of weeks.

However, I think if you can rebuild IRAF, it might well do OK with the long prefix.  The trouble is that these paths get embedded at build time, and are then limited to however long the path was at build time.  As long as your whole system is built with a long prefix, things might work.

**Comment by jhunkeler** [comment]
@msarahan Given the (extremely) nested design of IRAF I think @jehturner may be correct here.  As conda-build begins traversing IRAF's symlink-hell it likely hits >10 links along the way, eventually reaching its destination, or exploding... Sadly these links tend to span MANY levels down, even if the library we are attempting to discover is literally one level up from where the executable resides.

@jehturner correct me if I'm wrong

It might look something like:

```
/1/2/3/4/bin/exec.e
/1/2/3/lib/libstuff.so
```

However, you might see bizarre symlinks in IRAF such as...

```
/1/lib -> /1/2/lib -> /1/2/3/4/5/6/7/8/9/lib -> [a lot more of this] -> /1/2/3/lib
```

And depending on the path conda-build takes to get back to `/1/2/3/lib`, you could end up with something horrifying:

```
#exaggeration
exec.e:
    $ORIGIN/../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../lib/libstuff.so
```

Even though it could have been simply (by no real fault of conda-build, I suppose):

```
exec.e:
    $ORIGIN/../lib/libstuff.so
```

**Comment by msarahan** [comment]
@jhunkeler that's very different from the prefix length, AFAIK.  That's the RPATH relocatability.  You can disable that using the ```build/binary_relocation``` key in meta.yaml.  As of conda-build 2.0.11, you can provide lists of files or glob patterns, rather than just a boolean value.  This way, you might be able to fix your symlinked mess, while still keeping relocatability for other things.

The other question that this raises is whether something like normpath could fix this issue.

Ultimately, though, I'd like to better understand if the prefix length is the issue, or if deeply nested symlinks are messing up the RPATH stuff.  They're two very different parts of conda-build.

CC @mingwandroid

**Comment by jhunkeler** [comment]
@msarahan I didn't realize you could pass values to `build/binary_relocation` these days, thanks for the tip! I'll have to try that out.

Sorry for derailing things. I didn't realize there was a difference.

I was under the impression the `_placehold` padding complimented RPATH as a means to ensure the length was initially 255 bytes at compile-time, leaving plenty of room to modify it. I also believed `_placehold` was a workaround used to avoid `-headerpad_max_install_names | -headerpad` directly, because the path limits might be slightly different per OS.

🎱 

@jehturner At what point does the build process actually fail? During compilation or conda-build's post-processing? I mean, if `spp` is conking out on long paths, perhaps we could increase the buffer length(s) to compensate for them.

**Comment by jehturner** [comment]
Sorry, I'm not sure why I didn't find issue #1331 in a quick search.

I don't think this is an RPATH issue but some problem with IRAF's "virtual filename" layer underallocating string buffers (or similar). Sorry for the confusion. We are already rebuilding IRAF and it actually does build on Anaconda 4.2.0 (in work/) -- it just won't run subsequently (under _b_env_placehold_placehold...) when building its add-on packages. Anyway, I believe there is only one IRAF binary (of about 80) for which RPATH is actually needed (it's a very self-contained system) and I can compare that executable's behaviour with another version that doesn't have the relevant dynamic link.

I can certainly try to come up with a PR for this, though it would probably take longer than a couple of weeks to get to (we're trying to get this releasable ASAP and I also have a short night shift coming up). I was thinking a meta.yaml option would allow shortening the path length only for packages that need it, though I suppose it's determined by the dependencies to some extent. Anyway, a command-line argument (do you mean for the value of DEFAULT_PREFIX_LENGTH?) would be better than a hack :-).

Good news regarding glob patterns for binary_relocation; I have seen patchelf break binaries in the past (we also used it for our old distro that came out around the same time as Anaconda).

@jhunkeler: both mkpkg (when trying to compile external packages) and cl (at run time) are failing under the long paths. The cl failure is just the same as you document under "compatibility issues" on the front Ureka page, so this may explain some of the failures you've seen. Anyway, I did make a first attempt at patching IRAF (spp.h), unsuccessfully. There are also a couple of values in fio.h that might be relevant, or the problem could be more widespread. Of course it's often the case that fixing one thing in the IRAF code breaks something else...

**Comment by msarahan** [comment]
Closing, but I'd be happy to reopen if you're still having issues.
