### ISSUE TITLE
Explicit multi-user conda install support

### ISSUE THREAD

**Issue by msarahan** [conda/conda-build#1601]
A reasonably common use case is installation of conda in some system location, which is then not writable by users.  Conda-build does not explicitly test this condition, and it is broken in at least one known instance: https://github.com/conda/conda-build/pull/1540#issuecomment-268876670

This issue is for creating explicit test situations for this functionality, and fixing any further issues that are discovered.

CC @frol

**Comment by groutr** [comment]
another potential issue (similar to https://github.com/conda/conda-build/pull/1540#issuecomment-268876670) might be the `conda-bld` directory that conda-build uses by default in the root environment.  Fortunately this can be solved by setting a path relative to the users home directory for the root-dir in .condarc (since the ~ will expand to the current user).  Conda-build should understand that if it can't write to the $CONDA_ROOT/conda-bld, it should fall back to `~/.conda/conda-bld` if root-dir isn't set in a visible .condarc.

**Comment by cpcloud** [comment]
@groutr Unfortunately, lock files are written in the root environment, which makes setting CONDA_BLD_PATH or passing --croot a moot point.

**Comment by msarahan** [comment]
There's a fallback directory in the home folder now (as of 2.1.5).  If anyone needs anything more complicated, please comment here and I'll reopen this issue.
