### ISSUE TITLE
Document missing support for binary prefix on Windows

### ISSUE THREAD

**Issue by dolfim** [conda/conda-build#1629]
I think the documentation should state more clearly that binary prefix replacement is not fully supported on Windows.

The only comment about it that I could find is in the conda sources:
```
# on Windows for binary files, we currently only replace a pyzzer-type entry point
#   we skip all other prefix replacement
```

https://github.com/conda/conda/blob/master/conda/core/portability.py#L87

**Comment by msarahan** [comment]
I'm not clear on why this needs to be documented.  Binary prefixes only affect Linux and Mac as far as we've been able to see.  They actually break lots of stuff on Windows because of Windows' 260 character path limit (which has been very recently removed, but still needs to be respected for quite a while.)

**Comment by dolfim** [comment]
My point is that the docs does not state clearly that prefix replacement in binary is supported only on Mac and Linux. It explains how this is done on those systems, but after reading a few times I was still sure that some other black magic was implemented for Windows.

**Comment by msarahan** [comment]
OK, fair enough.  I'll move this issue to the docs repo and try to fix it soon.

**Comment by msarahan** [comment]
Issue moved to [conda/conda-docs #395](https://github.com/conda/conda-docs/issues/395) via [**ZenHub**](https://www.zenhub.com/)
