### ISSUE TITLE
load_setup_py_data is executed with conda-build's env, not the package's env

### ISSUE THREAD

**Issue by msarahan** [conda/conda-build#1662]
From @bryevdv via flowdock

When load_setup_py_data is executed to gather information for jinja2 templating, the python interpreter that is used to load setup.py is the interpreter in the root environment, not the environment being created for the package.  This can lead to incorrect logic, for example, contingent on python version.

This will probably require a separate rendering pass - once with conda-build's environment to establish the initial set of packages, and then a second pass after the initial environment has been created.  The second pass would need to modify the initial environment.

**Comment by jakirkham** [comment]
A second pass could be really handy for other reasons here too. For example, suppose I was to use `load_setup_py_data` with source that has not yet been acquired (e.g. a tarball on PyPI or elsewhere). Having a second pass would make it really easy to maintain Python recipes as one could gather most if not all of the metadata from `setup.py`. Thus this would solve issues ( https://github.com/conda/conda-build/issues/794 ) and ( https://github.com/conda/conda-build/issues/884 ). It may also supplant or significantly simplify `bdist_conda`. Not to mention many issues at conda-forge occur because people miss changes in dependencies when packaging a new version. With a reasonable jinja template using this second pass, those issues basically go away as well.

**Comment by msarahan** [comment]
fixed in #2071 - will be part of 2.1.16 and 3.0.0 final.
