### ISSUE TITLE
conda-skeleton fails conda-forge-linting service 

### ISSUE THREAD

**Issue by rainwoodman** [conda/conda-build#1703]
e.g.
```
For recipes/pmesh:

    The home item is expected in the about section.
    The recipe could do with some maintainers listed in the extra/recipe-maintainers section.
    The recipe must have a build/number section.
```

Some of these are package related -- but conda-skeleton shall probably ask for user input for these missing information.

The idea is then given at pypi package running conda-skeleton will give a recipe that can be used on conda-forge. (But I think it may be a very silly idea.)

**Comment by msarahan** [comment]
This is a good idea.  Since conda-forge's linter is not a de-facto standard for all recipes, I don't think we should use it directly.  Instead, my hope was that the conda-verify project could help unify Continuum's linter and conda-forge's linter, and people could pick and choose from a subset of linting options.

That project is at https://github.com/conda/conda-verify - it was forked off of anaconda-verify this summer, and modified to be more modular.

Unfortunately, the way it has played out is that although conda-build has official support for conda-verify, and is using it by default, conda-forge has not adopted it (probably because I didn't advertise conda-verify enough), and the maintainer of anaconda-verify, @ilanschnell, has chosen to keep developing anaconda-verify with focus on linting that applies his feelings for standards for packages.

If you'd like to add this linting support, I recommend adding it to conda-verify.  We can add a conda-verify flag that selects conda-forge's linting criteria.  I'd also be in favor of a configuration option that could be set to always use a particular set of linting rules.  I still have hope for conda-verify, but it needs support from everyone as a unifying tool if it is going to succeed.
