### ISSUE TITLE
feature request: set environment variables from meta.yaml

### ISSUE THREAD

**Issue by croth1** [conda/conda-build#1755]
It would be nice to have a way to declare environment variables for the test environment directly in meta.yaml.

like 
```
   env:
       - KERAS_BACKEND=theano
```

xref: https://github.com/conda-forge/keras-feedstock/pull/6

migrated from https://github.com/conda/conda/issues/4686, thanks @patricksnape

**Comment by msarahan** [comment]
Can you use the existing activate.d script mechanism?  It seems like this is something that you need to be setting for users at runtime anyway - not just at test time.

Docs at https://conda.io/docs/using/envs.html#saved-environment-variables - note that you can call your script filenames anything you want - just pick a unique name so that other projects won't clobber it.

**Comment by croth1** [comment]
@msarahan, thanks that's a good idea!

**Comment by msarahan** [comment]
Closing as resolved by above.
