### ISSUE TITLE
2.1.6 breaks the test step?

### ISSUE THREAD

**Issue by tonigi** [conda/conda-build#1816]
In 2.1.5 a test worked correctly

```
+ source /home/toni/Apps/anaconda3/bin/activate /home/toni/Apps/anaconda3/conda-bld/htmd-pdb2pqr_1489075109977/_t_env
+ /bin/bash -x -e /home/toni/Apps/anaconda3/conda-bld/htmd-pdb2pqr_1489075109977/test_tmp/run_test.sh
+ pdb2pqr_cli --verbose --ff parse --with-ph=7.0 --ff=parse --ph-calc-method=propka31 3PTB.pdb 3PTB.pqr
```

after updating to 2.1.6 i get

```
+ source /home/toni/Apps/anaconda3/bin/activate /home/toni/Apps/anaconda3/conda-bld/htmd-pdb2pqr_1489075203612/_t_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
+ /bin/bash -x -e /home/toni/Apps/anaconda3/conda-bld/htmd-pdb2pqr_1489075203612/test_tmp/run_test.sh
+ pdb2pqr_cli --verbose --ff parse --with-ph=7.0 --ff=parse --ph-calc-method=propka31 3PTB.pdb 3PTB.pqr
/home/toni/Apps/anaconda3/conda-bld/htmd-pdb2pqr_1489075203612/test_tmp/run_test.sh: /home/toni/Apps/anaconda3/conda-bld/htmd-pdb2pqr_1489075203612/_t_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/pdb2pqr_cli: /home/toni/Apps/anaconda3/conda-bld/htmd-pdb2pqr_1489075203612/_t_env_placeho: bad interpreter: No such file or directory

```

conda-build is running in an env.

**Comment by msarahan** [comment]
this looks like there's a short prefix issue.  Do you see warnings during build about a fallback to a shorter prefix?

If so, the solution is to rebuild your packages from the bottom of your stack up so that all of your packages have the full 255 character prefix.  This is especially critical for programs that embed the prefix internally.

It appears that 2.1.6 broke this for you, because between 2.1.5 and 2.1.6, we started using a long prefix for the test environment as well as the build environment.  There does seem to be a bug in prefix length detection - you should see an error when the test environment is created, rather than dying down the line as you see.

**Comment by tonigi** [comment]
The full log is [here](https://travis-ci.org/Acellera/conda-pdb2pqr). I don't see prefix warnings...

**Comment by tonigi** [comment]
The long prefix seems to hit the 80 chars limit in Linux shebang paths. 
http://stackoverflow.com/questions/10813538/shebang-line-limit-in-bash-and-linux-kernel

Not sure in which conditions it occurs; in my case it was an entry point script.

**Comment by msarahan** [comment]
I see.  This might have something to do with https://github.com/conda/conda/pull/4828.

I'm going to make the long test prefix optional.  I think it's still a good thing, to catch things like that conda bug.  There are certainly cases where it just won't work, though - and until that conda PR makes it into a release, maybe we should just disable it by default.

**Comment by msarahan** [comment]
fixed (by disabling long test prefix, and by submitting patch to conda on entry points) - closing.
