### ISSUE TITLE
Using '-t' flag in combination with source_files fails

### ISSUE THREAD

**Issue by jolos** [conda/conda-build#1942]
When only running the tests using the '-t' flag, and specifying the source_files in the meta.yml file I
get the following error message:

> ('Did not find any source_files for test with pattern %s', u'tests')

**Comment by jolos** [comment]
I should specify that just building `conda build recipe` works fine

**Comment by msarahan** [comment]
What is your full command line?  IMHO, it only makes sense to test packages, not recipes (these can be validated, but that's not the same thing as testing).  With the recipe, conda-build basically renders your recipe, then tries to go find the package to download.  It's very circuitous and not entirely sane.

Try providing the path to your built package, rather than the path to your recipe, if you are currently providing the latter.

Not saying that there isn't a bug here, just hopefully providing a workaround.

**Comment by jolos** [comment]
I split the building and testing in 2 separate steps ( for integration with a CI-system):
``
conda build -b --no-include-recipe recipe
conda build -t recipe
``

I like your suggestion, didn't know this was possible!
Though this only works if I omit the --no-include-recipe

**Comment by msarahan** [comment]
I see.  The docs need clarification.  The test/source_files key does not support your use case.  Like I said, conda-build only uses the recipe to go find your package.  The way that the test/source_files key works is that it uses the source if it is already there, or it uses the data in the embedded recipe to go get it.  If you don't include the recipe, it will fail.

I think you might need to add a step to your CI to strip out the info/recipe folder from your output tarballs after your test step.
