### ISSUE TITLE
entry_point script file has a wrong python prefix 

### ISSUE THREAD

**Issue by wsfax** [conda/conda-build#2004]
this is exactly the same as #1786 but it happens also with the latest version of conda-build (2.1.9) and the latest conda (4.3.17) on windows python 2.7.

in fact the python prefix is always pointing to the _b_env folder no matter where you install your package.

To summarize the issue:
if you have a noarch recipe like this:
```
build:
  noarch_python: True
```
and this recipe has entry points defined in `setup.py` under `entry_points['console_scripts']`, then if you install the conda package your entry_point scripts will have a wrong python prefix in the first line. 

This prefix seems to be hardcoded to the _b_env dir created by conda-build while building the package. for example:
`#!C:\Anaconda27\conda-bld\mypkg_1494248431459\_b_env\python.exe`
instead of
`#!C:\Anaconda27\\python.exe`

Under windows this makes running the executable entry point to return:
`failed to create process.`

**Comment by msarahan** [comment]
Sorry, but it looks like you have something out of date - something crufty.  Entry points created in the way that you describe are captured in our test suite at https://github.com/conda/conda-build/blob/master/tests/test-recipes/metadata/_legacy_noarch_python/meta.yaml

Running our tests on Windows should catch your error, but those tests pass.

I have also manually tested by building this noarch package on Mac, then installing it on Windows (no shebang recorded in script at all), and by building this noarch package on Windows, and installing it on Windows (again, no shebang recorded at all).

Have you ever installed conda-build with pip?  You probably need to do some cleanup in your site-packages folder, or maybe start a clean miniconda installation if you're really stuck.

**Comment by msarahan** [comment]
sorry, I think I spoke too soon.  You are talking about whole scripts, not the entry point mechanism for pointing at particular functions.  I'll try to see if there's a test for this, and if not, add one and fix as necessary.

**Comment by msarahan** [comment]
And I take back my take-back.  the entries in 'console_scripts' are the ones I was testing before.  http://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point They are the ones that point to functions, rather than to whole scripts.  At this point, I'll wait for more info from you, or close this issue after a few days of inactivity.

**Comment by wsfax** [comment]
thanks for your reply. I had a look at your legacy test and the only difference between my project and the test is that I am using `bld.bat` & `bld.sh` and you are using the `script` field in the `build` section in the `meta.yaml` file.

In my case `bld.bat` is simply calling `setup.py install` so I could remove it and replace it with the `script` field in the `build` section and this makes my problem solved.
Now my `commands` tests are passing.

**Comment by msarahan** [comment]
Thanks for the hint.  That seems like a bug.  I'll look into it.

**Comment by msarahan** [comment]
nope, seems to work for me either way.  Are you sure that you had the right setuptools arguments?  In particular, if your setup.py imports the setup function from setuptools (as opposed to distutils.core), then you need to tell it not to create an egg:

```
python setup.py install --single-version-externally-managed --record=record.txt
```

as opposed to:

```
python setup.py install
```

Eggs rely on editing .pth files for entry points, and those get horribly broken by the conda model, which is that the same file in different packages clobbers the installed location, rather than any kind of merging (which is a terribly hard problem).

**Comment by wsfax** [comment]
Indeed I was using `python setup.py install` without telling it not to create an egg. I guess this must be the problem then. 
Thanks for the hint.
