### ISSUE TITLE
Conda build succeeds but package contains nothing but an info directory.

### ISSUE THREAD

**Issue by kurtwheeler** [conda/conda-build#2057]
I have been working on creating a conda recipe for [bioconductor-scan.upc](https://bioconductor.org/packages/3.5/bioc/html/SCAN.UPC.html). I have a PR open in [bioconda-recipes](https://github.com/bioconda/bioconda-recipes/pull/4676) for it, and the tests for that repo are passing. I am able to run 
```
conda build --override-channels --channel bioconda --channel r --channel defaults --channel conda-forge recipes/bioconductor-scan.upc
```
successfully and upload the built package to anaconda.org. I can even install it into a conda environment with no errors. However whenever I try to actually use it by calling `library("SCAN.UPC")` in R (running within a conda environment I've installed the package into of course), I get an error:
```
> library("SCAN.UPC")
Error in library("SCAN.UPC") : there is no package called ‘SCAN.UPC’
```
This seems like a bug to me because I'm not sure what I'm doing wrong to cause this behavior. You'll notice that my recipe has a test which is doing the same exact thing:
```
test:
  commands:
    - '$R -e "library(''SCAN.UPC'')"'
```
but the test passes when I build the package.

How can I build this package in a way the source in included?

**Comment by msarahan** [comment]
Sorry, I'm not very familiar with R at all.  Nothing looks obviously wrong to me.  This generally happens when your recipe is installing things somewhere other than $PREFIX.  It's perhaps possible that $R is resolving to your system installation of R, rather than the R in conda-build's build environment.  If so, that's a bug, but I need you to help figure out if that is happening.

Perhaps some of the bioconda folks could take a look?  @johanneskoester ?  @mingwandroid ?

**Comment by johanneskoester** [comment]
Maybe you have your R search path set to a different folder locally? What is the output of `echo $R_LIBS`?

**Comment by kurtwheeler** [comment]
> It's perhaps possible that $R is resolving to your system installation of R, rather than the R in conda-build's build environment. If so, that's a bug, but I need you to help figure out if that is happening.

How could I tell if that is happening? `which R` outputs a path to an R which is within my conda installation, but I'm not sure how to tell if that is what `$R` is resolving to during `conda build`. I'm also unfamiliar with `$PREFIX`, however it doesn't appear to be set to anything.

`echo $R_LIBS` doesn't output anything, I guess because it's not set. $R, $R_LIBS, and $PREFIX are all unset as far as I can tell, I don't know how to tell what they get set to during the build command though.

**Comment by kurtwheeler** [comment]
It appears to be an issue with my conda installation. I'm now building my recipes within a Docker container to ensure a pristine conda environment and the built packages include source code.

**Comment by msarahan** [comment]
Yes, that fix suggests that it was using your system R.  That's a conda-build bug, because conda-build should be defining the R environment variable.  This bug may crop up if the R environment variable is already set.

One other somewhat strange fix here is to use R, rather than $R or %R% - the correct binary will be on PATH, and you should not need the full path (which is what the env var contains)
