### ISSUE TITLE
Improve building and testing of "conda" recipe

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#2095]
Its tricky to build and test `conda` correctly with `conda-build` currently. In particular, the `conda` package has its own copies of `activate`, `deactivate`, and `conda`. However these are replaced by copies or symlinks to the ones in the `root` environment during testing. Doing this confounds are ability to test the `conda` we built as it is mixed with the one from `root`. It would be great to have some way to disable installing of these symlinks or copies from the `conda` in `root` and possibly disable activation altogether.

**Comment by msarahan** [comment]
Are you aware of the ``--no-activate`` CLI flag?

**Comment by jakirkham** [comment]
I did see that in the `conda-build` 3 changelog, but it sounds like it has a different purpose. Namely it skips running the scripts in `activate.d`. Am I understanding that correctly? If so, I am unclear on how this solves the problem laid out above. Isn't it still installing the scripts from the `root` copy of `conda` in the environment?

Also if it is not installing the scripts from the `root` copy of `conda` (which would be a good start), how can I specify this in the recipe's `test` section itself? I wouldn't want to accidentally corrupt a users Miniconda install as they would want to build the latest `conda` and miss adding this flag.

**Comment by jakirkham** [comment]
Also, for reference, I'm trying to improve testing the `conda` feedstock so that bad packages are less likely to leak out. The linked PR demonstrates what I'm trying to go for and, to some extent, its shortfallings.

xref: https://github.com/conda-forge/conda-feedstock/pull/26

**Comment by jakirkham** [comment]
Also cc-ing @kalefranz as this discussion is likely to have some crossover with `conda` as well.

**Comment by msarahan** [comment]
The ``--no-activate`` flag has existed for a much longer time.  It does not run activation with conda.  Part of that is not doing the activate.d scripts.  The conda scripts that you're mentioning are created as part of the activation process - it's a conda thing, not a conda-build thing.  If you use ``--no-activate``, things should work pretty well.

**Comment by jakirkham** [comment]
Yeah, I think I confused it with a [`.condarc` setting]( https://conda.io/docs/config.html?highlight=activate#disable-activation-of-environments-during-build-test-conda-build-3-0 ) that was new. In any event, I did give it a try and was still seeing symlinks on my Linux build using `conda-build` 2.1.15. Not sure if this qualifies as a bug or not.

**Comment by kalefranz** [comment]
Conda < 4.4 creates writes those symlinks (1) when you activate an environment and (2) when a new environment is created.  So unfortunately using `--no-activate` will still have this problem.

My suggestion is to hold on this issue until conda 4.4.  Conda 4.4 switches to using PATH resolution as it was designed.  All of the "symlink conda into non-root environments" behavior has been dropped.

The foundation of this work is https://github.com/conda/conda/pull/5044, with about a half dozen follow-on PRs.  From a user perspective when working in a shell, the conda "command" is lifted one level above the conda executable, to the level of a function in each shell.  When interacting with a shell, it's actually possible to use conda and for conda to be fully functional, even if the conda executable isn't even on PATH! (In bash, the way to install conda now is `source etc/profile.d/conda.sh` rather than `export PATH="bin/conda:$PATH"`.)

Hopefully I didn't create confusion or FUD with that little explanation.  It's not a full explanation, so I'm guess it leaves several "but, what if ?" questions.  I have high confidence that the whole conda/conda#5044 switch is well thought out and reviewed.  @mingwandroid has been involved in the higher-level design, and @mbargull has pretty thoroughly reviewed all of the related code changes.

**Comment by msarahan** [comment]
Thanks for clarifying that @kalefranz - I think the best option for now @jakirkham is judicious use of ``always_include_files`` until conda 4.4 becomes de-facto standard.

**Comment by jakirkham** [comment]
So IIUC basically this won't be a problem once `conda` 4.4 is a thing, correct? If so, that seems reasonable. Should we then move this issue over to the `conda` tracker and close it out once the fix lands in `conda`? If so, I'm more than happy to do this.

> I think the best option for now @jakirkham is judicious use of always_include_files until conda 4.4 becomes de-facto standard.

Might we still need this if `etc/profile.d/conda.sh` shows up per environment? I don't really know the structure `conda` is going for. So I might be missing something.

> (In bash, the way to install conda now is `source etc/profile.d/conda.sh` rather than export `PATH="bin/conda:$PATH"`.)

Brief digression, is there an equivalently simple way to add `conda` to the path? Part of the reason I ask is some internal use cases at my work can't run the full activation script from `conda`. Haven't entirely figured out why, but it would be nice if we have some way to keep them happy.

**Comment by msarahan** [comment]
I think this is fixed by #2359 - closing.
