### ISSUE TITLE
Standalone tool to do binary prefix replacement

### ISSUE THREAD

**Issue by asmeurer** [conda/conda-build#2207]
For the emacs conda forge recipe, I need to do a binary prefix replacement to pull out a hard-coded work directory path https://github.com/conda-forge/emacs-feedstock/issues/2. 

It would be very helpful if there were a standalone command line tool to do binary prefix replacement, so that I don't have to extract that code myself.

**Comment by pelson** [comment]
I'd love to see similar functionality. In my case, for a Windows build that bakes in a resource path into the dll. https://github.com/conda-forge/udunits2-feedstock/issues/18

@msarahan - is there anything in conda or conda-build that can already be used? If not, is there a standard tool that we can make use of for this? The ``binary_replace.py`` found in places like https://github.com/conda-forge/emacs-feedstock/blob/bda318f7ee6910d1b3cc92d235f3535d6a0a4867/recipe/binary_replace.py are a good start, but are missing things like null character padding. conda/conda has some functionality in https://github.com/conda/conda/blob/069da86f657a673b8dd60168c2905a2e0ccce58f/conda/core/portability.py#L70-L96, but this it entirely dodges Windows. It isn't clear to me why though, the same technique used for Linux & OSX binaries appears to be reasonable for dlls (I don't know from experience though, [StackOverflow says so...](https://stackoverflow.com/a/15076555/741316))

**Comment by mingwandroid** [comment]
Hi @pelson, you may want to use https://github.com/AnacondaRecipes/udunits2-feedstock/blob/master/recipe/0002-Use-the-shared-library-to-locate-the-default-xml.patch instead.

I'll make a PR if you wish?

**Comment by pelson** [comment]
Thanks @mingwandroid!

Personally, I'm strongly against patching software in conda-forge in this way, and actually consider binary modification superior. Essentially, the patch you've got there is a fork of udunits2 that potentially needs to be updated for each release of udunits2. I've expressed [similar opinions](https://github.com/conda-forge/python-eccodes-feedstock/pull/1#issuecomment-227675563) about patching software so that it "works" on python 3, even though the package itself doesn't.
(I appreciate these statements are a little strong, and I also appreciate that we're working to different objectives, so please don't take this as an attack on your approach for anaconda).

Other than the modifying binaries vs patching source opinions, is there a reason you're aware of that prohibits us doing pretty basic binary patching of these paths in dlls?

**Comment by mingwandroid** [comment]
Sure it needs to be maintained but it's very simple to do that. Obviously the best approach is to submit it upstream for review. We patch lots of things (clearly we'd rather not, that goes without saying though), I think this is exactly the sort of patch that should be ok since it addresses specific issues in the difference between our ecosystem and upstream (namely relocatability).

But IMHO binary prefix modification should be ejected from the ecosystem as a security and stability nightmare. Plainly, it does not work (see more of the reasoning at https://github.com/conda-forge/udunits2-feedstock/issues/18#issuecomment-390936315)

**Comment by asmeurer** [comment]
@pelson for the emacs feedstock, I realized that NULL padding was unnecessary because I need to build against the longest possible path anyway, and then replace it with the long prefix so that conda itself does the binary prefix replacement at install time. 

For your problem, it would seem that `detect_binary_files_with_prefix` would just do the trick. Does it not work on Windows? The reason I needed an external tool from what conda build already does is that the emacs build directory (the work directory) was being hard coded, which conda build does not support.
