### ISSUE TITLE
Set target in package section [feature request]

### ISSUE THREAD

**Issue by ratstache** [conda/conda-build#2264]
## Problem

Currently the only way to change the target platform is using the built in way of handling variants. This involves including an additional file `conda_build_config.yaml`. When you try to set `target` in the package section it is completely ignored and when you try to set `target` in the outputs section it throws an error.  Something like:
```
Expecting win-64 got linux-64
```

## Request

Ideally we would like to be able to set target directly in the package section, but our needs could be met as long as that functionality is exposed and not bound to the use of `conda_build_config.yaml`. I took a look at doing this myself but I am unfamiliar with the code base and the reliance on `target_platform` seems to be entrenched in the variants logic and spread across quite a few files.

Please let me know what you think!

**Comment by msarahan** [comment]
Yes, I agree with you.  This needs to be fixed.  I think it'll need to be fixed by tweaking metadata.py's get_output_metadata method, so that the target attribute ends up overriding or setting the target_platform of the variant.  As you say, it is pretty tangled.  If a better overall structure for conda-build is obvious to you, please suggest it.  It has undergone a lot of organic growth and definitely could use a refactor.  Unfortunately, that's not a current priority.

**Comment by ratstache** [comment]
Hey, I think I've found a solution for this but I can't find the docs on actually building the project to be able to test it. Basically because it's failing in `tarcheck.py` at an assertion statement simply adding `self.config.target_subdir` to the array in this line https://github.com/conda/conda-build/blob/8a7c41dd37204f0d6b3d31240f5180b617192b2f/conda_build/tarcheck.py#L85 should fix it.

I wanted to test for side effects, but all it's essentially doing is not failing the build if info.json's subdir == target_subdir which I believe is the behavior that is intended with this anyways

**Comment by msarahan** [comment]
Yes, I think you're right.  That fix is appropriate.
