### ISSUE TITLE
`conda convert` should accept `--python` flag

### ISSUE THREAD

**Issue by dsludwig** [conda/conda-build#2270]
`conda convert` currently allows converting between platforms for pure-Python packages. It should also be able to change the Python version, since there are no `.pyc` files being saved.

cc @msarahan

**Comment by msarahan** [comment]
I think pyc files are always being saved - except for noarch packages.  Conda-convert regenerates them as necessary.  If we did a conda convert for python version, we'd have to wipe out all pyc's, and rebuild them.

In our chat, I was more thinking that conda-build could support output of pure-python packages to arbitrary platforms.  It is a case of matching the appropriate directory structure of the target platform, since pyc files themselves are platform independent.

**Comment by dsludwig** [comment]
Ah, okay. I was under the impression they were not there. That definitely makes adding this feature more involved.

**Comment by msarahan** [comment]
Nah, it's still easy. Just need to treat python packages specially, and basically run convert at the end of a build process over any non native target architectures. Should be reasonably easy.
