### ISSUE TITLE
conda build on Mac discards `# [not win]`

### ISSUE THREAD

**Issue by guyer** [conda/conda-build#2326]
I've got a [recipe](https://github.com/guyer/conda-recipes/tree/fipy_recipe/fipy) for a pure python package that takes different combinations of required packages depending on platform (specifically, some libraries it uses aren't available for Windows, either as conda packages or at all).

I append `# [not win]` to these requirements, but when I build on Mac, the resulting `info/recipe/meta.yaml` no longer has the platform selector. As a result, `conda convert -p all` doesn't produce a useful Windows package.

**Comment by msarahan** [comment]
I think this is more of a feature request than a bug report. Selectors apply at build time, and are not saved anywhere. At convert time, they are long gone. The meta.yaml in info/recipe is intended to be final: no changes expected after reading from disk. Meta.yaml.template contains the original recipe. If you want to submit a PR so that convert uses meta.yaml.template, that would be most welcome. Otherwise the lead time for me to do that is around 1 month.

**Comment by guyer** [comment]
I wasn't entirely surprised that the Mac build discarded the selector, but that's why I added
```
target_platform:  
  - noarch
  - win-64
  - win-32
```
in a `conda_build_config.yaml`. Shouldn't that provoke a Windows build that *does* see `# [not win]`?

I'd appreciate learning of a way to perform a pure-Python Windows build on a non-WIndows conda, but otherwise I'll look into submitting a pull request.

**Comment by msarahan** [comment]
What you're asking for, I think, is cross-"compiling".  This came up in https://github.com/conda/conda-build/issues/2270

We don't have a way to do that right now.  We don't technically need to run the Windows python to build windows packages - we only need to know the output folder structure.  It should be possible to have target_platform control some kind of post-build ``convert`` scheme.

If you have time for a PR, that would be wonderful.

**Comment by guyer** [comment]
We'll see!
