### ISSUE TITLE
conda-build package test for whole channel

### ISSUE THREAD

**Issue by argltuc** [conda/conda-build#2337]
In our current software development workflow we build packages for different platforms in our CI. The resulting artifacts are organised like a conda repository and given as once to the test and deploy stages with there platform depended jobs. To reduce complexity of projects CI configuration we want to use only one testing command for the test stage but handle all platforms.

Our first try was to use `conda-build --test ./builds/*/*.tar.bz2` Where `./builds/` represents our repository containing indexed `linux-64` and `win-64` folders. But this will lead in testing packages of a wrong platform.
Now our vision is a croot-like test command, which handle the input folder as a conda repository and uses only the subfolder regarding to test called platform.

Is it possible to test with conda-build a complete conda repository-like folder structure, that a linux-64 runner just handle linux-64 packages and not also win-64 packages?
Or could it an idea to extend conda-build with this testing feature?

**Comment by mingwandroid** [comment]
Can you not just change:

`conda-build --test ./builds/*/*.tar.bz2`

to:

`conda-build --test ./builds/linux-64/*.tar.bz2`

and:

`conda-build --test ./builds/win-64/*.tar.bz2`

.. depending on the machine you are running on?

**Comment by argltuc** [comment]
Of course, this will work. But exactly this we want to avoid, since it will explode our CI configuration.
Therefore we are looking for a quite smarter way of testing packages.

**Comment by mingwandroid** [comment]
I have no idea why you cannot implement exactly what you are asking conda-build to do in your own code. FWIW I am against any hard-coded prevention of testing artefacts from foreign architectures and/or machines because these days we have fairly mature technologies like QEMU and Wine that are able to do exactly that.

And, as you passed those tar.bz2 filenames to conda-build so you've  explicitly asked it to do just that.

**Comment by gabm** [comment]
I totally agree with you @mingwandroid that hard-coded exclusions are a bad idea, but I think @argltuc wants to achieve something different. He wants to test "all currently testable platforms" from a channel. The typical usecase is that your CI produces you a "channel" from multiple different-architecture runners... then you want to to run a test stage on this "channel" which could lead to something like:

- on the windows machine test win-32, win-64 and noarch, but no linux stuff
- on the intel linux docker image test linux-64 and noarch
- on the aarch64 docker image test linux-aarch66 and noarch
- ...

maybe that could be achieved by an additional command `conda-build --test-channel <channel>` for example.

**Comment by mingwandroid** [comment]
> "all currently testable platforms"

Here is the crux of the problem. Do you have QEMU running because you are bootstrapping a foreign arch on intel Linux? Are you wanting to test Wine itself here? Or Windows packages on Linux instead or ... I stand by my assertion that whatever hardcoded exclusions @argltuc have no place whatsoever in `conda-build` and can and should be done in a site-specific place, like the CI system itself.

Eventually, I want `conda-build` and `conda` to be aware of emulation technologies (and for us to package them) and then be able to make a determine as to what the "currently testable platforms" are, but we're not there yet, so until then we must allow everything (again, conda-build is *explicitly* being asked to test this exact set of .tar.bz2 files from the command-line so for now we must assume that the user has emulation technologies in place to do just that).

**Comment by mingwandroid** [comment]
If you want to go to the trouble of adding a `--skip-non-native` sub-option to the testing procedure then be my guest, but it needs nuancing so that it can be instructed to either skip or not skip `win-32` when running on `win-64`. It's not something I will spend any time on.

**Comment by gabm** [comment]
I totally understand your concern, there should not be hard-coded exceptions in CB. I don't think that CB has to be aware of emulating technologies at this point. But I do see a usage scenario for that. Let me explain:

When I instruct conda to install packages from a certain channel, i give it a http:// or file:// URL. Conda will expect, that in this URL it can find two subfolders "noarch" - and another of its own architecture (for example linux-64). So by default we instruct conda to install a package from a channel - and it picks whatever is available and suitable.

Now in CB when testing we'd like to have the same feature. Provide a file:// url (for example by --croot) and start testing according to the same logic: test packages from noarch and your own architecture. 

I think this symmetry with conda is very reasonable - specially because "testing a file" is actually "tricking conda into thinking that the folder of the file is actually a channel" according to #2301 .. so why not generalise and test "the whole channel"? according to the same scheme as conda does when installing/updating packages?

**Comment by mingwandroid** [comment]
Whether we provide a channel interface to testing or not is a different issue to what should happen when conda-build is asked to test a specific `.tar.bz2` file from the command-line though?

I have no opinion on testing all packages from a channel.

**Comment by gabm** [comment]
> Whether we provide a channel interface to testing or not is a different issue to what should happen when conda-build is asked to test a specific .tar.bz2 file from the command-line though?

I think what @argltuc wants to realise is a "channel-testing-interface"

**Comment by msarahan** [comment]
Yes, that's a reasonable idea.  I think it is out of scope for conda-build, though.  In order to implement such a thing for conda-build, conda-build would need to learn how to enumerate packages in channels.  That's the realm of anaconda-client.  I think the optimal implementation would be an add-on to anaconda-client that would loop over the channel's packages and use conda-build to test each package.

This is the kind of thing that the team here simply does not have time to do.  Our CI system has testing based on each package, not at the channel level.  This functionality is thus not something we can justify as advancing our internal platform.  We'd gladly review PRs to add this functionality, but have no spare cycles to dedicate otherwise.

**Comment by argltuc** [comment]
Yes, thats right... "testing a channel" is more of what I want to achieve...

@msarahan As far as I understand, the anaconda-client is for accessing the anaconda cloud. But I was talking about a local channel on the filesystem though. That would be indeed in the scope of `conda-build`, wouldn't it?

I'll contact our team and see which alternatives we have and whether we want to go into the process of implementing such feature.

**Comment by msarahan** [comment]
Yes, you're right.  Testing channels based on the filesystem could be different.  Fundamentally, if you enumerate packages in channels using information from repodata.json, then you should be able to use the same code for either anaconda.org or filesystem-hosted repos.

It's still out of scope for conda-build, IMO, but less so.

**Comment by argltuc** [comment]
After checking our options we decided, that we'll integrate such functionality into our own code. Though we believe it would fit to CB, its easier to build and maintain for us. Thanks for the discussion and your help.
