### ISSUE TITLE
Option to disable looking at local builds of packages (inverse of --use-local)

### ISSUE THREAD

**Issue by ezyang** [conda/conda-build#2447]
Right now, if I have a build of a package lying around, `conda build` will always pick it up, even if I don't want it to.

Additionally, there are no instructions for how to remove packages from the conda-bld repository.

**Comment by msarahan** [comment]
Using local packages is pretty core to conda-build.  I'm not sure that adding a flag to turn that off is useful enough to include it.

Conda-build is finding packages from what it calls "croot".  This is ``(miniconda root)/conda-bld`` by default, but can be changed with:

* the ``--croot`` CLI flag to ``conda build``
* the croot keyword to the conda-build api
* the root-dir configuration option in .condarc: https://conda.io/docs/user-guide/configuration/use-condarc.html#specify-conda-build-output-root-directory-root-dir
* the CONDA_BLD_PATH environment variable

You can clear the built packages with ``conda build purge-all``.  If you delete packages manually from any of the folders in croot, make sure to run ``conda index`` on those folders, so that the indexes in them are up to date.

**Comment by ezyang** [comment]
OK. Can we give this issue some Google juice so that it shows up when you search "conda-bld remove"? :)
