### ISSUE TITLE
Build variants: leftovers from previous variant build

### ISSUE THREAD

**Issue by AntoineD** [conda/conda-build#2460]
With anaconda 4.4 and conda-build 3.0.27, I noticed that when building a recipe with multiple variants the build directory is kept from on variant to another. This leads to nasty side effects like some targets not rebuilt or linked with wrong libraries.
I have to manually clean the build, no big deal but this is quite surprising.
Is it intentional?

**Comment by msarahan** [comment]
Sort of?  I think it's a bug that things aren't being cleared.  The "build directory" is a little ambiguous.  Do you mean the work folder, or the build (or host) prefix?  The build and host prefixes definitely should be getting cleared.  For the work folder, it's a little more complicated.  I think the crux of the problem is that you do not have tests, and we don't move to work folder when there are no tests.  That needs fixing (also, the final iteration of tests doesn't move the work folder, because the moving happens at the beginning of each test iteration).

Here's how it works (this is part of docs I'm writing up now).    

Mechanics of looping over variables
==========================

Looping in conda-build over your variants happen in two places. The first loop
happens on "top-level" metadata - variables that change things that happen
before or during the build phase. The second loop happens on outputs.

First, your variants are "distributed" across the top-level metadata. Any
variant variables that affect the outcome of packages in this step are
considered "top-level." For any top-level variable, only one value is propagated
into the internal second loop. Anything that did not affect the outcome of
packages at this step is saved for the next loop with all of its values.

Availability of source and artifacts
----------------------------------

* The build, host, and test prefix are cleaned between iterations of the outer loop
* Before each test phase, the work directory, including your source, is moved to
  a backup name. Your work directory only remains if you have
  the --no-remove-work-dir flag set.
* Any source_files you have specified in your test section are copied into the
  testing work folder (separate from the building work folder

Time implications
--------------------

* Source is re-provisioned after each iteration of the top-level metadata loop.
  This is not true of the inner outputs loop.  Inner loops can thus be faster.

**Comment by AntoineD** [comment]
You're right, I have no test in the recipe.
I guess the build directory in by default where the sources are, i.e. in work folder.
Thx a lot for the explanations.
