### ISSUE TITLE
Converting conda packages to wheels (and vice versa)

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#2490]
Would very helpful to have an option in `conda convert` to allow a `conda` package and its dependencies into a `wheel`. Potentially even the reverse operation should be possible. Should help further bridge the gap between these two great Python communities.

**Comment by mandeep** [comment]
``conda convert`` converts packages between architectures. I think this is a feature request for ``conda skeleton`` meaning this may be a duplicate of #2185.

**Comment by msarahan** [comment]
I think the conda issue at https://github.com/conda/conda/issues/5202 is more appropriate.  Conda-build can already "convert" a wheel to a conda package - when you have a wheel source, and you use pip to install it.

This is a terrible mess when shared libraries are involved.  What is necessary, in my opinion, is a two-way scheme to:

1. remove unrelated shared libraries from wheels when creating a conda package, and replace them with conda dependency metadata
2. when converting a conda package to a wheel, bundle necessary shared libraries from other packages.

Number 1 is pretty horrible.  Can you imagine the binary incompatibility that might arise?

The first thing that needs to be investigated for this issue is what information is even available.  Do wheels say what files they've included as shared library deps?  If not, I don't think there's much we'll be able to do (until they do?)  Next, what about binary compatibility?  We'll need to determine what conda package dependency is appropriate to match the stuff in the wheel.

Number 2 is relatively easy - probably mostly a matter of creating an env with a package, then using auditwheel.  I still don't think this is the right way to go, though.  I don't understand how wheel implements general-purpose non-python packages, and without that notion, this conversion is fraught with confusion.

**Comment by jakirkham** [comment]
Right, maybe we should focus on 2 here both because it is more cleanly cut and it seems that issue ( https://github.com/conda/conda/issues/5202 ) is moving towards territory covered by 1.

Certainly this shouldn't be allowed for an arbitrary package. Having `python` required for `build` and `run` should be necessary for this sort of conversion to proceed. Creating an environment does seem like a reasonable way to go about it. Not sure if there are other steps that would need to be considered.

Should add that I'm thinking about this in conjunction with issue ( https://github.com/conda-forge/conda-smithy/issues/608 ) in an attempt to consolidate the building effort of wheels and conda packages a bit more. Will need more discussion amongst both communities to determine whether this is reasonable. Just getting it started at this point.
