### ISSUE TITLE
Use GCC with cross-compiling chain on OSX

### ISSUE THREAD

**Issue by rainwoodman** [conda/conda-build#2515]
While porting our compilation to the new cross-compilation framework, I discovered that some of our packages do not like clang -- for a variety of reasons that are hard to track down making it a sinkhole of person-hours.

Is there a way to specify to use gcc on OSX platforms for cross compilation?

I am also very concerned about the plan that in the future conda-build will use clang for both Linux and OSX. clang may be technologically more advanced and preferable for a variety of unspeakable reasons (e.g. easier to support on macs). Not all packages will compile cleanly with clang -- especially if they were written on Linux/Cray.

**Comment by mingwandroid** [comment]
conda-build doesn't have any opinion on which compilers to use. You are free to use whatever you want for your own packages. Read up on the cross-compilation documentation for how to do this, it's very easy.

On macOS, the writing is in the wall though, GCC is far from well maintained there while clang is.

As a distribution, we are forced to make difficult choices here. In particular libc++ and libstdc++ cannot in general be linked to the same program.

Our gdal stack languished in an old broken state for over a year because half of its dependencies were built with g++ and half with clang++. We had to make a choice and we made the right one.

With C it's not so bad and you should have no problem linking clang and gcc built libraries together, but here we have yet to run into a package that we still care about that requires gcc on macOS (and nor have conda-forge and they have many more packages than we do). When we do I don't expect it'll be very hard to fix it so it works with clang.

**Comment by rainwoodman** [comment]
The google doc says I am supposed to write a set of customized compiler wrappers/activate scripts to support any customized compiler -- is this the *very easy* approach you refer to?  If it is indeed easy -- would it be useful for conda-build to ship with a package, or a config.yaml, or a meta.yaml example that switches to gcc on OSX platforms?

I understand the documentation made good efforts to be clear and helpful, but still the setup itself still consists of several scripts, each of which contains many compiler flags that largely relied on conventions, and not totally respected by software package authors. In fact I was to make use of the customization for the Cray CC compiler wrappers but I have been deferring this again and again by the scare factor.

**Comment by mingwandroid** [comment]
> The google doc says I am supposed to write a set of customized compiler wrappers/activate scripts to support any customized compiler -- is this the very easy approach you refer to? 

You seem a bit confused about what the `Anaconda Distribution` is and its relationship with `conda-build`.

`conda-build` is a general purpose build system. Historically it has been a bit less general purpose and hard-coded things about toolchains and compilers but this is not how it should be. It should know nothing about compilers or `*FLAGS`. Those terms should, eventually, not appear anywhere in its source code.

The `Anaconda Distribution` is a curated set of tools, libraries and packages that work well together and run on `Linux`, `macOS` and `Windows`. To that end, the `Anaconda Distribution` team have picked what we consider the technologies and toolchains that will deliver the best software on each of these platforms. To untangle compilers and `*FLAGS` from `conda-build` we have decided to use the `conda` package manager's ability to source activation scripts. This enables `conda-build` to be used on platforms we do not personally care about (e.g. Cray).

To answer the 'very easy' thing since you seem to mention it a lot and even emphasized it with italics, you could simply install `GCC` from `Homebrew` and write a package called `rainwoodman-gcc_osx-64` containing nothing but a single `activate-gcc.sh` script that contains:

```
export CC=/usr/local/bin/gcc
export CXX=/usr/local/bin/g++
```

.. and have your `conda_build_config.yaml` contain:

```
c_compiler:
  - rainwoodman-gcc
cxx_compiler:
  - rainwoodman-gcc
```

.. what you gain in simplicity you lose in quality, but you can see that setting things up so that *some* `GCC` is used on macOS is far from difficult.

Personally if I was going to make a `GCC` toolchain on `macOS` (if you want me to do this then please get in touch with sales@anaconda.com) I would use more or less the same [activation meta-package and scripts we use for Linux](https://github.com/AnacondaRecipes/aggregate/tree/master/ctng-compilers-activation-feedstock/recipe), though adopting the flags where necessary so they apply to `macOS`. Then for the actual toolchain implementation I would, as we did on Linux, use a [crosstool-ng based approach](https://github.com/AnacondaRecipes/aggregate/tree/master/ctng-compilers-feedstock/recipe) combined with the `cctools` and `ld64` packages that are built as part of the current [clang-based macOS toolchain implementation](https://github.com/AnacondaRecipes/aggregate/tree/master/llvm-compilers-feedstock/recipe).

Now I will admit that this is not necessarily easy. It *might* be, I don't know if you are familiar with crosstool-ng and macOS internals.

In your case, with Cray, you probably do not want nor need to get your hands dirty with compiling compilers and can go for the more homebrew based approach.

As to your point that some software is badly written and/or has no build system to speak off such that it may ignore your env. vars, well, yes, we ran into some of that too, and we have to patch that software. Luckily, for the software we need to build, that stuff is by *far* in the minority (I would estimate about 1 in 100 of the packages we build need such patching). I don't really see the relevance though, obviously you want to optimize for the general case and need to workaround the rest.

**Comment by rainwoodman** [comment]
Thanks for the example now I see it indeed is very simple -- I'll assume some sort of deactivate script is also necessary?

I see that a full tool chain is difficult due to the need to have supporting libraries. So I will avoid compiling compilers (Unless Cray pays me to do that). We are a bit urgent to have everything working since we are submitting the code paper. One of my frustration was nothing I planned for this overhaul with the new conda-build is working; but so it happens.. Thus for now we'll probably just follow your example to setup to use either the native clang from Travis and add a wrapper for the gcc and libgcc packages which have been working fine previously, and also link against the current mpich and openmpi on anaconda. 

We do sample different subset of packages, hence the impression can be different. Anaconda has probably 1000s of packages -- then the strange packages are indeed rare -- but our sample size is only 10, and all of them are very specific to a sub domain -- two or three out of 10 is a lot, especially when every author thinks they have figured the perfect way of packaging...

**Comment by mingwandroid** [comment]
> I'll assume some sort of deactivate script is also necessary?

If these compiler activation scripts are only ever used from conda-build then it's not necessary to deactivate, but if you need to activate your host env during a build to investigate failures then being able to deactivate is better so you may as well. I backup and restore existing values in our activate and deactivate scripts respectively.

**Comment by mingwandroid** [comment]
I do not see why you would want to use the native clang from Travis though when you can use our more modern clang.

**Comment by rainwoodman** [comment]
Indeed. After properly using openmpi and mpich that are built with the cross-compilation tool all of our packages now compiles cleanly with the anaconda 5.x toolchain -- gcc on linux-64 and clang on osx; and also after the `libgfortran.dylib not found` error was addressed by the rpath hack. Working on an actual mac did help a lot -- I am thankful my wife contributed hers for this.

So there is no longer a need to switch to gcc based compilers on osx from our side. Thanks for the help!

**Comment by mingwandroid** [comment]
Good to hear. Thanks for being open to trying this new stuff and helping out with the mpi recipes.
