### ISSUE TITLE
Compiler support for MSVC 2017

### ISSUE THREAD

**Issue by peterjc123** [conda/conda-build#2541]
It seems that the compiler MSVC 2017 is always ignored even if I specified the flags when I also have 2015 installed.
```CMD
set DISTUTILS_USE_SDK=1
set MSSdk=1
```
There's also no support for MSVC 2017 runtime libraries, just like `vc14` for MSVC 2015.
I wonder whether it is possible to use MSVC 2017 as the compiler and distribute the compiled packages.

**Comment by msarahan** [comment]
You need to use conda-build 3 and activation scripts that point to VS 2017.  Conda-build will not be adding support for new VS versions.  That capability is deprecated, and has been replaced by people explicitly specifying compiler packages.

There's a couple of blog posts talking about this at
https://www.anaconda.com/blog/developer-blog/package-better-conda-build-3/
https://www.anaconda.com/blog/developer-blog/utilizing-the-new-compilers-in-anaconda-distribution-5/

There's examples of how to create the activation scripts at https://github.com/AnacondaRecipes/aggregate/tree/master/vs2015

I started to do vs2017 also at https://github.com/AnacondaRecipes/aggregate/tree/master/vs2017, but it's not fully tested to work.

When you have your new compiler package ready, you'll need an entry in conda_build_config.yaml so that it gets chosen.  For example, we have our list of compilers used here: https://github.com/AnacondaRecipes/aggregate/blob/master/conda_build_config.yaml#L15

Keep in mind that several of those keys are "zipped_keys" meaning that the collections are not independent loops, but associated.  This is how we keep a given python version associated with a particular compiler, so that we remain binary-compatible with upstream python.  You don't have to keep that association if you don't want it, but you should really know what you're doing before you make that decision.

**Comment by peterjc123** [comment]
Thanks @msarahan, I managed to build with VS2017 with a modified version of your scripts.

**Comment by mingwandroid** [comment]
Can you share you modifications?

**Comment by peterjc123** [comment]
@mingwandroid 
Here it is. [vs2017.zip](https://github.com/conda/conda-build/files/1545424/vs2017.zip)
1. Extract the package and build it using `conda build .`. Some paths and version numbers are diferent, just change them for your environment.
2. Copy the `conda-build-config.py` into your packages and build them in a regular way.
