### ISSUE TITLE
blas *-devel libraries generating additional build variants

### ISSUE THREAD

**Issue by sdrobert** [conda/conda-build#2543]
This is a duplicate of #7630 on Anaconda/issues, but I've closed that and opened here on the advice of @msarahan. I'm using conda 4.3.30.

Here's a toy example:

meta.yaml:
``` yaml
package:
        name: test
        version: 0.0

source:
        path: .

requirements:
        build:
{% if blas_impl == 'mkl' %}
                - mkl-devel
{% endif %}
{% if blas_impl == 'openblas' %}
                - openblas-devel
{% endif %}
```
conda_build_config.yaml
``` yaml
blas_impl:
        - mkl
        - openblas
```

Using the ``print_yaml`` code from the [conda build 3 blog post](https://www.anaconda.com/blog/developer-blog/package-better-conda-build-3/):
```
>>> print_yamls('dumb_recipe')
package:
    name: test
    version: '0.0'
source:
    path: /Users/cl_mac/Projects/Code/pydrobert/kaldi/dumb_recipe
requirements:
    build:
        - mkl-include 2018.0.1 h8158457_4
        - mkl 2018.0.1 hfbd8650_4
        - mkl-devel 2018.0.1 h5cfdff2_4
        - intel-openmp 2018.0.0 h8158457_8
    run:
        - mkl >=2018.0.1
extra:
    copy_test_source_files: true
    final: true

--------------------------------------------------
package:
    name: test
    version: '0.0'
source:
    path: /Users/cl_mac/Projects/Code/pydrobert/kaldi/dumb_recipe
requirements:
    build:
        - libopenblas 0.2.20 h6c53463_3
        - libgfortran 3.0.1 h93005f0_2
        - openblas-devel 0.2.20 h1e4b922_3
extra:
    copy_test_source_files: true
    final: true

--------------------------------------------------
package:
    name: test
    version: '0.0'
source:
    path: /Users/cl_mac/Projects/Code/pydrobert/kaldi/dumb_recipe
requirements:
    build:
        - mkl-include 2018.0.1 h8158457_4
        - mkl 2018.0.1 hfbd8650_4
        - mkl-devel 2018.0.1 h5cfdff2_4
        - intel-openmp 2018.0.0 h8158457_8
extra:
    copy_test_source_files: true
    final: true

--------------------------------------------------
package:
    name: test
    version: '0.0'
source:
    path: /Users/cl_mac/Projects/Code/pydrobert/kaldi/dumb_recipe
requirements:
    build:
        - libopenblas 0.2.20 h6c53463_3
        - libgfortran 3.0.1 h93005f0_2
        - openblas-devel 0.2.20 h1e4b922_3
    run:
        - libopenblas >=0.2.20,<0.2.21.0a0
extra:
    copy_test_source_files: true
    final: true

--------------------------------------------------
```
As you can see, the build matrix is of size 4 instead of 2. The additional matrices appear to derive from either including or excluding the library in the list of runtime dependencies. Replacing ``mkl-devel`` with ``mkl`` and ``mkl-include`` drops the matrix to one less, and replacing ``openblas-devel`` with ``openblas`` drops it as well. If you make both changes, you get:
```
>>> print_yamls('dumb_recipe')
package:
    name: test
    version: '0.0'
source:
    path: /Users/cl_mac/Projects/Code/pydrobert/kaldi/dumb_recipe
requirements:
    build:
        - mkl-include 2018.0.1 h8158457_4
        - mkl 2018.0.1 hfbd8650_4
        - intel-openmp 2018.0.0 h8158457_8
extra:
    copy_test_source_files: true
    final: true

--------------------------------------------------
package:
    name: test
    version: '0.0'
source:
    path: /Users/cl_mac/Projects/Code/pydrobert/kaldi/dumb_recipe
requirements:
    build:
        - libgfortran 3.0.1 h93005f0_2
        - libgcc 4.8.5 hdbeacc1_10
        - openblas 0.2.20 ha880b72_0
extra:
    copy_test_source_files: true
    final: true

--------------------------------------------------
```
Which does not contain the entries with runtime dependencies. This is not a great workaround because it decouples the versions of the include files and shared libraries.

As for the run exports, if the associated library is manually included in the runtime requirements, you can get some funny duplication:
```
run:
        - libopenblas
        - libopenblas >=0.2.20,<0.2.21.0a0
```
probably harmless, though.

Thanks,
Sean

**Comment by msarahan** [comment]
I'm not sure why this happens.  I recommend adjust your recipe to the following, which fixes it for me:

```
package:
  name: test
  version: 0.0

source:
  path: .

requirements:
  build:
    - {{ blas_impl }}-devel
```

With conda-build 3.1.0, the simplified hashes cut out the variant completely because conda-build doesn't seem to be able to match up against stuff in the if statements.  You end up with only one output.  I can try to fix that.  I guess it's just a matter of tweaking regexes.  Really, you should prefer selectors over jinja2 blocks for this, though.

**Comment by sdrobert** [comment]
Thanks for the feedback. I'm actually trying to build an ``mkl`` and ``nomkl`` version of this library, so ``{{ blas_impl }}-devel`` doesn't work for OSX (which uses Accelerate). Being insensitive to variables defined in jinja blocks might explain why "nomkl" isn't appearing in those builds' hashes.

Is it possible to specify selectors as variants? I really like conda, and I'm trying to do things "the right way."

**Comment by msarahan** [comment]
#2547 fixes the conditionals, but it's going to be pretty hard to get that perfect.  Completely generalized regexes are not really attainable in my experience.

You can specify selectors as variants, because meta.yaml is parsed iteratively.  You may see warnings about variants not being defined yet - I'm working on squelching those.  Those happen in earlier iterations.

We've done some stuff around this blas stuff, but I wouldn't say we've isolated a single "right way" to do things yet.  The numpy recipe has our work: https://github.com/AnacondaRecipes/numpy-feedstock/blob/master/recipe/meta.yaml#L26

You can see some variants-in-selectors at https://github.com/AnacondaRecipes/numpy-feedstock/blob/master/recipe/meta.yaml#L38

**Comment by sdrobert** [comment]
That's perfect, thanks!
