### ISSUE TITLE
Run requirements in split packages not being honored

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda-build#2589]
```
[root@d50e35878ecf test]# cat meta.yaml 
package:
  name: test
  version: 1.0.0

requirements:
  build:
    - cffi

outputs:
  - name: test
    requirements:
      run:
        - matplotlib

[root@d50e35878ecf test]# conda build .

[root@d50e35878ecf test]# tar -xf /opt/conda/conda-bld/linux-64/test-1.0.0-0.tar.bz2 info/index.json -O
{
  "arch": "x86_64",
  "build": "0",
  "build_number": 0,
  "depends": [],
  "name": "test",
  "platform": "linux",
  "subdir": "linux-64",
  "timestamp": 1513632640258,
  "version": "1.0.0"
}
```

**Comment by nehaljwani** [comment]
I am guessing this is happening because the name of the package and the output name are same. 

I can across this issue when try to do: `conda skeleton rpm libsoup-devel --recursive` and after a `conda build`, `libsoup-devel` didn't depend on `libsoup`

**Comment by msarahan** [comment]
Yes, you guessed right.  Top-level requirements clobber outputs when the name is the same.  If you need this for whatever reason, put all of the requirements in the top-level area, and they'll be applied to the output.  When I have an output that is the same name as the top-level metadata, I only put ``name: test`` and nothing more, so that it's clear that it's just the top-level metadata.

It would be good to fix this so that top-level stuff is only build-time when outputs are present.  I think that's pretty minor, though, so absent a PR, it could be a while.

**Comment by msarahan** [comment]
fixed by https://github.com/conda/conda-build/pull/2595/commits/2cb2b19b5e7929fd9b6e0c93fe282f0334ac95e2 and the rest of that PR.
