### ISSUE TITLE
conda build purge appears to have no effect.

### ISSUE THREAD

**Issue by rainwoodman** [conda/conda-build#2592]
conda build purge appear to keep all files in conda-bld untouched. Given that the invocation syntax is degenerate with regular package named purge, I suspect the feature is dropped at some point.

Is there a replacement?

**Comment by msarahan** [comment]
``conda-build purge`` removes only build folders, so things named liked mypackage_912471073, where that latter number is milliseconds since epoch.

``conda-build purge-all`` removes all built packages as well (removes folders such as conda-bld/linux-64).  Both of these are tested in the test suite, and they are known to be working.  If you see otherwise, you may be having permissions problems.

**Comment by rainwoodman** [comment]
I was thinking of removing the built packages.
purge-all and purge are not documented in `--help`, so I relied on the message output of conda-build.

```
####################################################################################
Source and build intermediates have been left in /home/yfeng1/anaconda3/install/conda-bld.
There are currently 7 accumulated.
To remove them, you can run the ```conda build purge``` command
```
The message suggested `conda build purge` would have removed the built artifacts ( though it may actually not meant so `source and build intermediates ....`.

**Comment by rainwoodman** [comment]
I can confirm conda build purge-all indeed purges all.

**Comment by tovrstra** [comment]
@msarahan Can you re-open this bug? `conda build purge` only works in the `base` environment. To make it also work for other environments, the following line is a useful workaround, after loading a different environment:

```bash
export CONDA_BLD_PATH = ${CONDA_PREFIX}/conda-bld
```

**Comment by tovrstra** [comment]
I did some testing to better understand the issue. Everything actually works. The only real problem is that the screen output and the documentation could be improved. This is my test:

```bash
# Instructions assume a Conda is installed in ${HOME}/miniconda3

# 1) Activate conda and create a test env
source ~/miniconda3/etc/profile.d/conda.sh 
conda activate
conda create -n test python=3.7 conda-build -y
conda activate test

# 2) Get some recipe for testing and build the package
git clone https://github.com/conda-forge/cpplint-feedstock.git
cd cpplint-feedstock/
conda build recipe

# 3) Check that the package is present
ls -alh ~/miniconda3/conda-bld/noarch/cpplint-1.4.4-py_0.tar.bz2

# 4) Try the purge command. Observe that it did not remove the cpplint
# package, in line with comments above
conda build purge
ls -alh ~/miniconda3/conda-bld/noarch/cpplint-1.4.4-py_0.tar.bz2

# 5) Try the purge-all command, which does remove the pacakge
conda build purge-all
ls -alh ~/miniconda3/conda-bld/noarch/cpplint-1.4.4-py_0.tar.bz2  # This will fail.
```

So all is fine. I just have a few suggestions to improve the documentation and screen output

1) The end of the output of a package build could be improved. It currently prints:

    ```
    Source and build intermediates have been left in /home/toon/miniconda3/conda-bld.
    There are currently 55 accumulated.
    To remove them, you can run the ```conda build purge``` command
    ```

    Also printing a lines as follows would be helpful:

    ```
    In total XXX packages have accumulated in /home/toon/miniconda3/conda-bld.
    To remove these and the intermediates, you can run the ```conda build purge-all``` command.
    ```

2) The output of `conda build --help` can be improved. Now it does not mention the `purge-all` command:

    ```
    positional arguments:
      RECIPE_PATH           Path to recipe directory. Pass 'purge' here to clean
                            the work and test intermediates.
    ```

3) Maybe also mention `purge-all` in `docs/source/user-guide/recipes/debugging.rst`.

Somewhat related to this issue, and also source of my initial confusion, is that `conda build` stores packages in `conda-bld` in the base environment, even when another env has been activated. Is this the intended behavior? It seems more logical to store packages in `${CONDA_PREFIX}/conda-bld` instead.

**Comment by tovrstra** [comment]
The source of my confusion with this issue is the location where `conda-build` stores packages. This can vary in rather odd ways:

- When `conda-build` is installed in the base env, locally built packages will always be stored in `~/miniconda3/conda-bld` (in the base environment), even when another env is currently active. The latter situation is not very intuitive.

- Only when `conda-build` is *not* installed in the base env, and just installed in the another env that is currently active, then packages are stored in `~/miniconda3/envs/<envname>/conda-bld` (in the current environment, not the base environment). This is fine.

This may sometimes give the impression that `conda build purge` and `conda build purge-all` are not working, simply because they clean up files in a directory that one might not expect.

It would be more sensible to determine the default for `--croot` from the active environment. The current implementation derives it from the location where `conda-build` is installed, and when `conda-build` is present in the base environment, it gets precedence over an installation in the active environment.

**Comment by mattchan-tencent** [comment]
It seems this bug is still active. I ran into it as well. Setting CONDA_BLD_PATH is a temporary workaround as mentioned.

P.S. Hi @tovrstra !

**Comment by tovrstra** [comment]
@mattchan-tencent Yep, I guess this is related to the way the conda is designed. Even when a sub env is activated, conda commands use the installation in the base env. To see this, activate a sub env and run the following:

```bash
which conda
echo $CONDA_EXE
```
