### ISSUE TITLE
SRC_DIR isn't path to source in test phase

### ISSUE THREAD

**Issue by kalefranz** [conda/conda-build#2608]
Using conda-build 3.2.0.  I'd like to hook in conda's unit tests into the test phase of package builds.  Normally I'd think to do this just with with something like

```
test:
  commands:
    - py.test {{ SRC_DIR }}/tests
```

or maybe `py.test $SRC_DIR/tests`.  Either way.  But SRC_DIR doesn't actually point to the source directory during the test phase.  Rather, it's something like

    SRC_DIR=/Users/kfranz/miniconda/conda-bld/conda_1514581679049/test_tmp

which only contains `conda_test_runner.sh` and a couple related files.

I know at one point what I'm trying to do worked.  I'm guessing this change was intentional though, which is fine.  But is there another way to access the actual source code for a build during the test phase?

Along these lines, this is exactly the reason it would be good to have source packages.  So that, at a later time, say when we release a new version of a dependency for the package in question (e.g. release a new version of `requests`, and I want to know if the existing packages for conda work with that new version), we can go back and test the previously-built package with that new dependency.  You'd often need the source code to do that though, since the tests aren't always bundled with the built package.

**Comment by mingwandroid** [comment]
For AD 5 we changed testing so that packages are atomically testable (run a shell installer with the `-t` flag to do perform a test on all packages). This means you need to identify any files or folders you need from the source code that are to be copied into the package for use at test time.

To identify the files you want, try:

```
test:
  source_files:
    - source-dir-file1
    - source-dir-dir/**
  files:
    - recipe-dir-file
```

> this is exactly the reason it would be good to have source packages

They're orthogonal because in nearly all cases *very* little of the source is needed for testing and it is important that packages should be atomically testable (or at least carry with the the essential files needed for testing). Having source packages is fine, and we do have them but not due to wanting to test. I want source files for reproducibility, license compliance and to allow source-level debugging.

> since the tests aren't always bundled with the built package.

They should always be.

**Comment by kalefranz** [comment]
Thanks!
