### ISSUE TITLE
Build prefix failed with prefix length 255 and (!) results in empty archive

### ISSUE THREAD

**Issue by aothms** [conda/conda-build#2640]
### Actual Behavior

My package fails on prefix lengths greater than 255, which I guess I can live with, but the resulting archive is empty. The log is basically the following:

~~~
## Package plan ##
  environment location: {...}/conda-bld/{...}/_h_env_placehold_placehold_placehold_placehold_{... at infinitum}

...

Build prefix failed with prefix length 255

...

## Package plan ##
  environment location: {...}/conda-bld/{...}/_h_env_placehold_pla

{compiling}

{installing into {...}/conda-bld/{...}/_h_env_placehold_pla}

...

No files or script found for output
~~~

With some random print statements in conda-build/build.py I found out that:

* Initially [1] `new_prefix_files` is actually correct as `m.config.host_prefix` is set to the 2nd 80 char prefix
* But subsequently, `output_d['files']` [2] is empty as `m.config.host_prefix` now points to the original 255 char prefix (which is indeed empty on the file system) as `m` has been changed by the loop iteration [3]. This is an **empty set** minus a whole bunch of original files.

[1] https://github.com/conda/conda-build/blob/master/conda_build/build.py#L1226
[2] https://github.com/conda/conda-build/blob/master/conda_build/build.py#L1258
[3] https://github.com/conda/conda-build/blob/master/conda_build/build.py#L1252

Not sure if this is helpful or significant

### Expected Behavior

A non empty archive uploaded to anaconda as python module is properly installed into prefix

### Steps to Reproduce

Have a look at https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.6.0/conda on 64bits linux

**Comment by msarahan** [comment]
Thanks for reporting.  I don't think we anticipated that people would be installing to paths greater than 255 characters.  That goes back to when the prefix used to be 80 characters, which was way too short - that was the major breaking change conda build 2.0, back in summer of 2016.

This fallback logic hasn't seen much exercise since the ecosystem stabilized with the 255-char prefix.  I'm not entirely surprised that it has suffered bit-rot.  I'm short on time right now to fix this.  If you submit a PR with a test (or better yet, a fix), I'll try to prioritize it.
