### ISSUE TITLE
Specify system toolchain in conda_build_config.yaml

### ISSUE THREAD

**Issue by Sarcasm** [conda/conda-build#2689]
With conda build 3 we can specify a "symbolic" compiler with `compiler('c')`, and specify some specific compiler(s) in conda_build_config.yaml.

If I wanted to specify the system compiler in conda_build_config.yaml, how should I proceed?
Should I make a fake compiler package that does nothing or is there a better way?

**Comment by msarahan** [comment]
It depends what you're trying to achieve.  Are you trying to reuse our recipes that already have the "symoblic" compiler (which is a good term, by the way)?  If so, I recommend a fake compiler package.  A fake compiler package still affords you some opportunity to impose constraints on runtimes to ensure that your package isn't broken by installation of incompatible software.

If you are writing your own recipes and want to use the system compiler, why use the "symbolic" compiler dependency at all?  You're not benefiting from it.  We have fallback paths that should still use system compilers, but you're losing out on the benefits of using our compilers (the greatest benefit to a package builder is much greater binary compatibility with everything else we build).

So, I think I'd really ask why you want to use system compilers.  Some people think they need to use them for CUDA support.  We have GCC 5.4 packages available that work for that, but I need to write up an example for how to specify that version.  It's simple - just another field in conda_build_config.yaml:

```
c_compiler_version:
  - 5.4     # [linux]
```

Do you have some other reason for wanting to use a system compiler?

**Comment by Sarcasm** [comment]
> Are you trying to reuse our recipes that already have the "symoblic" compiler (which is a good term, by the way)?

Yes, I'd like to be able to reuse the recipes provided by other projects, but I also like to experiment with various toolchains. The system one, and some others, built from source.
So I guess, the fake compiler is the way to go, thank you.

My issue is not related to CUDA, but I have different scenarios in mind.
One of them, is to improve the dependency management for simple C++ projects, where I want to keep working as usual, using my system compiler, but experiment with conda to handle the dependencies.
Right now, there are a lot of CMake abuses to do this, and there are quite a few other methods (conan, nix, vcpk, cget, hunter, ...). For now I like conda better because it seems more cross platforms, the documentation is good, and some of its design choices, it integrates well with existing practices.

Another use case I have in mind. I use some softwares that is supported on a given distribution, e.g. CentOS 7. Oftentimes, these softwares are extensible in C++ and/or Python.
Since I have to use the platform of reference, which comes with a toolchain they certified their software on, I'd like to reuse the system compiler to build the extensions.

Out of curiosity, regarding `c_compiler_version`.
The 5.4 compile for example, is available on anaconda, but not all anaconda packages are built against this version?
If it was important that my packaged are built against this version, I would have to rebuild the recipes with these settings, right?
I don't consider this an issue at all, but I just like to make sure my understand is correct.

**Comment by msarahan** [comment]
The major advantage of the dynamic pinning in conda-build 3 (run_exports, as well as the pin_subpackage and pin_compatible jinja2 functions) is that you define your known compatibility bounds on the upstream package.

So, for example, our compiler packages set their run_exports to something like this:

{{ pin_compatible('libstdcxx_ng', max_pin=None) }}

The behavior of these is documented at https://conda.io/docs/user-guide/tasks/build-packages/variants.html#extra-jinja2-functions, so I won't go into it too much.  Suffice to say, we capture the backwards-compatible nature of libstdc++ - newer libstdc++ will work for packages built with older g++, but not vice versa.

If you use the 5.4 gcc, those packages will be compatible with both other gcc 5.4 packages and gcc 7.2 packages.

You only need to rebuild dependencies and such when packages depend on mutually exclusive dependencies.  For example, HDF5 1.8 and 1.10 are not compatible.  We build out variants of things that use them so that we can support both at once.  Only one HDF5 version can exist in an environment at a time.

Regarding system compilers: CentOS 7 is fine, and I agree with your inclination on certification.  Our toolchain is a little better in that we use older glibc (2.12, corresponding to CentOS 6), so your packages built with our compilers will be more backwards compatible than if you built them on CentOS 7.  It will, however, require you or your users to either use conda (which will track your runtime needs appropriately) or ship the runtimes yourself.  The CentOS compilers are engineered to not need additional runtimes - they statically link in a bunch of the newer stuff.  It's a frankenstein's monster, but it works well enough I guess.

**Comment by Sarcasm** [comment]
Ah, thanks for the details.
I was wondering what toolchain was used to build the packages on Anaconda, because by default it looks like I got the gcc 7.2 version. However, I guess I'm just getting the most recent version by default. But you build with the "most ancient" version, for compatibility reasons.

Regarding the pinning, and if I wanted to make a fake compiler package.
Will I have to replicate the runtimes like `libstdcxx_ng` in my fake package?
A package built with the anaconda toolchain, with has `run_exports`, declares something like `libstdcxx_ng` as a runtime dependency.
If I fake the compiler, the prebuilt anaconda packages will require this dependency same dependency, or the run_export dependency of my compiler?
Intuitively, I would say that I need to expose the run_export, or that I should just recompile if I use a toolchain slightly different from anaconda.

**Comment by Sarcasm** [comment]
I'm closing, my initial question was answered, and even more!
Thank you.

**Comment by mingwandroid** [comment]
> I was wondering what toolchain was used to build the packages on Anaconda, because by default it looks like I got the gcc 7.2 version. However, I guess I'm just getting the most recent version by default. But you build with the "most ancient" version, for compatibility reasons.

Just to clarify this, we build nearly everything (except some CUDA-related things) with GCC 7.2 on Linux, but this GCC 7.2 was built on CentOS6 (just so that it can be used on CentOS6). More importantly, it is a pseudo-cross compiler (built with crosstool-ng) that targets CentOS6 (glibc 2.12, kernel 2.6.32). Using ancient compiler technology is not a viable strategy.
