### ISSUE TITLE
Ways to add requirements on OS versions

### ISSUE THREAD

**Issue by peterjc123** [conda/conda-build#2704]
I wonder whether there is way to add requirement in the build section of meta.yaml to specify os versions. Currently, I have to publish a package, sth like `windows-legacy` and make two same packages with or without the tracking feature.  Is there a better solution? Maybe sth like this.

```yaml
build:
    - win >= 6.2 # kernel version, or major version, anything like that
```

**Comment by msarahan** [comment]
This is what I'd recommend a custom compiler package for.  That package would set options or choose a different SDK from the standard.  You'd then set up your *_compiler sections in conda_build_config.yaml to use the custom compiler.

I don't have a good answer for how conda should installl these packages, though.  You'd probably want your custom compiler to use run_exports to add a dependency on some package that has a specific version or build string.  For example, our VS compiler packages add a vc dependency that is shared across all VS compiler packages, but which varies in version.  You'd want something similar, or perhaps a twist on vc that is more restrictive.

**Comment by peterjc123** [comment]
Well, building my own package is the same as the the method I stated before. It's not so convenient, since it's not automatically done, especially when users install the package. And the method you stated may be not so effective under such circumstance, since compiler packages can be easily updated, but OS cannot. It's rather constant. I hope there's a switch to add the system version requirements. (not framework, dependency)

**Comment by msarahan** [comment]
Sorry, but this is not likely to be added.  Neither conda nor conda-build have any notion of what OS they're on, beyond simply "win/mac/linux" or "32/64/powerpc/etc."  Fundamentally, this is because constraints in conda's solver are most easily expressed as dependencies.  Adding more "subdirs" - things like linux-64 - scales very poorly, and doesn't capture the fact that some packages may interoperate - you can use win-xp packages on win-7 for example.

You can achieve what you want with package dependencies, and while I agree that it is a bit indirect, thinking about packages in terms of ranges of compatibility (and what determines those ranges) is more effective.  The SDK's and compiler settings that I mentioned are what determine that range of compatibility on Windows.  Even if you update your compiler package, you can still keep it targeting a specific range of compatibility (e.g. win xp compatibility mode in VS).

This problem is very much like another one we're working through: https://github.com/conda/conda/issues/5360; most recent work at https://github.com/jjhelmus/selectable_pkg_variants_example

**Comment by peterjc123** [comment]
It's not so helpful. But thank you anyway.
