### ISSUE TITLE
Better documentation for run_exports

### ISSUE THREAD

**Issue by asmeurer** [conda/conda-build#2721]
I've read through the [documentation](https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#run-exports) for `run_exports` a few times, but I'm having a hard time understading what exactly it does. 

Can you add an example that clearly specifies what it does to the package (and dependencies, I'm assuming)? 

Also, it has this `pin_compatible`, but doesn't specify what it is. What does it do? Is it required for `run_exports`? What is `'x'`?

**Comment by asmeurer** [comment]
CC @scopatz

**Comment by msarahan** [comment]
It adds an entry to the package that specifies it.  For example, see https://repo.continuum.io/pkgs/main/linux-64/zlib-1.2.11-ha838bed_2.tar.bz2 - extract it and look at ``info/run_exports.yaml``.  In that file:
```
weak: ['zlib >=1.2.11,<1.3.0a0']
```
When conda-build gets its list of dependencies for the build and host environment, it looks in the package cache or downloads as necessary, and looks for these files in each package.  It adds any specs that it finds.  "weak" exports apply only from host to run.  "strong" exports apply from build to host and build to run.

So, for example, a package with:

```
requirements:
  build:
    - {{ compiler('c') }}
    - zlib
```

will not end automatically up with a run dep on zlib, because the zlib export is weak.

```
requirements:
  build:
    - {{ compiler('c') }}
  host:
    - zlib
```

will have an automatic run dep of ``zlib >=1.2.11,<1.3.0a0``.  Also, the compiler may have a strong run_exports entry to force a compiler runtime.  This is how we line up VS runtime stuff.  The vs2015_win-64 package has a strong run_export of vc 14, which forces the correct packages to be present in the run environment, and also in the host env.

``x`` is described in the "pinning expressions" section.  https://conda.io/docs/user-guide/tasks/build-packages/variants.html#pinning-expressions

pin_compatible is documented at https://conda.io/docs/user-guide/tasks/build-packages/variants.html#pinning-at-the-recipe-level

**Comment by asmeurer** [comment]
OK, now there is a new thing that I have never heard of, "host". What is that? 

There is some degree of automatic version pinning that happens here? Or is that only when using one of these jinja functions? 

Can you clarify, what is the difference between

```yaml
build:
  run_exports:
    - libabc

requirements:
  build:
    - libabc
```

and 

```yaml
requirements:
  build:
    - libabc
  run:
    - libabc
```

**Comment by msarahan** [comment]
run_exports only applies to downstream things, not to the immediate recipe.  Look at the zlib example I showed - it is behavior that happens when a package that defines run_exports is used as a build or host dependency.  It does nothing in the immediate recipe where it is defined.  This is actually something I'd like to fix.  It should apply between outputs in a given recipe, but currently does not.  As a result, you sometimes need to include run deps for outputs that you would not include for external recipes that consume the same build dep.

Host is documented at https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#host

The automatic pinning happens primarily only with the jinja functions.  The exception to that is if someone specifies ``pin_run_as_build``, documented at https://conda.io/docs/user-guide/tasks/build-packages/variants.html#pinning-at-the-variant-level

**Comment by speleo3** [comment]
Related: [build vs. host requirements](https://groups.google.com/a/continuum.io/forum/#!topic/conda/_AfnA9lgczA) question on conda mailing list.

**Comment by msarahan** [comment]
Closing.  If there are more questions on this topic, please open a new issue with specific questions on what you're confused about.
