### ISSUE TITLE
outputs section should allow one conda package without name

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#2729]
It appears that in `conda-build` 3 that even if only one `type: conda` package is include (when say a `wheel` is also package) that the `type: conda` package must have a `name`. However it seems this constraint can be relaxed as there will only be one `conda` package in this case.

**Comment by msarahan** [comment]
I think this makes sense, but I also think it's not much to ask that people add simply

```
- name: top-level-package-name
```

instead.  I'd welcome a PR for this, but it would be a while before I can do this myself.  The treatment of top-level stuff that's also output stuff is hairy.  There needs to be more separation between the build phase and the packaging phase.  Merging metadata between those two phases happens for outputs that have the same name as the top-level package name, which is basically what you're asking to happen implicitly here - so you might hit that hairiness.

You may be able to do something hacky with selectors, so that you only have the outputs section when building a wheel:

```
outputs   # [wheel]
  - type: wheel   # [wheel]
```

and a config file:

```
wheel:
  - True
  - False
```

**Comment by jakirkham** [comment]
Yeah, I can imagine how it can be tricky. Certainly not pressing, but a little surprising. Maybe it could be noted in the docs that conda outputs always need a name. If we ever relax it, it shouldn't break anyone that uses a name always, but simply allow this case to work.
