### ISSUE TITLE
Encrypted source archive

### ISSUE THREAD

**Issue by twrightsman** [conda/conda-build#2788]
Is it possible to specify a zip password for a given source URL that points to a password-protected zip archive? Or possibly a way to specify custom extra steps to extract a source file in `meta.yaml`?

**Comment by msarahan** [comment]
Not at present.  This is a very uncommon need.  Because of that, I'm hesitant to hack it into conda-build itself.  What I'd recommend instead is doing your source download and extraction yourself in build.sh.  Make curl a build-time dependency, and then use it for your download:

```
curl -LO your-url
< your unzip command with password >
```

I'd recommend using an env var there for the password, and then passing it into the recipe with a ``build/script_env`` section in meta.yaml, so that you don't hard-code the password into your recipe.
