### ISSUE TITLE
empty host loses imposed deps from build run_exports

### ISSUE THREAD

**Issue by msarahan** [conda/conda-build#2806]
These libraries are expected to be present when compiling, but if there are no other host dependencies, conda-build discards the host section completely and creates no environment for it.  Conda-build needs to resolve all run_exports prior to env creation, and create the host env even when the only deps are those that are imposed by run_exports in the build section (i.e. "strong" run_exports)

**Comment by mingwandroid** [comment]
`pyldd` is designed to deliberately ignore the build prefix and look for libs in the host prefix only (when not merging host and build prefixes), it also explicitly errors when it finds the DSOs but they're only transitive dependencies because all auto-loaded DSOs *must* come from direct run dependencies..

so to say that those tools are 'happy' isn't *really* the case, rather the checks they perform are less comprehensive because they do not have any idea about `conda`/`conda-build` concepts.
