### ISSUE TITLE
Build recipe that is python version dependent but system independent

### ISSUE THREAD

**Issue by frmdstryr** [conda/conda-build#2816]
I'm using conda to cross compile python extensions and libraries for Android and iOS (see https://github.com/codelv/conda-mobile) and create a "distribution" that can be used to build an app. It's been working very well so far. The recipes are built _and_ installed on the host system but only _run_ on the target system. 

I know this is different than a "normal" use case, but as the title states, is it possible to make a recipe independent of the host system `arch` (ex linux, win, osx ...) but dependent on the `python` version (ex 2.7, 3.6, ...)?  

Since the recipes need to be installed on the host os but actually run on a mobile device I'm using `noarch: generic` so a recipe built on linux can also be "installed" on a windows/osx system.  This has worked fine so far with python 2.7, however I'm beginning to add 3.6 libraries and this is causing issues where conda is installing dependencies built for the wrong python version.  

### Actual Behavior

When I build a recipe for 2.7 that depends on another package built for 2.7, it is installing a package built for 3.6 and vice versa... It is using the most recently built package NOT the one built for the given version of python. 

### Expected Behavior

When I build a recipe for 2.7 that depends on another package built for 2.7, it should only install packages built for python 2.7. Likewise when building a recipe for 3.6 it should only install packages built for python 3.6.

From reading other comments/issues the problem seems to be that using `noarch: generic` allows extensions but does not "restrict" to a certain python version and using `noarch: python` does not work because it does not allow extensions. What I'm looking for is a way to combine both (ex `noarch: generic_python`) or something that does not restrict the system but restricts the version of python.  Like what was suggested in https://github.com/conda/conda-build/issues/542#issuecomment-182602416.

Is this possible? Is there a better way to achieve what I'm trying to do?  The recipes build libraries for all supported "architectures" of the target platform so I'm not sure what's the proper way to do this.

Thanks!

**Comment by msarahan** [comment]
I think you're looking for cross-compiling and not really noarch.  Cross-compiling has been a feature developed in conda-build 3.  To achieve it, you need to create your own compiler packages (which can be nothing more than activation scripts).  See this part of the docs: https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html

In particular, you'll need to follow https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html#customizing-the-compilers to create your compiler packages.

After that, it should be straightforward to have conda use a new subdir, say linux-aarch64, instead of linux-64.  The app-running platform really isn't noarch, and it also isn't linux-64.  There's no way around the fact that it is a different subdir, and you have to account for that somehow.  Conda does know about aarch64 already: https://github.com/conda/conda/blob/4d70d98d3ffc857c72142bddbf78d34b9114b267/conda/base/constants.py#L58

but you need to bootstrap your own miniconda for that architecture.  Bootstrapping means building out all of the core dependencies for miniconda.  Mostly this is all python's dependencies.  If you use our recipes from https://github.com/AnacondaRecipes, they should work for your cross compiling right away, after you set up your compiler activation package.  Here's our build list in topological order for miniconda:

```
zlib-feedstock
xz-feedstock
m4-feedstock
libtool-feedstock
perl-feedstock
autoconf-feedstock
automake-feedstock
pkg-config-feedstock
ncurses-feedstock
libedit-feedstock
sqlite-feedstock
tk-feedstock
libffi-feedstock
readline-feedstock
ca-certificates-feedstock
openssl-feedstock
bzip2-feedstock
python-feedstock
python-2.7-feedstock
python-3.5-feedstock
certifi-feedstock
setuptools-feedstock
pretend-feedstock
hypothesis-feedstock
wheel-feedstock
pip-feedstock
setuptools_scm-feedstock
py-feedstock
pytest-feedstock
pytest-runner-feedstock
pycparser-feedstock
cffi-feedstock
yaml-feedstock
cython-feedstock
ruamel_yaml-feedstock
idna-feedstock
pytz-feedstock
pycosat-feedstock
iso8601-feedstock
asn1crypto-feedstock
cryptography-vectors-feedstock
six-feedstock
cryptography-feedstock
pyopenssl-feedstock
pysocks-feedstock
urllib3-feedstock
chardet-feedstock
requests-feedstock
conda-env-feedstock
conda-feedstock
```

**Comment by frmdstryr** [comment]
Thanks for the prompt reply.  

I did see that conda supports cross compiling however I was under the impression that conda will only let you install a package the host system supports. Ex if my system is ubuntu 16.04 with an x86_64 cpu (linux-64), I will not be able to install a linux-aarch64 package, is this true? 

Conda is not available on the target device(s), so a package cant be "installed" directly on the device as it is done on a normal system. 

Instead, the build system (android's gradle or xcode) must take all the pre cross-compiled libraries from a given location on the _host system_ and package them into multiple app(s) each built specifically for a target device's arch.  Ex, one "app" build for android will create 4 output apks, `app-arm64-v8a-debug.apk`, `app-armeabi-v7a-debug.apk`, `app-x86_64-debug.apk`, and `app-x86-debug.apk`.  iOS is slightly different in that "fat" libs are made where all the libs compiled for multiple different arches are combined into one single library.

In all cases though, all of the pre-compiled libraries for each target architecture must be available on the host system to use during the build phase of the app.

**Comment by mingwandroid** [comment]
`conda-build` (and by extension `conda`) is happy with having a `build` env that's `linux-64` and a `host` env that's `linux-aarch64` (for example).

You'd install cross-compilers in the `build` env (using `conda-build 3`'s `` - {{ compiler('c') }}`` for example to install the NDK (probably you'd just make two distinct metapackages for C and C++ both of which depend upon your Android NDK package).

If the package contains tests and you want them to be run then you even arrange for that to happen in a transparent way by using `QEMU` and `binfmt_misc` (and perhaps a `dejagnu` control file).

I did all of this before and while ago and managed to build all of `Miniconda` for an low powered `ARM` device which didn't use `glibc`.

**Comment by frmdstryr** [comment]
I got it to work using build strings for each version.

```yaml
build:
  noarch: generic
  string: py{{CONDA_PY}}
```

Then reference dependencies using

```yaml

requirements:
  build:
    - some-package>=x.x py{{CONDA_PY}}*

```

It always requires a version but it gets the job done.

**Comment by msarahan** [comment]
I'm glad you got it to work, but I think you're doing it the wrong way, and it will be fragile and will make you work harder over time.  I think you'll be overall fine for your use case, though.  We will be working on official aarch64 packages later this year, and that should make life easier.

**Comment by mingwandroid** [comment]
Those official aarch64 packages won't work on iOS (darwin) nor Android (bionic) though?

**Comment by msarahan** [comment]
Darwin probably not, but Android maybe?  You would know better than me.  I would think that Android would be a target platform for our aarch64 stuff.  What runs on @mingwandroid?

**Comment by mingwandroid** [comment]
I am powered mostly by coffee, tree-nuts and turmeric.

Android's weird I'm afraid!

I mean, the crux of the issue is what is `aarch64`? I believe following from tradition, conda's `linux-aarch64` subdir will be the most popular / baseline glibc-based device that's out there, so some raspberry pi 3 thing in terms of compatibility (is there a 64-bit distro for that yet though? I've lost touch, hopefully there is, if not a 64-bit kernel and user-space, then at least a mixed 32-bit kernel with a 64-bit userspace distro we can target).

We certainly *could* look into building a suite of packages for iOS and Android though, maybe with subdir names like `darwin-ios-aarch64` and `linux-android-aarch64`?

**Comment by mingwandroid** [comment]
Or even better, let's adopt the real triplets instead!

**Comment by msarahan** [comment]
Yes, adopting real triplets seems the most sane to me.  We should try to get that on our roadmap.

**Comment by jjhelmus** [comment]
Last time I looked into android the loader did not support RPATH which made things difficult.

**Comment by mingwandroid** [comment]
The question is, what would *most* people want with a set of Android (and iOS) conda packages?

My contention is that they will want to use them to make the next flappy birds rather than doing real work. This means they'll probably want to use static libraries anyway.

**Comment by mingwandroid** [comment]
There are ways of sharing shared libraries between applications on Android. The Qt port for Android does this via something called Ministro. I've not looked at that for years and years and wasn't ever intimately familiar with the details anyway, but it might be of interest for doing real work on Android.

**Comment by kiwi0fruit** [comment]
Is anybody interested in helping with [fixing building conda packages for Android/iOS](https://github.com/codelv/conda-mobile/issues/9#issuecomment-400174899)?

As at the moment **frmdstryr** did great amount of work to make it run on Android but he is not ready to fixing a _working_ solution with interface issues (packages have prefixes, not utilizing channels, etc.).
