### ISSUE TITLE
VideoToolbox not in macOS whitelist

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#2869]
Not sure where to put this yet, but saw the following in `ffmpeg`'s build logs. Is there some way we can get it added to `conda-build`'s whitelist?

```
WARNING (ffmpeg,lib/libpostproc.55.1.100.dylib): Needed DSO /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox not found in any CDT/compiler package, nor the whitelist?!
```

ref: https://api.travis-ci.org/v3/job/374617219/log.txt
ref: https://travis-ci.org/conda-forge/ffmpeg-feedstock/builds/374617218

**Comment by jakirkham** [comment]
There are also a few warnings at the end mentioning that `pyldd disagrees with ldd/otool` and that these should be reported here.

**Comment by jakirkham** [comment]
Along those lines similar warnings about `pyldd` and `ldd` tool disagreements on Linux.

ref: https://circleci.com/gh/conda-forge/ffmpeg-feedstock/129

**Comment by mingwandroid** [comment]
Hey @jakirkham, add it as follows:

```
build:
  missing_dso_whitelist:  # [osx]
    - /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox  # [osx]
```

You then want to be very deliberate about checking for symbol compatibility against the lowest version of macOS you support. One way is to use an old SDK. Currently, new packages for `AD` are allowed to use 110.101, but we're conservative and use `10.9` for nearly everything still (Qt being the notable exception, that needs a `10.11` SDK and to be told to target `10.10`). If you're going with whatever's on some CI system then you need to be deliberate about managing that too (as I'm sure you are only too aware).

The `disagrees with` stuff should just get removed now since `pyldd.py` with its overlinking checks were explicitly designed and developed to deprecate both `conda inspect linkages` and `conda inspect objects`. I propose replacing them with something that just prints:

"WARNING: You should remove conda inspect blah from your recipe"

**Comment by jakirkham** [comment]
Thanks for the feedback Ray. :)

So this is added to the recipe? Can we add it to `conda_build_config.yaml`? Guessing we don't want individual feedstocks choosing this generally. Any thoughts/concerns on whitelisting this at the `conda-build` level?

We are pretty careful about using 10.9. Currently we are forcing the 10.9 SDK on Travis CI (using an image with it) and downloading/using the 10.9 SDK on CircleCI for select builds. Have explored turning the 10.9 SDK into a `conda` package in PR ( https://github.com/conda-forge/staged-recipes/pull/5382 ). Though have mixed feeling about that. Would love your feedback there.

Thanks for the heads up about Qt. We will need to think about how we relax this constraint. ( https://github.com/conda-forge/conda-smithy/issues/769 )

Are you doing any other checks for macOS SDK version in `conda-build`? Are there settings we can/should enable (if we haven't already) to fail on SDK version mismatch?

Yep, remembering a previous conversation we had about this now. Raised issue ( https://github.com/conda-forge/conda-smithy/issues/768 ) to lint `conda inspect` going forward. Sorry for having this conversation again.

**Comment by mingwandroid** [comment]
> Guessing we don't want individual feedstocks choosing this generally.

Mmm. Not sure. I've hummed and hawed over this for a while. Not using system libs is good and explicit is better than implicit, so I believe having the really esoteric ones called out explicitly is better (libresolv is another one that gets linked to every now and then but to me it's a slightly red flag or at least something I don't fully grok - shouldn't we use openssl instead? So I want to easily be able to track all the recipes that need it). I whitelist a load of multimedia framework dylibs for qt but in general I don't want something like zlib pulling these in because that's be just weird and the error will force me to figure out what's going on.

I don't mind the current setup. The hard-coded list in post.py *could* be moved to conda_build_config.yaml but I kind of feel like it's a good list (though you may not want /opt/X11 in it). Any identified in the recipe are added to the list and so entries can use glob2 patterns FWIW.

I think making packages for the macOS sdk is a fine plan. Just set CONDA_BUILD_SYSROOT to point at it (see our cbc.yaml) and override it for qt in a more local CBC.yaml (same thing for macosx_min_depolyment_target and the other one .. on my phone now cannot check proper names).

conda build doesn't check for SDK versions beyond that, no and I don't really think that it should. One thing to note is that the clang compiler activation script falls back to using xcrun to find an SDK if the config var is not set and currently the latest macOS sdk is incompatible with our static linker (ld64) there's nothing I can do about this since Apple have yet to release the source code for the latest version.. maybe lld will be usable soon instead?)

CC @msarahan
