### ISSUE TITLE
Conda has no way to disable building of dependencies found locally

### ISSUE THREAD

**Issue by mithro** [conda/conda-build#2911]
Is there a way to make conda-build **not** use local recipes if a dependency is not found. Currently it does the following;
```
tansell@tansell:~/github/timvideos/conda-hdmi2usb-packages$ ./conda-env.sh build -c mithro arachne-pnr                   
INFO:conda_build.variants:Adding in variants from config.variant                                                         
Missing dependency icestorm, but found recipe directory, so building icestorm first
Cloning into '/usr/local/google/home/tansell/conda/conda-bld/icestorm_1527040072195/work'...
done.
```
However, I can't seem to figure out a way to prevent conda-build from doing this?

**Comment by msarahan** [comment]
If your dependency isn't found and you don't build it, it will error out.  Is that what you want?  Your package definitely will not build without all dependencies being available somehow.

**Comment by mithro** [comment]
Even if the dependency is found locally, I do *not* want it to build anything /except/ the exact package I asked to be built.

**Comment by msarahan** [comment]
The problem is that the exact package you asked to be built *can't* be built, unless all of it's dependencies are satisfied.  Your choices are either an error, or conda-build trying to build dependencies.  Or you can remove dependencies you don't have yet, if your software is modular enough.

**Comment by mithro** [comment]
@msarahan I would like it to error out.

**Comment by mithro** [comment]
@msarahan This would not be a great default behaviour -- but I was hoping there would be a flag which enabled this.

**Comment by msarahan** [comment]
Great.  I don't think there's a way to do that right now.  The code responsible is at https://github.com/conda/conda-build/blob/master/conda_build/build.py#L2267

This code is very old, very brittle, and in need of replacement with a proper graph-traversal approach.  That's discussed in https://github.com/conda/conda-concourse-ci/issues/78, but that's not planned in the next few sprints for us.

PRs would be welcome, either for the graph or just to add a CLI flag that would disable the search for other recipes.  I am swamped with other things and will not get to this any time soon.

If you have time for a PR, you should know that the Config object is a catch-all.  It'll probably be enough to only define a CLI flag in conda_build/cli/main_build.py, and then respond to that flag in build.py where I pointed to above.  All CLI flags are caught by a Config object, so it'll be there.  You'd probably also need to set up a default value, so that the attribute is defined when using conda-build's API.  See https://github.com/conda/conda-build/blob/master/conda_build/config.py#L57

**Comment by mithro** [comment]
It is unlikely I'll have a chance to do a pull request myself any time soon either. My current work around is to copy the recipe into its own directory and build from there.

**Comment by mithro** [comment]
@msarahan I renamed the bug a little to better match the issue. Feel free to rename it further if you think of a better name.
