### ISSUE TITLE
settings for winapi

### ISSUE THREAD

**Issue by looooo** [conda/conda-build#2929]
Previously with the old conda-forge toolchain, I was able to build FreeCAD for windows. Now with new compilers I guess a setting has changed and I get this output:
```
..\src\Main\MainPy.cpp(64): error C2664: 'DWORD GetModuleFileNameW(HMODULE,LPWSTR,DWORD)': cannot convert argument 2 from 'char [260]' to 'LPWSTR'
```
Any ideas how to change to the old settings?

conda-build=3.10.5
conda=4.5.4

**Comment by msarahan** [comment]
There's really no difference between the "old" conda-forge toolchain and the new one.  The new one is nothing more than a wrapper around the old toolchain files.  I don't know what your compiler error is, but I'm pretty sure it isn't due to a toolchain change.

I'd look extremely carefully at which compiler is being used, and make sure it is the one you expect it to be.  Also, if you aren't using the new ``{{ compiler('c') }}`` syntax, then you're really definitely using code in conda-build that has not changed.  It may be that something on appveyor changed.

**Comment by looooo** [comment]
I am using the new `{{ compiler('c') }}` syntax. The problems occurs in this recipe: https://github.com/looooo/staged-recipes/tree/freecad/recipes/freecad

>  It may be that something on appveyor changed.  

no, the problem occurs locally too.

> There's really no difference between the "old" conda-forge toolchain and the new one. The new one is nothing more than a wrapper around the old toolchain files. I don't know what your compiler error is, but I'm pretty sure it isn't due to a toolchain change.

I tried to build with `- toolchain ` instead of `- {{ compiler('cxx`) }} and it fails with the same error. Maybe this is coming from a windows update?

**Comment by looooo** [comment]
I guess I have found the problem. The UNICODE option was set by a cmake-configuration of a dependency.
So not in all related to conda.
