### ISSUE TITLE
Cyclic dependencies disallowed?

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#2960]
In PR ( https://github.com/conda-forge/libssh2-feedstock/pull/12 ), we tried to add `cmake` as a `build` dependency, but it seems `conda-build` disallows this as this would introduce a cyclic dependency. However the point of having `build` and `host` split is to allow things like compilers and build tools to be installed in `build` without running into cyclic dependency issues.

**Comment by mingwandroid** [comment]
The reason for the split between host and build are:

1. Allow cross-compilation.
2. To facilitate run_exports.
3. Allow creation of a package in the face of it needing to depend upon older versions of itself (in build).

Cycles are never allowable and should never be allowable in any situation.

**Comment by jakirkham** [comment]
The issue is we need `cmake` to build `libssh2`, but `cmake` depends on `libssh2`. It would seem that if we installed `cmake` in `build` (not `host`) we could skirt the main problematic issue (conflicts between the installed `libssh2` and the one we are trying to build and install), but that doesn't seem to be the case as `conda-build` blocks us from doing that. Right now we are stuck with this kludgy `cmake-binary` solution, but it would be great not to have to use that.

**Comment by msarahan** [comment]
Kludgy cmake-binary solution works fine for us.  If you want something different, please submit a PR.

**Comment by jakirkham** [comment]
Does that mean that you would be ok with relaxing this cyclic warning for cycles involving `requirements/build` only? It sounds like Ray was saying the opposite. Hence the question.

**Comment by mingwandroid** [comment]
There are technical solutions to this problem. In every case of a cyclic dep that I have seen, the maintainers have provided a 'way-out' (otherwise Linux From Scratch couldn't work!).

So we need a way to hook into these technical solutions from within `conda-build`. My suggestion is to identify some `cycle_breaker` flag in `meta.yaml` that `conda-build` uses to unravel cycles. What it would do is to build a new temporary package of the cycle breaker configured to not use its cyclic downstream via `conda-build` having set an env var that the build scripts can act upon.

PRs very welcome.

**Comment by jakirkham** [comment]
Ok, that's good to hear.

Do you have any reference to share about `cycle_breaker`-style fixes that other package building tools use? Just something to help start the creative process. ;)
