### ISSUE TITLE
conda build fails for Visual Studio 2017 (where it works for Visual Studio 2015)

### ISSUE THREAD

**Issue by 0zeroth** [conda/conda-build#3007]
A working Visual Studio 2017 installation (eg Cython works and automagically finds the compiler) will not work with `conda build` (it will complain it can't find a compiler)

The work-around is to either install Visual Studio 2015 _or_ run `conda build` from inside the Visual Studio command prompt.

**Comment by msarahan** [comment]
conda-build is set up to be compiler-agnostic.  Any compiler "magic" is legacy and no longer actively supported.  All compiler configuration should be done with compiler packages.  An example VS2017 recipe for compiler package is at https://github.com/AnacondaRecipes/aggregate/tree/master/vs2017

You'd then need to specify the compiler as vs2017 in a conda_build_config.yaml file, because the default version is otherwise 2015 for python 3.5+.  Please see https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html and https://github.com/AnacondaRecipes/aggregate/blob/master/conda_build_config.yaml#L21

This is not supported (let alone default) yet because we have not yet begun using VS2017 ourselves.  There have been numerous showstopping bugs with VS2017 and we're waiting for an adequate release.

**Comment by 0zeroth** [comment]
Thanks for the info - I completely missed that section of the docs when trying to wrap my head around the ``{{ compiler('c') }}`` style of recipe!
