### ISSUE TITLE
Option to error if compilers are not used, but compiled objects are found.

### ISSUE THREAD

**Issue by isuruf** [conda/conda-build#3035]
Feature request

**Comment by msarahan** [comment]
I think the reason behind your request is to help figure out which recipes need addition of an explicit compiler requirement.  I think a better approach here is to just not install compilers, or to put dummy error-only "compilers" in your build images to force failure when the proper compiler is not used.

The behavior you propose would break repackaging, but that's why it would be an option.  Probably default to disabled.
