### ISSUE TITLE
conda_build.api.render() does not find local packages

### ISSUE THREAD

**Issue by maddenp** [conda/conda-build#3050]
### Actual Behavior

`conda_build.api.render()` does not find local packages.

### Expected Behavior

`conda_build.api.render()` finds (or at least provides a mechanism to find) local packages.

### Steps to Reproduce

1. Have a local package. In my case:
```
$ conda search --use-local conda-libbacio
Loading channels: done
# Name                  Version           Build  Channel             
conda-libbacio            2.0.2      h9ac9557_0  home/pm/Desktop/fix/miniconda/conda-bld
```

2. Have a `meta.yaml` that requires the local package:
```
$ cat /home/pm/Desktop/recipe/meta.yaml 
package:
  name: foo
  version: 0.0.1

requirements:
  build:
    - {{ compiler('fortran') }}
  host:
    - conda-libbacio
```

3. Have a test program that calls `conda_build.api.render()`:
```
$ cat meta.py
import atexit
import shutil
import tempfile

import conda_build.api

croot = tempfile.mkdtemp()
atexit.register(lambda: shutil.rmtree(croot))
conda_build.api.render("/home/pm/Desktop/recipe", croot=croot, verbose=False, channel_urls=['local'])
```

4. Run test program:
```
$ which python
/home/pm/Desktop/fix/miniconda/bin/python

$ python meta.py
Returning non-final recipe for foo-0.0.1-0; one or more dependencies was unsatisfiable:
Build: None
Host: conda-libbacio
```

I was talking with Mike Sarahan about this in https://groups.google.com/a/continuum.io/forum/#!topic/conda/Bc1LkxPNz4g, and he suggested adding the `channel_urls=['local']` kwarg in the test program above. That was working, and I was working on a fix and possibly a PR per his request in that thread, but something has changed since then and the `channel_urls` kwarg no longer seems effective. A slightly older version seemed fine:
```
$ conda build --version
conda-build 3.12.0

$ conda install --yes conda-build=3.10.9
Solving environment: done

## Package Plan ##

  environment location: /home/pm/Desktop/fix/miniconda

  added / updated specs: 
    - conda-build=3.10.9


The following packages will be DOWNGRADED:

    conda-build:  3.12.0-py36_1 --> 3.10.9-py36_0
    conda-verify: 3.1.0-py36_0  --> 3.0.2-py36_0 

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

$ python meta.py
$

$ conda update --all --yes
Solving environment: done

## Package Plan ##

  environment location: /home/pm/Desktop/fix/miniconda


The following packages will be UPDATED:

    conda-build:  3.10.9-py36_0 --> 3.12.0-py36_1
    conda-verify: 3.0.2-py36_0  --> 3.1.0-py36_0 

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

$ python meta.py
Returning non-final recipe for foo-0.0.1-0; one or more dependencies was unsatisfiable:
Build: None
Host: conda-libbacio
```

In the meantime, I would be grateful to know how I can work around this.

##### `Output of conda info`
```
     active environment : None
       user config file : /home/pm/.condarc
 populated config files : 
          conda version : 4.5.8
    conda-build version : 3.12.0
         python version : 3.6.6.final.0
       base environment : /home/pm/Desktop/fix/miniconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/pm/Desktop/fix/miniconda/pkgs
                          /home/pm/.conda/pkgs
       envs directories : /home/pm/Desktop/fix/miniconda/envs
                          /home/pm/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.8 requests/2.19.1 CPython/3.6.6 Linux/4.15.0-29-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by pmspire** [comment]
Is there any chance someone could take a look at this? Could, at least, the regression that seems to have been introduced between v3.12.0 and v3.10.9 be reversed? I cannot upgrade conda-build due to this bug. Is there maybe a better temporary workaround than the one previously suggested by @msarahan, which no longer works?

**Comment by msarahan** [comment]
I have a local build of zlib, hash is h1de35cc.  That build is not online at all:

```
conda search zlib
Loading channels: done
# Name                  Version           Build  Channel
zlib                     1.2.11      h60db283_0  pkgs/main
zlib                     1.2.11      h60db283_1  pkgs/main
zlib                     1.2.11      hf3cbc9b_2  pkgs/main
```

If I create a recipe using zlib:

```
package:
  name: foo
  version: 0.0.1

requirements:
  host:
    - zlib
```

and render it, it uses the zlib package that is only available locally:

```
conda render test_zlib_render
--------------
Hash contents:
--------------
{}
----------
meta.yaml:
----------
package:
    name: foo
    version: 0.0.1
requirements:
    host:
        - zlib 1.2.11 h1de35cc_2
    run:
        - zlib >=1.2.11,<1.3.0a0
extra:
    copy_test_source_files: true
    final: true
```

The problem is that you are setting croot.  croot replaces where packages and build folders go.  When you make a clean temp folder, and then point conda-build at that for croot, "local" is pointing at a completely empty package collection.  You'd need to do a full ``file:///home/you/miniconda/conda-bld`` as your channel to pick up your central package stash.

**Comment by pmspire** [comment]
Interesting, @msarahan, and thank you. So the change I saw between v3.10.9 and v3.12.0 was probably a bugfix rather than a regression -- sorry for drawing the incorrect conclusion.

I had to (or decided to, anyway) use `croot` because, otherwise, a new build directory was created for every render, leading to a quickly escalating number of apparent partial builds that users would then be notified about and advised to remove with `conda build purge`. It's important to me not to expose my users to unexpected information/advice that makes them think they might have done something wrong/weird, so I wanted to suppress that behavior.

I'll have to see if I can use the facts you've given me here to come up with a solution. I suppose I could check which build directories exist before doing the render and then clean up the extra one added after the render. Concurrency might be an issue. Is there a way to reliably know when interacting with the render API the name of the build directory it creates? Or maybe I can link items into the temporary `croot` directory to fool it.

In any case, it sounds like this is not a bug, so please feel free to close. Of course, if you have any ideas about how I might solve my accumulating build directories problem, I'd be grateful to hear them.

**Comment by pmspire** [comment]
I found it: The `build_folder` property on the `Config` object accessed via `.config` on a `MetaData` object returned from a `conda_build.api.render()` call contains exactly the directory I want to delete after rendering.

As for closing the ticket, I recall now that, in our Google Group exchange, you seemed to indicate that having to pass the argument `channel_urls=['local']` to `render()` might not be desired, so maybe there's still something to be done here. But I'm happily out of the woods. Thanks again for your help.
