### ISSUE TITLE
Segfaults and GUI error messages ignored in win tests

### ISSUE THREAD

**Issue by msarahan** [conda/conda-build#3083]
@ocefpaf reported that appveyor jobs were succeeding where they should not have.  Error output was present, but the tests succeeded anyway.  For example, https://ci.appveyor.com/project/jswhit/netcdf4-python/branch/master/job/m9eqdnjqfbivryf7 He reported in private conversation that this appears to happen when the tests segfault or show a GUI error message that does not change the return code.  I'm not sure there's much we can do about this, but it's important to be aware of it.

**Comment by ocefpaf** [comment]
If you need more data point: 

https://ci.appveyor.com/project/czender/nco/build/1.0.463

And the right "job" from the one above that failed:

https://ci.appveyor.com/project/jswhit/netcdf4-python/build/1.0.1183/job/a8260qqanq412u7b

**Comment by ceball** [comment]
Just wondering if you're sure this is related (a) only to segfaults and gui error messages, (b) only to conda build, and (c) only to appveyor? I ask because I have encountered the exit status of various conda commands not being detected under a range of circumstances. Maybe problems come from a combination of how conda is installed and made available, plus obscurities in windows/cmd? 

Clarity in the conda docs about how to activate and invoke conda would be really helpful. Between different platforms and different versions of conda, I became very confused about how to install and use conda (e.g. on linux where I was using conda most, I became unsure if I should I add conda to my path and `source activate` as in the docs, or if I should source etc/profile.d/conda.sh and then `conda activate`).

Below are some demos that might be relevant to this issue...

## appveyor

Make conda available by adding to path, and exit status is detected correctly (1). Make conda available by calling activate.bat (copying what is done in job linked in original post above), and exit status not detected (2).

(1)
```yaml
environment:
  matrix:
    - PY: "3.6"
      PYTHON: "C:\\Python36-x64"
      CONDA: "C:\\Miniconda36-x64"

install:
  - "call %CONDA%\\Scripts\\activate.bat"
  - "conda info"
  - "conda notexistthing"
  - "conda notexistthing & exit"
  - "ls not going to work"
  - "echo ok"

build: off

test_script:
  - echo ok2
```

execution continues past the bad conda commands:
![screen shot 2018-10-24 at 20 11 01](https://user-images.githubusercontent.com/1929/47455138-fba31480-d7c8-11e8-9ff7-29cb9faa68b4.png)

(2)

```yaml
environment:
  matrix:
    - PY: "3.6"
      PYTHON: "C:\\Python36-x64"
      CONDA: "C:\\Miniconda36-x64"

install:
  - "set PATH=%CONDA%;%CONDA%\\scripts;%PATH%"
  - "conda info"
  - "conda notexistthing"
  - "conda notexistthing & exit"
  - "ls not going to work"
  - "echo ok"

build: off

test_script:
  - echo ok2
```

execution stops at first bad conda command:
![screen shot 2018-10-24 at 20 06 34](https://user-images.githubusercontent.com/1929/47454933-6142d100-d7c8-11e8-9e29-c2813bf571b5.png)

### locally

I personally encountered the problem of conda builds wrongly passing (i.e. passing when they are really failing) locally, when conda build was being called by another program (doit, a python make-like tool). I reduced the problem to using subprocess Popen with shell=True (which is what doit does by default).

Below, shell=True results in the exit status not being detected (1), but shell=False results in the exit status being detected (2)

```python
import subprocess

shell = True

actions = ['ls not going to work',
           'python -c "import sys;sys.exit(1)"',
           'conda badcommand',
           'conda badcommand & exit']

for action in actions:
    print(action)
    try:
        subprocess.check_call(action, shell=shell)
    except:
        print('...nonzero exit detected')
        import traceback
        traceback.print_exc()
    else:
        print('...nonzero exit NOT detected')
    print('-'*5)
```

(1) with shell=True, exit status of bad conda commands is not detected
```
(pddev) >python testexit.py
ls not going to work
'ls' is not recognized as an internal or external command,
operable program or batch file.
...nonzero exit detected
Traceback (most recent call last):
  File "testexit.py", line 21, in <module>
    subprocess.check_call(action, shell=shell)
  File "d:\mc3\envs\pddev\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ls not going to work' returned non-zero exit status 1.
-----
python -c "import sys;sys.exit(1)"
...nonzero exit detected
Traceback (most recent call last):
  File "testexit.py", line 21, in <module>
    subprocess.check_call(action, shell=shell)
  File "d:\mc3\envs\pddev\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python -c "import sys;sys.exit(1)"' returned non-zero exit status 1.
-----
conda badcommand

CommandNotFoundError: No command 'conda badcommand'.

...nonzero exit NOT detected
-----
conda badcommand & exit

CommandNotFoundError: No command 'conda badcommand'.

...nonzero exit detected
Traceback (most recent call last):
  File "testexit.py", line 21, in <module>
    subprocess.check_call(action, shell=shell)
  File "d:\mc3\envs\pddev\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'conda badcommand & exit' returned non-zero exit status 1.
-----
```

(2) with shell=False, exit status of bad conda commands is detected
```
(pddev) >python testexit.py
ls not going to work
...nonzero exit detected
Traceback (most recent call last):
  File "testexit.py", line 21, in <module>
    subprocess.check_call(action, shell=shell)
  File "d:\mc3\envs\pddev\lib\subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "d:\mc3\envs\pddev\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "d:\mc3\envs\pddev\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "d:\mc3\envs\pddev\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
-----
python -c "import sys;sys.exit(1)"
...nonzero exit detected
Traceback (most recent call last):
  File "testexit.py", line 21, in <module>
    subprocess.check_call(action, shell=shell)
  File "d:\mc3\envs\pddev\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python -c "import sys;sys.exit(1)"' returned non-zero exit status 1.
-----
conda badcommand

CommandNotFoundError: No command 'conda badcommand'.

...nonzero exit detected
Traceback (most recent call last):
  File "testexit.py", line 21, in <module>
    subprocess.check_call(action, shell=shell)
  File "d:\mc3\envs\pddev\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'conda badcommand' returned non-zero exit status 1.
-----
conda badcommand & exit

CommandNotFoundError: No command 'conda badcommand'.

...nonzero exit detected
Traceback (most recent call last):
  File "testexit.py", line 21, in <module>
    subprocess.check_call(action, shell=shell)
  File "d:\mc3\envs\pddev\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'conda badcommand & exit' returned non-zero exit status 1.
-----
```

I guess I'm saying it's not clear to me from the documentation how I should activate and then invoke conda on different platforms and under different circumstances. If it's not possible to cover that, at least a description of what "conda" is or might be (batch file? exe? function? executable?) and a note that there are some potential pitfalls would be helpful.
