### ISSUE TITLE
CC and CXX variables are not being set in build env

### ISSUE THREAD

**Issue by marcelotrevisani** [conda/conda-build#3171]
I'm using the ``conda-build 3.15.1`` and trying to build a recipe and I just realized that the ``CC`` and ``CXX`` variables are not being set in the build environment. I also saw something similar in ``conda-forge``.
Please see
https://github.com/conda-forge/staged-recipes/pull/6724/files

The CI:
https://circleci.com/gh/conda-forge/staged-recipes/30699?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by marcelotrevisani** [comment]
When I try to build a recipe locally I saw this error:

```
ERROR: This cross-compiler package contains no program /home/trevisan/miniconda3/conda-bld/autocorrelator_1537960033902/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/x86_64-conda_cos6-linux-gnu-c++
Traceback (most recent call last):
  File "/home/trevisan/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/trevisan/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 424, in main
    execute(sys.argv[1:])
  File "/home/trevisan/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 415, in execute
    verify=args.verify)
  File "/home/trevisan/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 201, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/trevisan/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 2205, in build_tree
    notest=notest,
  File "/home/trevisan/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1445, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir, stats=build_stats)
  File "/home/trevisan/miniconda3/lib/python3.6/site-packages/conda_build/utils.py", line 311, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/home/trevisan/miniconda3/lib/python3.6/site-packages/conda_build/utils.py", line 291, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/home/trevisan/miniconda3/conda-bld/autocorrelator_1537960033902/work/conda_build.sh']' returned non-zero exit status 1.
```

**Comment by marcelotrevisani** [comment]
hum... it seems ``Anaconda`` broke the compilers...

**Comment by mingwandroid** [comment]
I doubt it. Something else if wrong here

**Comment by marcelotrevisani** [comment]
Just changed to the ``conda-forge`` channel and it worked. Do you have a hint here?

**Comment by msarahan** [comment]
You need to look at exactly what packages were used - which compilers, which activation scripts.  The link you posted is to a "toolchain" based build, which is a non-prefixed compiler.  That's a totally different story from ours.  We must have a sysroot other than the system one, because that's how we achieve isolation from the host OS and target specific older platforms.  When you use our compilers, you are "cross-compiling" even when your host OS and arch match your build OS and arch.  In that case, it is a "pseudo cross compiler" because the sysroot is not the system sysroot.

This error is a cmake error.  CMake is not friendly with sysroots.  See 

* https://gitlab.kitware.com/cmake/cmake/issues/17483
* https://stackoverflow.com/questions/36195791/cmake-missing-sysroot-when-cross-compiling
* 

For an example of how to work around cmake, see https://github.com/AnacondaRecipes/libnetcdf-feedstock/tree/master/recipe

This error is not a conda-build error, so I'm closing this issue.  You say that CC and CXX are not being set, but did you echo them to check?  Conda-build does not set these env vars at all.  The compiler activation scripts do.

**Comment by ax3l** [comment]
Hitting a similar problem here in https://github.com/conda-forge/openpmd-api-feedstock/pull/10 https://github.com/conda-forge/openpmd-api-feedstock/pull/11

Can't we just set the `CMAKE_FIND_ROOT_PATH` for the GCC pseudo cross-compiler?
https://cmake.org/cmake/help/v3.0/command/find_library.html

And if yes, where to point it to?

**Comment by mingwandroid** [comment]
I do not think that would work in all circumstances. sysroots need to be handled implicitly by cmake. As such, they are known by the compiler and cmake and cmake knows it does not need to/should not pass flags for this to the compiler.

> And if yes, where to point it to?

Please refer to https://github.com/AnacondaRecipes/libnetcdf-feedstock/blob/master/recipe/cross-linux.cmake

**Comment by mingwandroid** [comment]
I don't know why you'd want something different (and potentially buggier) than just using that though?
