### ISSUE TITLE
requirement for 3.7.* inserted in no-arch package

### ISSUE THREAD

**Issue by cjw296** [conda/conda-build#3222]
### Actual Behavior

Please see this recipe:

https://github.com/Simplistix/picky-conda/blob/ca41d224da571d2218aca990ea0b385596696cab/conda.recipe/meta.yaml#L18-L24

When I built version 2.0.2 of this package back in may, I got a (correct) requirement of "any python":
https://anaconda.org/simplistix/picky-conda/files/modal/info/5ae9b809f7d77b12100be33c

When I built 2.0.3 today, the same recipe resulted in a version requirement of 3.7.* being inserted:
https://anaconda.org/simplistix/picky-conda/files/modal/info/5bc718361294c61344f3b2d3

### Expected Behavior

Any version of python to be required, not specifically 3.7.*

### Steps to Reproduce

See above

##### `Output of conda info`

See the job log here: https://travis-ci.org/Simplistix/picky-conda/jobs/442622712

Workaround here: https://github.com/Simplistix/picky-conda/commit/c6399b69cec27e191b4d3c19315721b5325d8ecd

**Comment by msarahan** [comment]
I looked at your job log, but didn't see any output about the actual build.  Can you please point me to specific lines from the build log?

I can't reproduce this problem locally, either, unfortunately.  Something definitely went wrong, but I need more info to be able to troubleshoot it.

**Comment by bilderbuchi** [comment]
One hint: Check if the reason is the pyyaml package version being picked during the build.

Yesterday, I found a similar problem with a package of mine being dependent on any numpy. Earlier versions built fine with any numpy, new version suddenly has `numpy=1.11.*` for no obvious reasons. I also have pandas as a dependency. Turns out that the specific pandas version that got picked during `python setup.py bdist_conda` has a `numpy=1.11.*` dependency, although pandas versions with more relaxed numpy specification are available.

I "fixed"/worked around this by bumping my explicit numpy dependency to `numpy>1.11`, now another pandas version gets picked up, and incidentally my package's build string went back to a more generic(?) `py36_0` instead of `py36<hash>_0`.
