### ISSUE TITLE
TypeError: string indices must be integers for conda skeleton pypi 

### ISSUE THREAD

**Issue by talhajunaidd** [conda/conda-build#3246]
I'm trying to create conda package for [django-oauth-toolkit](https://pypi.org/project/django-oauth-toolkit/) 
### Actual Behavior

TypeError: string indices must be integers

### Expected Behavior

It should generate `meta.yml`

### Steps to Reproduce

`conda skeleton pypi django-oauth-toolkit`

##### `Output of conda info`

```
Using 1.2.0
Use --version to specify a different version.
Using url https://github.com/jazzband/django-oauth-toolkit/tarball/master (0 B) for django-oauth-toolkit.

Leaving build/test directories:
  Work:
 C:\ProgramData\Miniconda3\conda-bld\skeleton_1541398102724\work
  Test:
 C:\ProgramData\Miniconda3\conda-bld\skeleton_1541398102724\test_tmp
Leaving build/test environments:
  Test:
source activate  C:\ProgramData\Miniconda3\conda-bld\skeleton_1541398102724\_test_env
  Build:
source activate  C:\ProgramData\Miniconda3\conda-bld\skeleton_1541398102724\_build_env


Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\Scripts\conda-skeleton-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda_build\cli\main_skeleton.py", line 65, in main
    return execute(sys.argv[1:])
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda_build\cli\main_skeleton.py", line 61, in execute
    version=args.version, config=config)
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda_build\api.py", line 282, in skeletonize
    recursive=recursive, config=config, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda_build\skeletons\pypi.py", line 278, in skeletonize
    noprompt, manual_url)
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda_build\skeletons\pypi.py", line 576, in get_download_data
    if url['digests']['sha256']:
TypeError: string indices must be integers
```

**Comment by kyleabeauchamp** [comment]
I also hit this bug for tensorflow-estimator.

**Comment by timsnyder** [comment]
At a minimum, it seems like the pypi skeleton needs to giveup with a better message when the package doesn't contain an sdist for the given version. 

Or, perhaps we can teach it about wheels.  Seems like the wheel for `mitmproxy` contains the dependency information in the `dist_info/METADATA` and the entrypoints in `dist_info/entry_points.txt`.  That's what `skeletons.pypi.get_pkginfo()` claims it must get from the package itself.   We should be able to use the whl URL as the source because pip will install it just fine.

I hit this after hacking past an equally obtuse error when trying to skeletonize `mitmproxy`

**Comment by Jegp** [comment]
This also seems to happen for me on `v3.21.4` for torch. To reproduce: `conda skeleton pypi torch`
