### ISSUE TITLE
Indexing packages when using S3 to host a channel

### ISSUE THREAD

**Issue by jrsmith3** [conda/conda-build#3259]
I am hosting my own private conda channel on S3, but I don't understand how to avoid mirroring all the packages on my local hard drive. The source of the problem is the `repodata.json`, `channeldata.json`, etc. files.

If I build a single package and copy just the `.tar.bz2` file to S3, `conda-install` does not see it in the channel. In order for `conda-build` to see the package, I have to copy the package and all of the `repodata.json`, etc. metadata files created by `conda-build` to S3.

My conundrum is: these JSON metadata files do not appear to be updated properly unless all of the packages I've ever built appear in my local package directory. I now have more than 4GB of conda packages on my local hard drive so that I get the correct metadata in these JSON files.

Is there a way to continue building conda packages with my local machine while avoiding mirroring my private S3 conda channel on my local hard drive? For what its worth, I realize that `conda-index` will build the JSON files, but it doesn't seem to work when you attempt to index a location on S3.

If this question isn't formatted correctly or belongs in the bugtracker of another repo, I apologize in advance and I will update/move it. FWIW, I also posted [this question](https://stackoverflow.com/q/53269465/1533474) on StackOverflow.

**Comment by msarahan** [comment]
I don't think there's a way to do that right now.  If you wanted to change conda-index to support s3/remote package sources, we'd welcome a PR.  Here's the thing: in order to build the index, you'll need to download the remote package files anyway to get the metadata files, or you'll at least have to have a scheme for extracting and putting the metadata files in a place on s3 that conda-build can get to.  Conda-build needs the metadata files to build the index.

Without a central index, conda would be intolerably slow.

**Comment by jrsmith3** [comment]
Thanks for the response. I have some follow-up questions:

1. Is there any documentation of the structure of the metadata files, locations, things that `conda-index` updates, etc? Or would I just have to read the code?
2. Where would someone open a PR to add this feature to `conda-index`? In this repo, or in the main `conda` repo?

Thanks.

**Comment by msarahan** [comment]
In this repo.  conda-index is part of conda-build.  See conda_build/index.py

**Comment by jrsmith3** [comment]
I'm re-upping my question above: is there a spec and/or description for the metadata files that appear in the build directory? Here are all the ones I see:

* `about.json`
* `index.html`
* `.index.json`
* `.paths.json`
* `.recipe.json`
* `repodata2.json`
* `repodata.json`
* `channeldata.json`
* `index.html`
* `repodata.json.bz2`
* `rss.xml`

I don't understand the need for both `repodata.json` and `repodata.json.bz2`. I also don't understand why there are both `repodata.json` and `repodata2.json`. Finally, I don't see documentation for the structure of `repodata.json`. I can sort of see how to construct `repodata.json` from the `info/index.json` files within the packages, but a more explicit document would be helpful.

> Without a central index, conda would be intolerably slow.

Sounds right, but if I'm hosting on S3, maybe I can construct the index using EMR. Its a big hammer, but it works well with S3 if I understand correctly.

Thanks for your help.

**Comment by nehaljwani** [comment]
Not-so-long ago, I had attempted creation of conda channels over S3. I tried indexing by mounting the bucket on my local disk so that cnoda build can see a directory layout similar to a posix file system and then ran conda index on it, which ran fine and everything. The only trouble was, when I added a new package or removed an existing one, conda index would index everything again! I think it was likely because the {a|m|c}time of the already indexed tarballs wasn't what CB would expect, on the re-run.

@jrsmith3 If you are able to do this with EMR, could you please write a blog post about it, or share your experience on this GH issue? It would be immensely helpful!

**Comment by jrsmith3** [comment]
I'm going to close this issue because I feel like its been resolved.

**Comment by darrenleeweber** [comment]
This could be related to https://github.com/conda/conda/issues/7328

**Comment by joeyfezster** [comment]
Hi there.
I'm considering hosting my own python repo on s3 and setting it up as a conda channel.

@jrsmith3 - is there any info you can share on the issue you experienced, and what issues one might find now?
Thanks!!

**Comment by jrsmith3** [comment]
@joeyfezster unfortunately I didn't really do any more work on this issue after posting it. Good luck!
