### ISSUE TITLE
bad character '=' in build string "pl>=523he37515_5"

### ISSUE THREAD

**Issue by epruesse** [conda/conda-build#3276]
### Actual Behavior

Recipe:
https://github.com/bioconda/bioconda-recipes/blob/e4d5d1b0d005dd355664af9d3fb461647186918d/recipes/arb-bio/meta.yaml

Build log:
https://circleci.com/gh/bioconda/bioconda-recipes/35311?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Error:
```
TEST START: /opt/conda/conda-bld/linux-64/arb-bio-6.0.6-pl526he378515_5.tar.bz2

Error: bad character '=' in build/string: pl>=523he378515_5
```

### Expected Behavior

I believe this is an issue related to mixing `pin_compatible` with `outputs` and version constraints on the libraries used. In this case, I need `perl >=5.23`, and `perl 5.26` is chosen. I also need the run time perl to have the same version (or else the binary extension compiled won't work), so I have a `pin_compatible` on that.

One ugliness I've noted is that `pin_compatible` raises, unless I add perl to the build requirement list for every output, even if that one doesn't need perl at all. 

Another one is that `perl` should really export a version requirement on the compiler. If you try to build binary modules using gcc 4.8 and a perl binary compiled with gcc >=4.9, you get `-fstack-protector-strong` flags in the generated Makefile, which gcc 4.8 will not accept. 

Another one is that I apparently have to repeat my run time dependencies over and over. It would be neat if the top level run requirements were copied into all outputs. Or some similar, well documented behavior.

Another one is that YAML standard behavior is broken in CB3 - the outputs section is parsed individually, so using YAML anchors to reduce repetition doesn't work.

**Comment by msarahan** [comment]
We need to document this.  You can't put version constraints on the key language packages: python, perl, lua, and R.  If you need to restrict the version, you can do so by skipping with selectors:

```
build:
  skip: True  # [perl < 5.23]
```

Please keep one topic per issue.

> Another one is that perl should really export a version requirement on the compiler. If you try to build binary modules using gcc 4.8 and a perl binary compiled with gcc >=4.9, you get -fstack-protector-strong flags in the generated Makefile, which gcc 4.8 will not accept.

We advise use of our compiler packages, which are gcc 7.3 and above.  We offer no support for using anyone else's compilers - you're going to need to find community support for that, or figure it out for yourself.

> Another one is that I apparently have to repeat my run time dependencies over and over. It would be neat if the top level run requirements were copied into all outputs. Or some similar, well documented behavior.

Explicit is better than implicit.  Sorry it's cumbersome.  You can make packages that depend on other packages within your recipe (pin_subpackage) and that's often helpful for reducing deps (you can leave indirect deps off the list).

Early versions of CB3 did copy top-level deps in, and it was ultimately very troublesome.

> Another one is that YAML standard behavior is broken in CB3 - the outputs section is parsed individually, so using YAML anchors to reduce repetition doesn't work.

We need to understand what is in the YAML both before and after parsing, so that we understand what variables got used.  That's very hairy and fragile, especially when it comes to outputs.  Losing standard YAML behavior is regrettable, but the features based on knowing what variables get used are more core to CB3's capabilities and can't be sacrificed.  If you'd like to contribute towards restoring the YAML functionality while maintaining CB's current capabilities, we'd welcome any PRs you come up with.

**Comment by msarahan** [comment]
PS: while you can't use YAML anchors, you should be able to use jinja2 variables to reduce duplication.  Do note, however, that conda-build does not support template inheritance, again because of that used-variable stuff - it would have to assemble all the template parts before doing any further rendering/insertion of variables, and last time I looked, jinja2 didn't have those separated into 2 phases.

**Comment by epruesse** [comment]
Thanks for the quick answer Mike!

> We need to document this. You can't put version constraints on the key language packages: python, perl, lua, and R. If you need to restrict the version, you can do so by skipping with selectors:
> 
> ```
> build:
>   skip: True  # [perl < 5.23]
> ```

Does that apply to 

```
requirements:
  run:
    - python >3
```

as well? We've been doing that a lot at Bioconda, and so far it's worked fine. I thought the skip approach wasn't needed in CB3 anymore?

Any chance that this might be fixable? Specifying constraints on interpreters seems to be something pretty common (in particular with Python, but also with R and Perl). 
  
> Please keep one topic per issue.

Sorry, I think my frustration was starting to show about there. The design choice to extend YAML with line based selectors and Jinja2 templating and then iterative templating created something very difficult to follow.

**Comment by epruesse** [comment]
Now I'm getting an error on the skip line - can't compare string to int in the selector.
