### ISSUE TITLE
Run environment is cleared when multiple outputs are present

### ISSUE THREAD

**Issue by chrisburr** [conda/conda-build#3337]
The issue appears to be similar to #3310, however the PR that fixed that issue doesn't resolve this.

### Actual Behavior

When building the `5.x` branch of conda-forge's clangdev feedstock, the build fails with `conda-build >= 3.17.0` as the `$PREFIX` directory is emptied. This affects https://github.com/conda-forge/clangdev-feedstock/pull/44.

From my quick attempt at fixing this, the build dependencies (`m.ms_depends('build')`) appear to be "forgotten" when [this line](https://github.com/conda/conda-build/blob/c96c469a886d23200cde6d1e46a537c8d363c4d3/conda_build/build.py#L1409) is executed.

### Expected Behavior

Configure stage of the build is sucessful, as is the case for `conda-build <= 3.16.3`.

### Steps to Reproduce

```
git clone https://github.com/conda-forge/clangdev-feedstock.git -b 5.x
cd clangdev-feedstock
conda install conda-build=3.17.6
conda build -c conda-forge/label/gcc7 recipe/ --variants '{clang_variant: cling}'
```

This works if `3.17.6` is replaced with `3.16.3` and still fails if `3.17.0` is used.

**Comment by msarahan** [comment]
I'm pretty sure this is the same as https://github.com/conda/conda-build/issues/3277#issuecomment-442979390

Because the MetaData object model in conda-build doesn't separate top-level from outputs in meaningful ways (there's just MetaData objects for both), there's a lot of annoying bugs/edge cases when the top-level package name is the same as an output name.  It's simplest to just avoid these by naming the top-level package name any arbitrary name, and keeping the outputs as the name you really want.

@bergtholdt has a PR to raise an error when the names are the same, https://github.com/conda/conda-build/pull/3314.  I agree with that PR, but I suspect that it will break enough things that it should be handled carefully.

While this is probably a bug, I don't think we're going to fix it unless changing the top-level package name just doesn't work.  A longer-term fix of addressing the data model issue would be time better spent, but that's unfortunately more than we have time for right now.  Community contributions would be most welcome and appreciated.

**Comment by chrisburr** [comment]
Thanks for the quick reply! You're correct, this is the same as https://github.com/conda/conda-build/issues/3277#issuecomment-442979390 and renaming the top-level package avoids the bug.

If raising an error in #3314 is risky perhaps a warning could be issued instead? It could then be promoted to an error once you're confident it's safe to do so.
