### ISSUE TITLE
specify minimum build number for requirement

### ISSUE THREAD

**Issue by epruesse** [conda/conda-build#3381]
Is there a way to specify a minimum build number in the `requirements: run` section? I understand that I can give a specific build string, but is it possible to require `package xyz >1.2.3__5` where `5` is the minimum build number?

To describe the specific situation where I need this:

- package `A` run requires package `B >=6.0.6`
- package `B 6.0.6 build 4` requires `glib` but really needs 2.56 (was linked against it)
- package `B 6.0.6 build 5+` requires `glib >=2.56,<3`

The problem is that a lot of other packages are pinned to `glib 2.53`, so `conda` likes to pick `build 4` because `build 5` requires lesser versions of a lot of other packages. 

- Re-labeling the broken build of package `B` is not an option as it's hard-pinned (via `conda export`) by a lot of clients, so that would cause significant breakage. 
- Pinning to the specific build_string of `B` doesn't seem like a good option either, as it limits future upgrades.

**Comment by msarahan** [comment]
No, this is not really supported other than exact build strings.  The huge problem with this approach is that build numbers carry meaning only within the context of one channel.

A better approach is hotfixing your repodata so that you make that old package less desirable somehow.  If this is for conda-forge, you'd do that at https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/tree/master/recipe.  Keep the solver's priority order in mind: https://github.com/conda/conda/blob/master/conda/resolve.py#L1064-L1122

**Comment by msarahan** [comment]
One other thing: You can move undesirable packages to a different channel, such that people who have used conda export can still ultimately obtain them, but they're not generally available.  This is probably the easiest solution, but would require that your end users add a channel.

**Comment by epruesse** [comment]
So with `conda install` I can use `B[version=>=6.0.6,build_number=>=5]` - does that work in the `meta.yaml`?

**Comment by epruesse** [comment]
The `patch_instructions.json` thing is interesting. Are there docs as to how that works? This is for Bioconda, but we could try and implement something like this.

**Comment by epruesse** [comment]
Question on the side: Why does the resolver ever install anything other than the most recent build number of a package? Usually (other package managers at least), a revised build implies that the previous build was broken in some way, and should not be used any more.

**Comment by msarahan** [comment]
Anything in the patch_instructions.json file will clobber repodata.  Bioconda is one of the channels that gets the cloudflare mirror treatment, so it can also be set up this way.  All we need from you is a place where you'll publish the most recent patch instructions (like that conda-forge package) and we can set up the rest.

Note that the patch_instructions.json file reflects only the repodata at the time it was run.  For that reason, you may want some kind of automated nightly generator for the package containing the patch instructions, so that it reflects more current repodata, rather than just whenever the patch generator was last altered.

> Question on the side: Why does the resolver ever install anything other than the most recent build number of a package?

See the conda optimization conditions I linked to above.  conda-metachannel has an option to limit repodata results to solely the latest build number.  It's something nice to try, but by no means are you guaranteed the correct answer all the time by taking this approach, especially when multiple packages are specified (the latest build of one may not be compatible with the latest of another.)  https://medium.com/@marius.v.niekerk/conda-metachannel-f962241c9437
