### ISSUE TITLE
Conda-debug fails with local requirements

### ISSUE THREAD

**Issue by teake** [conda/conda-build#3433]
### Actual Behavior

Whenever a recipe has a build or host requirement on a locally build package, `conda-debug` fails with the error message

```
conda_build.exceptions.DependencyNeedsBuildingError: 
    Unsatisfiable dependencies for platform [...]: {'<name of dependency>'}
```

### Expected Behavior

Since `conda-build` works perfectly fine in these case, I expected `conda-debug` to also work.

### Steps to Reproduce

In `test_package_1/meta.yaml`:
```
package:
  name: test_package_1
  version: 1.0
```
In `test_package_2/meta.yaml`:
```
package:
  name: test_package_2
  version: 1.0

requirements:
  build:
    - test_package_1
```
Then do:
```
$ conda debug test_package_2
```
This fails the with error given above. 

Note however that when the local build directory is added to the channel list with `conda config`, it does work. Specifying the local build directory as a command line argument (either with `-c local` or `-c <conda_path>/conda-bld` does not work.

##### `Output of conda info`

```
     active environment : None
            shell level : 0
       user config file : ~/.condarc
 populated config files : ~/.condarc
          conda version : 4.6.7
    conda-build version : 3.17.8
         python version : 3.7.1.final.0
       base environment : ~/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : ~/miniconda3/pkgs
                          ~/.conda/pkgs
       envs directories : ~/miniconda3/envs
                          ~/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.7 requests/2.19.1 CPython/3.7.1 Darwin/18.2.0 OSX/10.14.3
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```
where I've unexpanded the home directory.

**Comment by zhaojack** [comment]
I've ran into this exact same issue, and I think I've identified why it's happening in the code.

In [cli/main_debug.py](https://github.com/conda/conda-build/blob/master/conda_build/cli/main_debug.py#L59), the `execute` function will invoke `render_execute` only if the given target is a tarball as opposed to a flat recipe folder. If it's a flat recipe folder, it will take the raw arguments from the argument parser and pass it straight to `api.debug` via `**kwargs`.

[api.debug](https://github.com/conda/conda-build/blob/master/conda_build/api.py#L398) in turn attempts to process the args (passed as `**kwargs` into the function) via `default_config = get_or_merge_config(config, **kwargs)`. However, this is not correct because not all configurations normally translate from the argument namespace to the config object with the same keyed name. `channels` in particular [typically seem to go through a process](https://github.com/conda/conda-build/blob/master/conda_build/cli/main_render.py#L185) where they are validated/further processed, and results in a config key called `channel_urls`. So when `**kwargs` entry `channels` is used directly instead of the expected `channel_urls`, it simply gets lost in the process.

I'd like to +1 on a fix.

**Comment by nehaljwani** [comment]
In addition to this, `local` will be different for `conda-debug`, since it changes the `croot` from 
```
/Users/nwani/m3/conda-bld
```
to:
```
/Users/nwani/m3/conda-bld/debug_1554873697539
```
