### ISSUE TITLE
Pinning version to exact value

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#372]
When trying to fix the version of a dependency, say `numpy` in `meta.yml`, I receive the following error. I would hope that we could pin versions here if necessary or am I just doing something wrong. Any thoughts?

    Error: bad character '==' in package version dependency 'numpy'
    Perhaps you meant 'numpy==1.9.0'

**Comment by asmeurer** [comment]
Spell it like `numpy ==1.9.0` with that exact spacing.

**Comment by jakirkham** [comment]
Yeah, sorry, this is still not working for me. Here, I tried one with gcc. I admit I could be doing something wrong, but I did add the space and tried `4.8` and `4.8.0` and got basically the same error as seen below.

    Fetching package metadata: ......
    Error: No packages found in current osx-64 channels matching: gcc ==4.8.0

**Comment by asmeurer** [comment]
Do you have a build of  gcc 4.8.0? The ones in the Continuum repos are 4.8.2 and 4.8.4.

If you just want 4.8.X, use `gcc 4.8.*`. See http://conda.pydata.org/docs/spec.html.

**Comment by jakirkham** [comment]
Sorry, the 4.8.0 was a red herring. Yes, anything in the 4.8 series should be fine. Probably more recent is better. I think I missed the pattern matching thanks for pointing that out.

So, for the record, I tried `gcc ==4.8.2` and `gcc >=4.8` both worked fine. However, when I tried `gcc ==4.8` or `gcc ==4.8.*` or `gcc ==4.8*` (some parts of the doc said this) it failed to find a match.

**Comment by asmeurer** [comment]
`==4.8*` should not be used anywhere. Does it say that somewhere in the docs?

`==` is exact matching (unlike `=` at the command line, which adds the `*` to the end of the version automatically). `==4.8` failed because there is no build of exactly gcc 4.8. `==4.8.*` failed because using a relational with a version with a `*` doesn't make sense. It should probably be checked for in conda build and errored immediately. If you want to pattern match with the `*`, don't use any relational operator (like `gcc 4.8.*`).

**Comment by jakirkham** [comment]
Oh no, sorry, I meant whether the dot was there or not (e.g. 4.8.* vs 4.8*). I see. Sorry I was confused. This all makes sense now. Thank you for clarifying.

**Comment by asmeurer** [comment]
The dot is recommended as otherwise it might match a theoretical 4.80 (unlikely in this case, but a good practice to use in general).
