### ISSUE TITLE
RECIPE_PATH can be a meta.yaml

### ISSUE THREAD

**Issue by scopatz** [conda/conda-build#3746]
### Actual Behavior

When running `conda build /path/to/meta.yaml` the package builds correctly

### Expected Behavior

`RECIPE_PATH` is suppossed to be a dircetory, so passing in a file should fail.

##### `Output of conda info`

```

```

CC @dillonroach

**Comment by marcelotrevisani** [comment]
According to the documentation, it should be a directory, indeed
```
positional arguments:
       RECIPE_PATH
              Path  to  recipe  directory. Pass 'purge' here to clean the work
              and test intermediates.
```

However, I don't see this behavior as a problem. or is it? 
I am not against to raise an error when the ``RECIPE_PATH`` receives a filepath.
I think we have two options here, we might update the docs to also cover this possibility or to raise an error when a file is passed, that should be easy to implement

cc: @msarahan @jjhelmus

**Comment by scopatz** [comment]
Yeah, maybe this is just a docs error, but it was unexpected

**Comment by jjhelmus** [comment]
[Theses lines](https://github.com/conda/conda-build/blob/master/conda_build/utils.py#L1203-L1204) in utils.py look to be responsible for `meta.yaml` being a valid argument to RECIPE_PATH.  This seems to case of the [robustness principle](https://en.wikipedia.org/wiki/Robustness_principle), "be liberal in what you accept from others".  conda build will accept a meta.yaml file as a recipe path because users tend to pass those in and it is not difficult to determine the intention.  That said I'm split as to if this should be documented as such.  Although passing a path to a meta.yaml file is allow it is not the recommended use.

**Comment by dillonroach** [comment]
It might be valuable then to just add a warning? Say.. leave the handling and docs the same, but add a warning toss that says something like 'you have specified a meta.yaml instead of a directory, re-assigning the containing directory as the target'

That way the edge cases are handled without a hard-stop error, but there's at least feedback to a newer user that the line they called isn't the ideal.. nor is it actually what's being executed under the hood

**Comment by marcelotrevisani** [comment]
I think a warning as @dillonroach mentioned is a good idea indeed.
