### ISSUE TITLE
Anaconda/conda upgraded to Python3.8 and now is not working

### ISSUE THREAD

**Issue by Trizali** [conda/conda-build#3787]
Hello,

I had Anaconda linked to python3.5, but after the pip upgrade (with conda) the version of Anaconda was also upgraded to python3.8. I need to go back to the python3.5, because I have lots of libraries already installed and configured on python3.5
Conda was also updated and it was not working, but I found how to have miniconda3 working in order to test some commands.

I don't know what to do in order to recover Anaconda linked to python3.5.

Any suggestion will be more than welcome. I'm desperate :-(

Regards,

**Comment by marcelotrevisani** [comment]
Hi @Trizali ,

You can force ``conda`` to install the python which you need. I don't think this question is related to ``conda-build`` but it is to ``conda``.

You can do something similar to:
```
conda install python=3.5 --name NAME_OF_YOUR_ENV_HERE
```

However, I highly recommend you to upgrade your Python version, especially because ``conda-forge`` and some packages are not being packaged for Python 3.5 anymore.

Did it help? May I close this?
