### ISSUE TITLE
Allow Blake2 hash in conda build meta.yaml?

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [conda/conda-build#3828]
Working on a build recipe that needs to download a tarball from PyPi (the maintainer is not putting releases on gitHub, or anywhere else I can find :-( ), I noticed that PyPi is providing three hashes:

MD5
SHA256
BLAKE2-256

But they are using the BLAKE2 hash to generate the download url.

So to make a recipe, I need the BLAKE2 hash anyway -- so it would be nice if conda-build could use the BLAKE2 hash to verify the download, rather than my having to use both the BLAKE2 and SHA hashes.

It looks like it's in hashlib, at least for py3.6 and above and py2.7 on my machine (which is from conda on a Mac)

So could be easily done.

**Comment by marcelotrevisani** [comment]
We can add the ``blake2``, however, it is necessary just one of the hashes to verify the package
just ``sha256`` should be enough

**Comment by ChrisBarker-NOAA** [comment]
I know that -- but PyPi is using the Blake2 hash to generate its download urls -- so I need the Blake2 hash anyway, so I'd like to use it to verify as well, so I don't need to use both.

**Comment by ChrisBarker-NOAA** [comment]
Sorry for the noise -- turns out PyPi does provide an easier download url -- I was jsut too lame to find it.

But it looks like BLAKE2 is a pretty nifty hash, so maybe support it anyway?

**Comment by marcelotrevisani** [comment]
Sure, it is possible to add. We are open to contributions, I may take a look on that. But if you want to give a try that would be nice :)

**Comment by marcelotrevisani** [comment]
Can you give an example of a package which is using ``blake2`` on ``pypi``?
I tried with ``pytest`` and they are providing just ``md5`` and ``sha256``

**Comment by marcelotrevisani** [comment]
I just saw that this modification would be better to do it in ``conda`` instead in ``conda-build``. Because ``conda-build`` is using the function ``hashsum_file`` which is defined in ``conda.utils``
Actually, the modification on ``conda-build`` to support ``blake2`` for python version 3.6+ will be simple just if we want backward compatibility that would be necessary to put more effort on it.
As (I think) ``conda`` will drop the support for Python 3.6 in January, I think that is not a problem.

IHMO, we may implement it just for Python 3.6+

cc @msarahan
