### ISSUE TITLE
conda pipbuild fails to fetch metadata for some packages

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#390]
It appears that `conda pipbuild` fails when fetching metadata for some packages. For instance, here is an example with `six` below. Note after attempting to fetch metadata, it simply drops back to prompt.

    $ conda pipbuild six
    Package search: {'_pypi_ordering': 20, 'version': '1.9.0', 'name': 'six', 'summary': 'Python 2 and 3 compatibility utilities'}
    Fetching package metadata: ......
    $

**Comment by jakirkham** [comment]
FWIW, this still fails in 1.13.0.

**Comment by hargup** [comment]
It is likely that this behaviour is because the binary for package `six` already exists, for such cases `pipbuild` exists without any message, see https://github.com/conda/conda-build/issues/435.
You can verify that by printing a message after this line
https://github.com/conda/conda-build/blob/master/conda_build/main_pipbuild.py#L297

**Comment by jakirkham** [comment]
Interesting, you may very well be right. If that's true, then I see the following problems.

1. There is no error message provided.
2. This disallows building a newer version of a package that is already present.

**Comment by jakirkham** [comment]
@hargup FWIW, I ran into this problem with another package today. After systematically purging my system, I finally succeeded when I removed the existing package. So, I believe you are correct.
