### ISSUE TITLE
Downstream tests error rather than skip and warn when environment is unsatisfied 

### ISSUE THREAD

**Issue by jjhelmus** [conda/conda-build#3908]
According to the [documentation](https://conda.io/projects/conda-build/en/latest/resources/define-metadata.html#downstream-tests) when the newly built packages causes an unsatisfied dependency in a downstream test, those tests are skipped and a warning is issued.  

This description does appear to be correct, rather than the tests being skipped and an warning issue, unsatisfied environments caused an error in the case of conda-forge/binutils-feedstock#23.

**Comment by isuruf** [comment]
This is due to the `RuntimeError` being raised in https://github.com/conda/conda-build/blob/610630602066c049d87045c9b7c89b1a6c2e1a6d/conda_build/exceptions.py#L61-L78
not getting caught at https://github.com/conda/conda-build/blob/ba6cf7ab75de9f7961e1ce85c090baf52ce46cbc/conda_build/build.py#L2951

Any ideas how to fix this?
