### ISSUE TITLE
Errors with render and recipes with multiple outputs

### ISSUE THREAD

**Issue by bnemanich** [conda/conda-build#4228]
### Actual Behavior

Calling `conda_build.render` on recipes with multiple outputs does not always generate the correct build requirements. For example, if I call `conda_build.render` on this recipe: https://github.com/open-ce/xgboost-feedstock/blob/main/recipe/meta.yaml , the generated metadata doesn't not include `cmake`. This means that passing the metadata to `conda_build.build` fails.

### Expected Behavior

The generated metadata should include all of the build requirements listed in the recipe.

### Steps to Reproduce

```
git clone https://github.com/open-ce/xgboost-feedstock.git
```

#### From a python script

```python
import conda_build

meta_data = conda_build.render("xgboost-feedstock/recipe")
conda_build.build(meta_data)
```

### `conda info`

<details>
<summary><code>conda info</code></summary>

```
 active environment : base
    active env location : /tmp/nemanich/miniconda3
            shell level : 1
          conda version : 4.10.1
    conda-build version : 3.21.4
         python version : 3.7.6.final.0
       virtual packages : __cuda=10.2=0
                          __linux=4.14.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=ppc64le
       base environment : /tmp/nemanich/miniconda3  (writable)
      conda av data dir : /tmp/nemanich/miniconda3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-ppc64le
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-ppc64le
                          https://repo.anaconda.com/pkgs/r/noarch
               platform : linux-ppc64le
             user-agent : conda/4.10.1 requests/2.22.0 CPython/3.7.6 Linux/4.14.0-115.18.1.el7a.ppc64le rhel/7.6 glibc/2.17
                UID:GID : 581379:1059966
             netrc file : None
           offline mode : False
```

</details>

**Comment by chenghlee** [comment]
Is there a `conda_build_config.yaml` that's used with this recipe? We are trying to replicate this issue, but without the `conda_config_config.yaml` you're using, we don't have appropriate values for various variables.

**Comment by npanpaliya** [comment]
@chenghlee - Here is the conda_build_config.yaml that the above test works with https://github.com/open-ce/open-ce/blob/main/envs/conda_build_config.yaml.

**Comment by chenghlee** [comment]
Are you calling `render` and `build` from a script, rather than using `conda build` directly?

**Comment by npanpaliya** [comment]
We've calls to `conda_build.api.build`, `conda_build.api.debug` and `conda_build.api.render`.

**Comment by chenghlee** [comment]
Can you try with the CLI tools (`conda render` and/or `conda build`) to see if the issue still appears there?

**Comment by npanpaliya** [comment]
Okay

**Comment by npanpaliya** [comment]
With the latest conda-build 3.21.8, we are seeing another issue with conda_build.api.render method. It gives the following error -
```  File "/mnt/pai/home/npanpa23/153/open-ce-builder/open_ce/conda_utils.py", line 53, in render_yaml
    metas = conda_build.api.render(path,
  File "/mnt/pai/home/npanpa23/anaconda3/lib/python3.8/site-packages/conda_build/api.py", line 42, in render
    metadata_tuples = render_recipe(recipe_path, bypass_env_check=bypass_env_check,
  File "/mnt/pai/home/npanpa23/anaconda3/lib/python3.8/site-packages/conda_build/render.py", line 838, in render_recipe
    m.config.compute_build_id(m.name(), m.version(), reset=reset_build_id)
  File "/mnt/pai/home/npanpa23/anaconda3/lib/python3.8/site-packages/conda_build/config.py", line 611, in compute_build_id
    shutil.move(old_dir, work_dir)
  File "/mnt/pai/home/npanpa23/anaconda3/lib/python3.8/shutil.py", line 802, in move
    copy_function(src, real_dst)
  File "/mnt/pai/home/npanpa23/anaconda3/lib/python3.8/shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/mnt/pai/home/npanpa23/anaconda3/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/pai/home/npanpa23/anaconda3/conda-bld/work'
```
This is just a part of the error but pointing to the problem in conda-build. 
This used to work fine with conda-build 3.21.7.

Further investigation shows that https://github.com/conda/conda-build/commit/001bcc48c33761b2f37fb3d61031a77091be10ce#diff-eaaf464431ee59c1575fecf5aa57498e16bb0694fd2cb6ee1638d3ebd682e68f change causes the problem.

And when I tried `conda render` CLI command instead of conda_build.api.render, it worked fine even with 3.21.8 version.

**Comment by chenghlee** [comment]
It's likely you need additional code to get and pass values for the `config`, `variants`, and possibly other arguments to the `render` and/or `build` API functions. I would suggest looking at the code in [cli/main_render.py](https://github.com/conda/conda-build/blob/3.21.8/conda_build/cli/main_render.py#L180-L199) and [cli/main_build.py](https://github.com/conda/conda-build/blob/3.21.8/conda_build/cli/main_build.py#L477-L479) as a start.

Is there a reason you're writing your own script rather than using the existing `conda render` & `conda build` CLI tools?
