### ISSUE TITLE
PREFIX=$PREFIX, not the actual prefix, on OS X in build.sh

### ISSUE THREAD

**Issue by grumpyquant** [conda/conda-build#4264]
## Actual Behavior

I am seeing the value of the environment variable PREFIX is $PREFIX when build.sh is executed from conda-build.

## Expected Behavior

I would expect the value of PREFIX to be equal to the build directory.

## Steps to reproduce

With a package with meta.yaml:

```
package:
  name: test
  version: 1.0.0
```

and build.sh:

```
#!/bin/bash
echo $PREFIX
exit 1
```

then what I see as output of conda-build on this package is:

```
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for test
INFO:conda_build.metadata:Attempting to finalize metadata for test
BUILD START: ['test-1.0.0-0.tar.bz2']
source tree in: /Users/gq/test/env/conda-bld/test_1628582741127/work
export PREFIX=/Users/gq/test/env/conda-bld/test_1628582741127/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh
export SRC_DIR=/Users/gq/test/env/conda-bld/test_1628582741127/work
$PREFIX
```

(followed by a traceback due to my exit at the end of build.sh)

What I am of course expecting to see is the value of PREFIX on the last last, as displayed 3 lines up, not $PREFIX.

If I look in work/build_env_setup.sh, I can see that the export PREFIX line sets PREFIX correctly.  If I debug the package via "conda debug" and run build.sh by hand after the setup, then PREFIX is also set correctly.

I also see other variables rewritten unexpectedly.  E.g., in PATH, I can see $PREFIX scattered throughout.  BUILD_PREFIX=$PREFIX.  etc.

##### `Output of conda info`

```
     active environment : /Users/gq/test/env
    active env location : /Users/gq/test/env
            shell level : 1
       user config file : /Users/gq/.condarc
 populated config files : /Users/gq/.condarc
          conda version : 4.10.3
    conda-build version : 3.21.4
         python version : 3.9.5.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/gq/miniconda3-4.10.3  (writable)
      conda av data dir : /Users/gq/miniconda3-4.10.3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/anaconda/osx-64
                          https://conda.anaconda.org/anaconda/noarch
          package cache : /Users/gq/miniconda3-4.10.3/pkgs
                          /Users/gq/.conda/pkgs
       envs directories : /Users/gq/miniconda3-4.10.3/envs
                          /Users/gq/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.9.5 Darwin/20.5.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by cgr71ii** [comment]
The same is happening to me. This is a bug, isn't it? Have you figure out how to solve it, @grumpyquant ?

**Comment by cgr71ii** [comment]
After deep dive into the code I have find out that this is not a bug, but a feature...

The line
https://github.com/conda/conda-build/blob/77463386355f3a726437311d3fa1f39a59afc2e9/conda_build/utils.py#L242
is the one to blame for the confusion. This line substitutes all the `build.sh` output where the value of $PREFIX is found for the name of the envvar itself, and it does the same for SRC_DIR:
https://github.com/conda/conda-build/blob/77463386355f3a726437311d3fa1f39a59afc2e9/conda_build/build.py#L2196

Becuase of the substitution, when we `echo` the value of $PREFIX, $PATH or whatever envvar which contains the value of $PREFIX or $SRC_DIR, we will see only the name of the variable, but the value IS THERE, just hidden. In fact, if you execute
```bash
ls $PREFIX
```
you will find out that it works.

This is a detail which may lead to a very confusing situation... as confusing as the PIP_* envvars which prevent to download content from PyPi which are not documented...

I think this issue can be closed now that this information is available here to anyone which reaches this issue with the same problem.

**Comment by pschloss** [comment]
Thanks for digging through the code! Is there any way to turn this off? I need to see whether `$PREFIX` is getting correctly used in the package that I'm trying to build a recipe for. Just for peace of mind I'd like to see the expanded out value of the variable.

**Comment by cgr71ii** [comment]
Well, I'm not pretty sure, but I think that could enable debug mode, what shouldn't replace these variables:

https://github.com/conda/conda-build/blob/77463386355f3a726437311d3fa1f39a59afc2e9/conda_build/build.py#L2193-L2194

Also, I think you could modify the snakemake code of your local installation and remove

https://github.com/conda/conda-build/blob/77463386355f3a726437311d3fa1f39a59afc2e9/conda_build/build.py#L2200-L2201

Of course, if you modify the code it might be side effects which I don't know (it is possible that in other parts of the code it is expected to be found these variables in the strings). So, if you want to avoid this replacement, I'd go for the debug mode, that of course it might not be the perfect solution for releases since the debug mode perhaps affect the build somehow you don't want for a release.

I don't have a final solution for these, sorry :( I just wanted to be sure that it wasn't a bug. Another "dirty" solution you can try is to modify your log file and replace the `$PREFIX` and `$SRC_DIR` for the paths you expects (of course, this might be hiding deeper bugs if you think that your source and prefix directories are pointing somewhere which are actually not).

I think this is a cosmetic feature, but since we're doing builds, I think that a better solution for a future release of conda build would be:

1. Print these variables at the beginning of the build process (e.g. `echo "\$PREFIX=/path/to/prefix"`)
2. Do not replace the content of `$PREFIX` for the string `$PREFIX`, since this might be hiding some bugs or just making dizzy the developers like ourselves :')
