### ISSUE TITLE
QUESTION: meta.yaml build:entry_points and setup.py entry_points

### ISSUE THREAD

**Issue by johnflavin** [conda/conda-build#4291]
I have a question about an interaction between conda build and the underlying package build tool when both define an entry point. The purpose of defining the entry point is to create a minimal script that will pass CLI args into a python function. But which tool creates the script? `conda-build` or `pip`/`setuptools`/whatever packaging tool you're using? And in particular, how does the correct shebang in the final installed script get generated?

For a concrete example, I'm looking at metaflow. [Its `meta.yaml`](https://github.com/conda-forge/metaflow-feedstock/blob/master/recipe/meta.yaml) defines an `entry_point`, and [its `setup.py`](https://github.com/Netflix/metaflow/blob/master/setup.py) also defines the same entry point.

1. When `conda build` is run, the source is downloaded and the build script `{{ PYTHON }} -m pip install . -vv` is run.
2. I think that would create the entrypoint script.
3.  But then when conda build's post packaging step kicks in, what happens? Does it make a new entrypoint script based on the definition in `meta.yaml`? Does it leave the old one in place and modify its shebang line? Something else?

**Comment by LourensVeen** [comment]
For anyone else finding this, I have a similar setup and it appears that `conda build` overwrites the pip-created entrypoint script with its own. This is required, because pip will create an entrypoint script with a shebang line that hardcodes the location of the Python interpreter in the build environment. This environment is deleted once the package is built, leaving a broken script.

Conda creates one that has the usual `#!/usr/bin/env python` line, which will find the Python interpreter in the currently active Conda environment, which is exactly what you want if you've installed the package.

Debugging tip: Make sure your entry point is under `build/entry_points`, not under `requirements/entry_points` or `requirements/build/entry_points`. Tripped me up :smile:.
