### ISSUE TITLE
KeyError: 'extras_require' while running conda skeleton

### ISSUE THREAD

**Issue by KevinKuchinski** [conda/conda-build#4354]
Hi, 

I was trying to prepare a recipe for my pypi package by running conda skeleton and got the following traceback (pasted below). To test if the problem was with my package, I tried running the conda skeleton pypi click command from the tutorial, and got exactly the same error.

```
Traceback (most recent call last):
  File "/Users/kevinkuchinski/miniconda3/bin/conda-skeleton", line 11, in <module>
    sys.exit(main())
  File "/Users/kevinkuchinski/miniconda3/lib/python3.9/site-packages/conda_build/cli/main_skeleton.py", line 64, in main
    return execute(sys.argv[1:])
  File "/Users/kevinkuchinski/miniconda3/lib/python3.9/site-packages/conda_build/cli/main_skeleton.py", line 59, in execute
    api.skeletonize(args.packages, args.repo, output_dir=args.output_dir, recursive=args.recursive,
  File "/Users/kevinkuchinski/miniconda3/lib/python3.9/site-packages/conda_build/api.py", line 276, in skeletonize
    skeleton_return = module.skeletonize(packages, output_dir=output_dir, version=version,
  File "/Users/kevinkuchinski/miniconda3/lib/python3.9/site-packages/conda_build/skeletons/pypi.py", line 315, in skeletonize
    get_package_metadata(package, d, data, output_dir, python_version,
  File "/Users/kevinkuchinski/miniconda3/lib/python3.9/site-packages/conda_build/skeletons/pypi.py", line 752, in get_package_metadata
    requires = get_requirements(package, pkginfo, all_extras=all_extras)
  File "/Users/kevinkuchinski/miniconda3/lib/python3.9/site-packages/conda_build/skeletons/pypi.py", line 1115, in get_requirements
    for extra in pkginfo['extras_require']:
KeyError: 'extras_require'
```

**Comment by ACharbonneau** [comment]
I've also just gotten this error trying to build a skeleton on `deriva` from pypi. Exact same traceback:

> Traceback (most recent call last):
  File "/Users/amandacharbonneau/mambaforge/envs/cfde_venv/bin/conda-skeleton", line 11, in <module>
    sys.exit(main())
  File "/Users/amandacharbonneau/mambaforge/envs/cfde_venv/lib/python3.10/site-packages/conda_build/cli/main_skeleton.py", line 64, in main
    return execute(sys.argv[1:])
  File "/Users/amandacharbonneau/mambaforge/envs/cfde_venv/lib/python3.10/site-packages/conda_build/cli/main_skeleton.py", line 59, in execute
    api.skeletonize(args.packages, args.repo, output_dir=args.output_dir, recursive=args.recursive,
  File "/Users/amandacharbonneau/mambaforge/envs/cfde_venv/lib/python3.10/site-packages/conda_build/api.py", line 276, in skeletonize
    skeleton_return = module.skeletonize(packages, output_dir=output_dir, version=version,
  File "/Users/amandacharbonneau/mambaforge/envs/cfde_venv/lib/python3.10/site-packages/conda_build/skeletons/pypi.py", line 315, in skeletonize
    get_package_metadata(package, d, data, output_dir, python_version,
  File "/Users/amandacharbonneau/mambaforge/envs/cfde_venv/lib/python3.10/site-packages/conda_build/skeletons/pypi.py", line 752, in get_package_metadata
    requires = get_requirements(package, pkginfo, all_extras=all_extras)
  File "/Users/amandacharbonneau/mambaforge/envs/cfde_venv/lib/python3.10/site-packages/conda_build/skeletons/pypi.py", line 1115, in get_requirements
    for extra in pkginfo['extras_require']:
KeyError: 'extras_require'

**Comment by KevinKuchinski** [comment]
A curious development: I installed conda-build on an old laptop and conda skeleton ran fine, both on the tutorial's click package and on my own package. Thinking this could be a simple update issue, I updated my conda and conda-build on the computer where I had had the errors, then tried running conda skeleton again. Unfortunately, the same error continued.

**Comment by ACharbonneau** [comment]
I'm on a brand new laptop, and so have a brand new install of conda, so it could be some kind of version thing, I don't know if I have conda-build on my old laptop to try an earlier version

**Comment by OmarOakheart** [comment]
I have the exact same issue, even when trying to run the example

conda skeleton pypi click

I'm using Windows 10's Ubuntu app, in case that's relevant at all.

**Comment by edeno** [comment]
Hi all, I've also been experiencing this issue as well.

I tried downgrading conda and conda-build to 4.10.3 and 3.21.4, respectively but this did not work. However, when I downgraded python from 3.9 to 3.6.13, this avoided the error.

I suspect it has to do with the setuptools that gets installed in 3.9 (which is greater than 60.0), whereas in 3.6, setuptools 58.3 gets installed. I don't know enough about how conda-build works to verify this though.

**Comment by ruochiz** [comment]
I have the exact same issue. The python version used for the conda-skeleton is 3.7

**Comment by toonarmycaptain** [comment]
I'm getting this issue with Python 3.8.

**Comment by HuguesGiraud** [comment]
I had the exact same issue. I managed to fix it with the following steps:
1. Check your packages with `conda list`. Look at the channel associated to pkginfo package
2. If the associated channel is conda-forge, `conda remove pkginfo`
3. You could change the channel priority order in .condarc file in order to put "defaults" channel in first position and then `conda install pkginfo`  (or without changing channel priority order but you could think about it: `conda install -c defaults pkginfo`).
4. Re-install conda-build: `conda install conda-build`
5. Now, you should be able to run `conda skeleton pypi <package>`

**Comment by OmarOakheart** [comment]
@HuguesGiraud 's solution did not work for me. I get the same error as before with

`pkginfo                   1.8.2              pyhd3eb1b0_0`

**Comment by gergelycsegzi** [comment]
I managed to fix the issue by running:
`conda skeleton pypi [package] --python-version 3.6`

**Comment by ruochiz** [comment]
I tried @gergelycsegzi solution. Does seem to work on the example "click" package. But still doesn't work on my own package. I finally just quitted using conda skeleton and just wrote my own recipe and do conda build. Seems to work on my own machine. Not sure if that affects the compatibility of the packages on other platforms.

**Comment by zanussbaum** [comment]
I'm having a similar issue when building `google-cloud-aiplatform`. I tried the solution proposed by @HuguesGiraud but also failed to resolve the issue.

**Comment by decrevi** [comment]
> I managed to fix the issue by running: `conda skeleton pypi [package] --python-version 3.6`

This worked for me.

**Comment by lynch730** [comment]
So the immediate problem is that 'site-packages/conda_build/skeletons/pypi.py' is trying to locate dictionary keys 'extras_require' and 'tests_require' from pkginfo.

My *very* limited understanding is that this pkginfo dictionary has keys derived from setup.py entries (e.g. 'packagename' and 'version' are also keys used). This suggests skeletons/pypi.py is assuming the pypi setup.py file has entries for 'extras_require' and 'tests_require' and will throw errors if they are not found. 

This is by no means the ideal solution, but I was able to get skeleton to produce a meta.yaml file by hacking out the parts of skeleton/pypi.py referencing these two keys. 

Specifically, I did the following:
1. commenting out the "for extra in pkginfo['extras_require']" loop around line 1115 and replacing with extras_require=[]. 
2. comment out 'metadata['tests_require'] = get_tests_require(pkginfo)' on 771
3. comment out f d['tests_require']: on 384/385
4. deleting tests_require line in 260
(I may have gotten some of these line numbers off slightly). I've attached my mangled file below.

Note: I think this is okay, because the whole point is to produce a template meta.yaml file that you will have to modify anyway. If this results in missing setup.py "requires" you will just have to go back and add them yourself.
[pypi.zip](https://github.com/conda/conda-build/files/8240189/pypi.zip)

**Comment by rockhowse** [comment]
Fun times on an `M1` as `conda skeleton pypi [package] --python-version 3.6` yields even more fun errors:

```
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform osx-arm64: {'python=3.6'}
```

**Comment by clearoak** [comment]
Same issue encountered.

**Comment by calvinwy** [comment]
same here, still experiencing the issue even after updating conda-build.  Could someone look into this?  I am trying to setup my package to conda-forge.

**Comment by jvollme** [comment]
@calvinwy : for what is is worth: I now found that using [greyskull](https://github.com/marcelotrevisani/grayskull/) instead of conda skeleton seems to work. It looks like greyskul is supposed to replace conda skeleton anyway, so others with this problem may just use greyskull as an alternative...

**Comment by calvinwy** [comment]
> @calvinwy : for what it is worth: I now found that using [greyskull](https://github.com/marcelotrevisani/grayskull/) instead of conda skeleton seems to work. It looks like greyskul is supposed to replace conda skeleton anyway, so others with this problem may just use greyskull as an alternative...

@jvollme : Thanks!  I actually figured out the same thing yesterday from the official conda-forge step-by-step guide [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#step-by-step-instructions), sorry about forgetting to update my post.

**Comment by WarrenWeckesser** [comment]
This issue has been closed, but the error still occurs with `conda` installed with the latest Anaconda and then updated.  Has the fix just not yet made it into a release of `conda`?  Or is `conda skeleton` truly deprecated and unsupported?  If so, you could save folks some time by updating the instructions at https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs-skeleton.html.

**Comment by StefanoTrv** [comment]
Still having this same problem. Setting the python version to 3.6 worked.
