### ISSUE TITLE
SPIKE: Overriding zip keys in local cbc.yaml not working as expected

### ISSUE THREAD

**Issue by kenodegard** [conda/conda-build#4519]
Research & document what conda-build does today.

**Comment by travishathaway** [comment]
While working on this, another related bug surfaced that was reported to the [conda/conda-build](https://github.com/conda/conda-build) repository:

https://github.com/conda/conda-build/issues/4537

I also discovered that there are several other issues related to the behavior of `conda_build_config.yaml` files:

- https://github.com/conda/conda-build/issues/3974
- https://github.com/conda/conda-build/issues/4377

I've been able to track down the buggy behavior to this function:

https://github.com/conda/conda-build/blob/953b89542b51c0c988c5630a4f2b018f7efed857/conda_build/variants.py#L602-L619

As a future developer works on this, the thing to keep in mind is the output of this function. Right, now it is just a list with a single item (i.e. with `python=3.10` and `numpy=1.21`). Ideally, we'll want to have a full list of all passed in variant configs.

Yet another thing to keep in mind is whether this is actually the expected behavior. From as far as I can tell, it is the expected behavior to be able to build multiple versions of recipe using different version combinations of `python` and `numpy`. This is what is explained in the documentation and the actual code leaves one believe this too.
