### ISSUE TITLE
Review release policy of conda-build

### ISSUE THREAD

**Issue by jezdez** [conda/conda-build#4754]
To streamline the conda-build releases, we need to review if the current release policy is matching the expectations by users and if we're still making effective use of versioning.

Especially with [CEP 8](https://github.com/conda-incubator/ceps/blob/main/cep-8.md) having been rolled out in conda, it'd be useful to understand if using it for conda-build would also work.

The outcome of this issue would be a plan of action to improve the release management of conda-build.

**Comment by kenodegard** [comment]
We have successfully released conda-build in tandem with conda for several releases now (since March 2023). Tandem releases have been useful in identifying deprecation issues and even plugin issues. Our release process is also streamlined enough that we can successfully deliver two releases in tandem without major obstacles or delays.

The next step is to switch from conda-build's SemVer to CalVer, see #4975
