### ISSUE TITLE
Validate contents of meta.yaml before solving package dependencies

### ISSUE THREAD

**Issue by da1910** [conda/conda-build#4773]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

If the user has made a mistake in the meta.yaml file, for example by specifying `build -> script: build.sh` which will cause conda-build to fail, it should do so _before_ taking several minutes/hours to solve an environment.

### Why is this needed?

This reduces time spent waiting for builds to fail during the development process

### What should happen?

If things that are obviously wrong and easy to validate are incorrect, fail immediately, rather than waiting for conda to take its sweet time solving the environment.

**Comment by beeankha** [comment]
Hi @da1910 , thanks for taking the time to file this issue. I've added the https://github.com/conda/conda-build/labels/backlog and https://github.com/conda/conda-build/labels/pending%3A%3Adiscussion labels so that it's in the conda core devs' queue of issues to discuss and refine.

In the meantime, if you feel like there is additional information that might help us, please feel free to continue to update this ticket!

**Comment by da1910** [comment]
I also hit a similar issue today where I had accidentally used `output` as a key, rather than `outputs`. I'm a little surprised that that's not checked either, I had expected the `meta.yaml` file to be validated against a schema before anything else happened?

**Comment by da1910** [comment]
I missed this notification - yes it still occurs as described. I encountered this on linux by following the steps described above, either by setting `build -> script: build.sh` or by setting the `output` key instead of `outputs`.

The latter is literally trivial to fix, as you define the spec for the meta.yaml file, just validate it up front?
