### ISSUE TITLE
--update flag for conda skeleton

### ISSUE THREAD

**Issue by asmeurer** [conda/conda-build#492]
It would be useful to have an --update flag for conda skeleton, which updates a given recipe. This would be different from just using --version-compare and rm because it would detect any changes to the recipe and try to maintain them. Would be useful for both pypi and cran (and probably cpan, although I don't really use that one).

**Comment by ChrisBarker-NOAA** [comment]
Great idea -- My first thought is to take the reverse approach -- rather than detecting changes to the recipe, simple specify what bits will get updated: i.e keep the recipe entiorely as is, but update 

package:
  version: "1.6.2"

source:
  fn: awesome-slugify-1.6.2.tar.gz
  url: https://pypi.python.org/packages/source/a/awesome-slugify/awesome-slugify-1.6.2.tar.gz
  md5: 6ff079a109646055f9af6c0df285a450

And maybe:

requirements:

(in that case you'd probably want to add, but not remove requirments.)

and update versions of requirements, if they are specified.

In practice, other stuff may get changed (like what customization was needed), but in that case, the use is simply going to have to start again by hand.

-Chris

**Comment by asmeurer** [comment]
I think your suggestion and mine would each be about equally difficult to implement, and mine is more robust against changes to package metadata across versions.

**Comment by ChrisBarker-NOAA** [comment]
I'm not sure they are equally difficult, but implementer's choice! I"d be nice to see, either way.

**Comment by timsnyder** [comment]
#1704 added a `--force` option to the cpan skeleton that has some overlap with this idea.
