### ISSUE TITLE
Cannot install Anaconda on Mac M2 

### ISSUE THREAD

**Issue by denemelerce14** [conda/conda-build#4920]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

[install logs.docx](https://github.com/conda/conda-build/files/11861116/install.logs.docx)

Hi,

I downloaded 64 bit- graphical installer for Mac. I tried to install it but had an error that basically says it has failed.  Attached I added log files for the installation. I couldn't install it. This is the first time I try to download Anaconda.

### Conda Info

```shell
zsh: command not found: conda
```

### Conda Config

```shell
zsh: command not found: conda
```

### Conda list

```shell
zsh: command not found: conda
```

**Comment by beeankha** [comment]
Hi @denemelerce14 , thank you for filing this issue! Due to the contents of this ticket being off-topic for this repo, we ask that you please file a new one in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues) (it is the place for `conda` installer/package manager issues) if you're still encountering this problem.
