### ISSUE TITLE
Deprecate `conda_build.bdist_conda`

### ISSUE THREAD

**Issue by kenodegard** [conda/conda-build#4985]
### What happened?

The functionality in `conda_build.bdist_conda` is specific to Python packages (built with `distutils`/`setuptools`) and not needed to build a conda package, e.g. see the sample usage:

https://github.com/conda/conda-build/blob/b2cb091e60bf9a879e4330db6ddad19675ee7f87/recipe/test_bdist_conda_setup.py#L3-L11

Based on a preliminary [GitHub search](https://github.com/search?q=NOT+is%3Afork+NOT+org%3Aconda+%2Fdistclass%3D.*CondaDistribution%2F&type=code) the feature is also minimally used out in the wild (if at all?).

[Docs](https://docs.conda.io/projects/conda-build/en/stable/user-guide/recipes/build-without-recipe.html)

Thoughts on deprecating it? @chenghlee @dbast @jaimergp @ryanskeith @beeankha

**Comment by jezdez** [comment]
A few thoughts:

- the bdist_conda functionality is an attempt at lowering the barrier of adoption of conda, so it becomes easier for maintainers to build conda packages from standard Python packages
- setuptools is still maintained and not deprecated
- PEPs [517](https://peps.python.org/pep-0517/) (build backends) and [518](https://peps.python.org/pep-0518/) (`pyproject.toml`) provide new official APIs to define and build Python packages
- the wheel package [is supporting a bdist_wheel subcommand](https://github.com/pypa/wheel/blob/e76040b0d970a0fe6211c31888fc929078ba02d9/pyproject.toml#L37-L38)
- But: we should work towards a few things to evolve this and stay up-to-date:
  - deprecate the built-in `bdist_conda` command
  - _and_ release a `setuptools-conda` package in the conda incubator that contains the needed code (or just tell people to use old conda-builds?)
  - add the ability to conda-build to optionally read conda recipe metadata from `pyproject.toml`
  - work on a PEP 517 compatible build backend that enables Python users in the future to easily build conda files in addition to wheel files

**Comment by jezdez** [comment]
I'd be interested to hearing what @dholth has to say about this

**Comment by dholth** [comment]
I would be shocked if anyone uses this.

**Comment by beeankha** [comment]
@mbargull do you have any thoughts or concerns about deprecating `conda_build.bdist_conda`?

**Comment by mbargull** [comment]
Thanks for asking, Bianca!
I think `bdist_conda` is of limited use and has probably a very, very small user base.

In general, I think it would be beneficial if `conda-build` would be a generic package build tool at its core with specialized functionality like `bdist_conda` being added on the outside rather than the inside of it.
Meaning, I'm supportive of removing it from `conda-build` and think this functionality should be provided by an additional tool/package.

If we leave it in `conda-build`, it will likely only add tech-debt/maintenance-burden and at the same time not get the support it actually needs since it's used and tested by too few users.

There is, of course, the questions on where such tool/package would be developed at and who would sponsor such work...
We may want to comb through issues open regarding `bdist_conda` to figure out who is interested in it (and @jezdez would probably know who from the Python ecosystem to poke to find potential interested parties).

**Comment by joserc87** [comment]
I'm arriving to this issue, investigating after my CI pipeline has started failing with
```
error: invalid command 'bdist_conda'
```
realizing that it's been deprecated, and reading:

> I would be shocked if anyone uses this.

Well, for what is worth, at least one person was using it :smiling_face_with_tear:. Also my project didn't appear in that search (and probably others as well) because I don't have `distclass=conda_build.bdist_conda.CondaDistribution` in the setup.py.

Of course I understand the need of deprecating features that are barely used, but be careful with your assumptions: there could be more people using this than what you expect.

**Comment by joserc87** [comment]
BTW if there are others like me, for me the solution is just to fix the version to `24.3.0` (`conda install --yes conda-build=24.3.0`) which seems to be the previous version to this deprecation. If there is a better solution I'd love to hear it.
