### ISSUE TITLE
Remove old full-index-in-memory loading and `conda.plan`-related solver handling

### ISSUE THREAD

**Issue by mbargull** [conda/conda-build#5154]
In gh-5074 we removed the `conda.models.dist.Dist` usage from `conda-build`.

This included copying over the `install_actions`/`execute_actions`/`display_actions` functions from `conda.plan`
(which only continued to exist to serve these deprecated functions to `conda-build`).

These functions, which are as of gh-5074 now part of `conda_build.environ`, are reduced to have only the code  actually used in `conda-build`.
But their behavior still remained the same, i.e., they still use the same old solver invocations that loads the whole repodata index into memory, not benefiting from the reduced resource usage via https://github.com/conda/conda/pull/12050 .

To be able to work with the reduced/only partially loaded index, we need to deprecate/remove some functionality that relies on iterating over the full index.
gh-5152 marks parts related to that as deprecated.

The major part to look out for when we'll replace the current `install_actions` code is that the index has to stay in a consistent state throughout a recipe build.

---

Closes https://github.com/conda/conda-build/issues/4961

**Comment by mbargull** [comment]
I'll look into this during the next couple of weeks.
In preparation of it, to get a sense on what memory/CPU consumption is currently happening, I stumbled upon the fact that peak memory usage (with `libmamba` solver) is actually dominated by a bug in `conda>=4.12`: https://github.com/conda/conda/issues/13541 .
So, when doing comparisons of resources used before/after changes in `conda-build`, one should factor out the surplus coming from that bug (patching `conda` when testing -- or, if lucky, maybe we get a patch release in the meantime).

**Comment by jaimergp** [comment]
xref https://github.com/conda/conda-build/issues/4961

**Comment by jaimergp** [comment]
@zklaus, summarizing our conversation earlier today:

- The easy way out: detect `context.solver == libmamba` and only populate the local part of the `_index` (no need to build PackageRecords for the whole thing)
- Same but a bit more elegant, add a class attribute to `Solver` to announce whether a full index is needed in memory or not.
- Better even: change the solver API to have a standardized, companion Index API that handles the interfacing better (with and without conda-build) instead of relying on `Solver._index` manipulation. This API should mention which channels need to be reloaded after an artifact is built and how.

**Comment by dholth** [comment]
It would also be a great idea to make PackageRecord instantiate more quickly.

**Comment by jaimergp** [comment]
> It would also be a great idea to make PackageRecord instantiate more quickly.

I'll create an issue for this if it doesn't exist already.

Besides that, I think this is ready to close after https://github.com/conda/conda-build/pull/5488 and https://github.com/conda/conda/pull/13880, right?

**Comment by jaimergp** [comment]
Done: https://github.com/conda/conda/issues/14426
