### ISSUE TITLE
conda build fails

### ISSUE THREAD

**Issue by ericmjl** [conda/conda-build#531]
I have a project that I've been working on, to make protein genotype networks. https://github.com/ericmjl/genotype-network

There's a corresponding PyPI upload: https://pypi.python.org/pypi/genotype_network/0.1.4

I tried doing `conda skeleton pypi genotype_network`. All is good there.

Then I tried doing `conda build`, where I also have `binstar` upload automatically done. I get the following error:

	===== testing package: genotype_network-0.1.4-py34_0 =====
	import: 'genotype_network'
	===== genotype_network-0.1.4-py34_0 OK =====
	+ sample --help
	Traceback (most recent call last):
	  File "/Users/ericmjl/anaconda/envs/_test/bin/sample", line 4, in <module>
	    from sample import main
	ImportError: No module named 'sample'
	TESTS FAILED: genotype_network-0.1.4-py34_0

I cannot seem to figure out why conda build is trying to do `from sample import main`. Is there an explanation for this?

**Comment by jakirkham** [comment]
Because you have added `sample` to the `entry_points`. ( https://github.com/ericmjl/genotype-network/blob/master/setup.py#L107-L111 )

When building, `conda` tries to run all executable that you specify with the help option. The reason being, we think it is good practice for all command line tools to provides help. Using `argparse`, included in Python, the work is basically done for you.

If you have more questions, feel free to ask.

Based on the context here, I don't believe this is a bug in `conda`.

**Comment by ericmjl** [comment]
Oh my oh my. This was totally a newbie error on my part. Thanks for the help!!!

**Comment by jakirkham** [comment]
No worries. Fortunately, the Python community is a friendly place. :)
