### ISSUE TITLE
Support building noarch packages on Windows

### ISSUE THREAD

**Issue by dhirschfeld** [conda/conda-build#605]
> [noarch_python] Error: Python noarch packages can currently not be created on Windows systems.

https://github.com/conda/conda-build/blob/6ce4d8e057e83287c6ec771dc186f84885d8365f/conda_build/noarch_python.py#L88-L90

**Comment by chipmunc56** [comment]
Is there any chance this could get fixed?

**Comment by marscher** [comment]
The check for win platforms has been removed on master. But I noticed that the output path for noarch packages points to $platform instead of "noarch". This breaks some assumptions right?

**Comment by marscher** [comment]
example output: https://ci.appveyor.com/project/jchodera/conda-recipes/build/1.0.116/job/20kii0o1h7n8dixa#L668

**Comment by marscher** [comment]
Sorry this is not windows specific: https://travis-ci.org/omnia-md/conda-recipes/jobs/211417628#L4886

On linux the the built package also goes to linux-64 instead of noarch (conda-build-2.1.6). However this only happens during CI and not locally. The script which invokes conda-build is here:
https://github.com/omnia-md/conda-recipes/blob/master/conda-build-all#L415

**Comment by dhirschfeld** [comment]
Closing since I'm pretty sure this works on Windows now
