### ISSUE TITLE
osx_is_app should use pythonw for test imports

### ISSUE THREAD

**Issue by asmeurer** [conda/conda-build#7]
I don't fully understand `osx_is_app` (and btw it's not documented anywhere), but if means what I think it does, the test imports should be run with `pythonw`, not `python` on OS X.

**Comment by ozak** [comment]
Indeed. Was this ever solved? any way to work around it?

**Comment by rayosborn** [comment]
For some reason, this has just become a problem for my builds (https://github.com/nexpy/nexpy/blob/master/conda-recipe/meta.yaml), although they seemed to work fine a few months ago.

<details>
 <summary>Current conda install</summary>
  <pre><code>
              platform : osx-64
          conda version : 4.3.4
       conda is private : False
      conda-env version : 4.3.4
    conda-build version : 2.1.1
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : /Users/rosborn/anaconda  (writable)
    default environment : /Users/rosborn/anaconda
       envs directories : /Users/rosborn/anaconda/envs
          package cache : /Users/rosborn/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/conda-canary/osx-64
                          https://conda.anaconda.org/conda-canary/noarch
                          https://conda.anaconda.org/nexpy/osx-64
                          https://conda.anaconda.org/nexpy/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/rosborn/.condarc
           offline mode : False
             user-agent : conda/4.3.4 requests/2.12.4 CPython/2.7.12 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 938267710:660979062
  </code></pre>
</details>
<br>
The error is in running the test at the end, even though `pythonw` is installed in the test `bin` directory.
<br>
<details>
 <summary>Error message</summary>
  <pre><code>
+ /bin/bash -x -e /Users/rosborn/anaconda/conda-bld/conda-recipe_1484588846841/test_tmp/run_test.sh
+ nexpy --help
/bin/bash: /Users/rosborn/anaconda/conda-bld/conda-recipe_1484588846841/_t_env/bin/python.app: No such file or directory
  </code></pre>
</details>
<br>
It looks to me as if the problem is that the code in post.py (https://github.com/conda/conda-build/blob/master/conda_build/post.py) tries to run python.app, but doesn't have pythonw as a fallback option if it's not there.

**Comment by msarahan** [comment]
based on experimentation with @rayosborn's nexpy recipe, it looks to me like conda-build should be ensuring that python.app is a runtime dependency when osx_is_app is True (making sure it is there, or adding it automatically).  Without this, pythonw and python.app did not exist for me in my test folder, so switching to pythonw alone isn't likely to work.  I'll add this in for the 2.1.2 release.

**Comment by rayosborn** [comment]
I don't know how complicated this would be, but in the long term, it would be nice if the osx_is_app flag was ignored when using the recipe on another system architecture. At the moment, I have to write build scripts that remove the flag before creating the build for Linux and Windows, and then restore it again before rebuilding for OS X.

**Comment by msarahan** [comment]
That's disappointing.  I'll make sure that it is ignored on non-OS X platforms.

**Comment by rayosborn** [comment]
I should say that was the case a while ago. I haven't tested it more recently.
