### ISSUE TITLE
windows: code problems in how vcvarsall.bat is found?

### ISSUE THREAD

**Issue by janschulz** [conda/conda-build#729]
https://github.com/conda/conda-build/blob/master/conda_build/windows.py#L73

The code currently reads:

```
vcvarsall = os.path.join(program_files,
                             r'Microsoft Visual Studio {version}'.format(version=version),
                             'VC', 'vcvarsall.bat')

    # Try the Microsoft Visual C++ Compiler for Python 2.7
    localappdata = os.environ.get("localappdata")
    not_vcvars = not isfile(vcvarsall) # <- evaluated here
    if not_vcvars and localappdata and not config.PY3K:
        vcvarsall = os.path.join(localappdata, "Programs", "Common",
            "Microsoft", "Visual C++ for Python", "9.0", "vcvarsall.bat")
   # ... but not reevaluated after the new path is set...
    if not_vcvars and program_files and not config.PY3K:
        vcvarsall = os.path.join(program_files, 'Common Files',
            'Microsoft', 'Visual C++ for Python', "9.0", "vcvarsall.bat")
    if not_vcvars:
        print("Warning: Couldn't find Visual Studio: %r" % vcvarsall)
        return ''

    msvc_env_lines.append('call "%s" %s' % (vcvarsall, 'x86' if cc.bits == 32 else 'amd64'))
    return '\n'.join(msvc_env_lines)
```

If I read that right, then this code does *NOT* try to find the `vcvarsall.bat` file in three locations but only the first and the second and third locations are just not tried but result in a problematic error message as `vcvarsall` is updated to the third location?

IMO the right way would be:

```
    not_vcvars = not isfile(vcvarsall)
    if not_vcvars and localappdata and not config.PY3K:
        vcvarsall = os.path.join(localappdata, "Programs", "Common",
            "Microsoft", "Visual C++ for Python", "9.0", "vcvarsall.bat")
+        not_vcvars = not isfile(vcvarsall) 
    if not_vcvars and program_files and not config.PY3K:
        vcvarsall = os.path.join(program_files, 'Common Files',
            'Microsoft', 'Visual C++ for Python', "9.0", "vcvarsall.bat")
+        not_vcvars = not isfile(vcvarsall) 
    if not_vcvars:
        print("Warning: Couldn't find Visual Studio: %r" % vcvarsall)
        return ''
```

This is more or less what it read before https://github.com/conda/conda-build/commit/44251cbfcef5c82fdf2168e5a23505c670d12330

**Comment by JanSchulz** [comment]
CC: @groutr who did the mentioned commit

**Comment by JanSchulz** [comment]
Ok, this is really a bummer, as it burns matplotlibs builds (copied from https://github.com/matplotlib/matplotlib/pull/5629#issuecomment-174525328):

py27, 64bit:
https://ci.appveyor.com/project/JanSchulz/matplotlib/build/1.0.104/job/k30t1bkb9s1ljya6#L7294

```
[test-environment] C:\conda\conda-bld\work>call "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\vcvarsall.bat" amd64 
The specified configuration type is missing.  The tools for the
configuration might not be installed.
```
-> This is a problem in conda-build which does not prefers the installed python vs compiler over the normal VC install (which seems to be missing the 64bit compilers... :-()

PY34, 64bit: https://ci.appveyor.com/project/JanSchulz/matplotlib/build/1.0.104/job/qk7e8eska42nsv39#L7402
```
[test-environment] C:\conda\conda-bld\work>call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat" amd64 
The specified configuration type is missing.  The tools for the
configuration might not be installed.
```

-> This is point 4 on this entry: http://blog.ionelmc.ro/2014/12/21/compiling-python-extensions-on-windows/#for-python-3-4

Instead of `call <...>vcvarsall.bat amd64` it should run `CALL "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64` directly

**Comment by JanSchulz** [comment]
So IMO:

* if it requests version 9, try the python vs path first 
* if requests version 10, also add a `\nif errorlevel 1 (<call setenv.cmd directly>)`

**Comment by mwcraig** [comment]
+:100:  to the suggestions to call  `SetEnv.cmd` directly. That seems, [according to the distutils docs](https://docs.python.org/2/distutils/apiref.html#module-distutils.msvccompiler), to be what one should do when `UseSDK` is set 1 as it is in conda build. 

This change would remove the need for special setup scripts on appveyor that set the SDK, allowing one to build for several versions of 64-bit python on one build worker.

**Comment by JanSchulz** [comment]
Note these bugs probably all have the same problem:
* plain duplicate: https://github.com/conda/conda-build/issues/623, should have searched better :-/
* https://github.com/conda/conda-build/issues/218 (old, asks for Support for Microsoft Visual C++ Compiler for Python 2.7, which is actually included, but due to this bug not used)
* https://github.com/conda/conda-build/issues/560 -> asks to get the path from teh registry

**Comment by janschulz** [comment]
as https://github.com/conda/conda-build/pull/861 is merged, this and most of the other linked issues could probably be closed.

**Comment by msarahan** [comment]
Thanks @janschulz, will do.
