### ISSUE TITLE
Pre-emptively create build/run/test envs to avoid late failure

### ISSUE THREAD

**Issue by ijstokes** [conda/conda-build#762]
I'm trying to build Bokeh right now with this command:

```
conda build -q -c javascript conda.recipe
```

After many minutes of building it then turns out `conda-build` can't create the test env since it can't find `pytest-cov`.  I forgot to add the `-c bokeh` option.  So now I have to start over again.  Is it possible to pre-create the test env?  Or at least do a `--dry-run` and maybe add in some smarts to know which packages the `build` stage will have created when it is completed?

**Comment by timsnyder** [comment]
I like the idea of this.  I have run into this type of situation with larger packages and I end up being tempted to do unsafe things (e.g. upload my package to my channel out of the broken directory).

I recently noticed the `--test` option to `conda-build`.  I think the next time I run into this, I'll try rerunning the exact same `conda-build` commandline with the additional channel given and with `--test`.  

I haven't tried this yet but I'm going to guess that the "already built" package won't be found and that I'll still have to fish it out of the "broken" directory and put it back into the "successful" platform channel directory and then rerun.

At a minimum, when the test phase fails due to inability to create the environment, it would be nice if `conda-build` could print out a 'hint' message about how to rerun from 'test'.  Something like:
```python  
  """
    # Unable to create environment for testing, perhaps you forgot to specify a channel?
    # To rerun from the test phase with an additional channel, use:
    #
    # $ {} -c <channel> --test
    #
    # To search anaconda.org for the missing package use
    # $ anaconda search -t conda {}
    """.format(some_generation_of_properly_quoted_sys.argv, missing_pkg)
```
