### ISSUE TITLE
CPU_COUNT can be too high on Travis CI

### ISSUE THREAD

**Issue by izaid** [conda/conda-build#784]
In DyND, we've found that the CPU_COUNT environment variable can sometimes be reported very high (.e.g CPU_COUNT=32) on Travis CI.

**Comment by msarahan** [comment]
That's probably the native CPU's on the machine.  Docker just passes it through.  Is this causing failed builds?  I feel like this is a special case for Travis, not really a special case for conda-build to handle.  We should definitely provide a way for people to override any auto-detected CPU_COUNT, though, so that we don't break Travis.

**Comment by izaid** [comment]
Yeah, it's causing failed builds for us. Would love a fix for it. Ping @insertinterestingnamehere

**Comment by msarahan** [comment]
For now, I'd recommend changing your recipe to not use -j${CPU_COUNT} -  at least for your checked-in copy of the recipe.

**Comment by izaid** [comment]
Already done, thanks. :)

**Comment by groutr** [comment]
I wonder if this might be of any help
http://serverfault.com/questions/691659/count-number-of-allowed-cpus-in-a-docker-container

`nproc` is a newish command present in coreutils.  It seems possible to parse `/proc/self/status`.  The `Cpus_allowed_list` gives the correct info inside a docker container.  Multiprocessing simply parses `/proc/cpuinfo`.
(http://manpages.ubuntu.com/manpages/natty/man7/cpuset.7.html)

**Comment by jakirkham** [comment]
I opened this issue ( https://github.com/conda/conda-build/issues/1117 ) to try and allow for `CPU_COUNT` to be overridden externally via an environment variable.
