### ISSUE TITLE
DOC: add windows development env build instructions in docs

### ISSUE THREAD

**Issue by msarahan** [conda/conda-build#793]
Moved from https://github.com/conda/conda/issues/2123

pydata/pandas#12428

Nice to have a conda/anaconda reference on how to do this in a straightforward way.

cc @msarahan @kalefranz

**Comment by ivoflipse** [comment]
What specifically do you want to have documented here? We have some experience building conda packages for Windows projects that require compilation, such as VTK and GDCM. So we could at least help verify that everything is reproducible and up to date

**Comment by msarahan** [comment]
I'd like to see things like:

1. Which compiler to use for any given python platform (to comply with standards).  Brief explanation of why mixing runtimes on Windows is a bad idea.
2. What are good alternatives for VS 2008 and VS 2010, since they are harder to obtain?  The MSVC++ compiler for Python works, but we need to document setup.  Does conda-build need any extra configuration?  Same story for the Win 7.1 SDK and the VS2010 compiler therein.
3. If you need to break compatibility and build your own Python ecosystem, what needs to be rebuilt, and how should you go about it?

**Comment by JanSchulz** [comment]
Re installing VS on windows: https://blog.ionelmc.ro/2014/12/21/compiling-python-extensions-on-windows/ this works and as far as I remember, conda build does not need any additional preparation (compared to a normal python build), but the setup is still not so straighforward...

For matplotlib on appveyor, you can see the [workarounds I needed to get this working](https://github.com/matplotlib/matplotlib/blob/master/appveyor.yml#L63-L68).
. It would be nice if all these workarounds wouldn't be nessesary (e.g. it would be nice to [call the right things if vcvarsall.bat on vs2010 isn't around for 64bit](https://github.com/conda/conda-build/issues/729#issuecomment-174532573)).

This probably also needs a fix for https://github.com/conda/conda-build/issues/729, so that the right vcvarsall.bat is found...
