### ISSUE TITLE
Build recipe parsing and extension

### ISSUE THREAD

**Issue by kalefranz** [conda/conda-build#857]
CC @pelson @ukoethe @msarahan @stuarteberg @ilanschnell @groutr 

I'd like to discuss here some fundamental issues related to three open and in places conflicting PRs. (There could be more to add to this list.)
- #728
- #747 
- #848 

These issues really go to the heart of how conda-build parses and handles meta.yaml recipes.  From the start, meta.yaml files have never been valid yaml files on their own.  Instead, a preprocessing step is used with the "selector" concept that then yields valid yaml.  Along the way, we added jinja2 templating that performs a similar function to selectors, but oftentimes in a more flexible way.

As this has all grown organically over time, some of the implementation is perhaps a bit haphazard.  We for example call `parse` three times, and `parse_again` twice, each time completely re-reading the meta.yaml file.  Furthermore, the timing for exactly when these calls happen is right now important and intermingled with the actual build step.

Here's my proposal to untangle and fix some of this:
1. A jinja2 pass is the first preprocessing step.  This step enforces jinja2 StrictUndefined mode for variables.  That means context and variables defined _as part_ of the meta.yaml recipe cannot be used _within_ the recipe.  For example, `{{ os.environ['GIT_DESCRIBE_TAG'] }}` won't work here, since that's dynamic information that can only be determined farther into the process.
2. A selector pass is the second preprocessing step. After this step, we have valid yaml.
3. We introduce a new capability where conda can dynamically interpolate values in meta.yaml with environment variables from the current build context right before those values are actually used in the code.  The behavior is similar to bash string interpolation with `${VAR_NAME}` or [PEP-498](https://www.python.org/dev/peps/pep-0498/) python string interpolation with `{VAR_NAME}`.  Here, let's assume the final implementation uses the ruby syntax of `#{VAR_NAME}` (so we don't clash with valid bash in the meta.yaml `test` section).  While the `{{ os.environ['GIT_DESCRIBE_TAG'] }}` example won't work, you can instead use `#{GIT_DESCRIBE_TAG}`.  Further, if jinja2 is installed, we can use filters e.g. `#{GIT_DESCRIBE_TAG | default('v0.0.0')}`.  We can go a step further by exposing the `meta` or `m` object to the interpolation context.
4. It's pretty clear to me that we need to support the concept of a build matrix in a more flexible way than just at the command line.  For example, we create a build matrix right now with `conda build . --python all --numpy all`.  The only way this can be extended is to make code changes by adding argparse flags.  While conda-build will always be run in a "local" context, and thus `platform` will never be a valid vector, we still have a clear need for flexible matrix support in conda-build.  Here, even though conda-build itself will never be a CI system, I think it's best to use the [Travis-CI matrix](https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix) for inspiration.

**Comment by stuarteberg** [comment]
You have laudable motivations here, and I certainly agree about the unfortunate overlapping functionality between selectors and jinja templates.  But I don't see why a totally new approach is necessary.

First, a minor clarification:

>We for example call parse three times, and parse_again twice, each time completely re-reading the meta.yaml file.

AFAICT, we only parse `meta.yaml` twice, not three times.  (The [first call] to `parse` just initializes `meta` with empty contents; it doesn't actually read `meta.yaml`.)

[first call]: https://github.com/conda/conda-build/blob/master/conda_build/metadata.py#L325-L328

> Furthermore, the timing for exactly when these calls happen is right now important and intermingled with the actual build step.

Well, yes, it's important, but it's not *too* complicated, IMHO.  The steps are as follows: (1) Parse `meta.yaml` (2) Download the `source`, (3) Re-parse `meta.yaml`.

Regarding your proposal:

The nice thing about jinja is that it is a mature, carefully designed templating system that is well-documented and has good coverage on stackoverflow.  As far as I can tell, part 3 of your proposal effectively requires a second-pass parse anyway, except that now we'd parsing the contents of each field individually.  It's not clear to me what would be gained with that approach vs. parsing the whole file a second time as we do now.  But even if we go down that road, why should we invent our own template syntax (e.g. `${VAR_NAME}` or `#{GIT_DESCRIBE_TAG}`) -- and implement the logic for supporting it, and document it -- when jinja syntax already exists and works perfectly well for that purpose?  Wouldn't that just burden recipe authors with yet another syntax to learn?

>we still have a clear need for flexible matrix support in conda-build

I'm puzzled by this conclusion, at least as it pertains to conda-build itself. (I don't do many "matrix" builds myself, so maybe I'm missing something.)  conda-build already supports everything you need to perform a single build, and it is, of course, trivial to wrap calls to it within a bash script (or whatever) that performs each build combination from a configuration matrix.  Instead of implementing matrix build logic within conda-build itself, isn't that sort of thing best left to external build matrix tools such as conda-build-all)?  (Of course, the PRs you listed above all aim to make building a single package with conda-build more *convenient*, which would greatly benefit such external tools, and I'm totally on-board with that.)

**Comment by stuarteberg** [comment]
One addendum to my last point:

>Instead of implementing matrix build logic within conda-build itself, isn't that sort of thing best left to external build matrix tools such as conda-build-all)?

In fact, I would be in favor of removing support for `--python all --numpy all` from conda-build.

**Comment by kalefranz** [comment]
> But I don't see why a totally new approach is necessary.

I actually don't think anything I proposed--besides the matrix part--is a totally new approach.  I think it's more a refinement and clarification.  Parts 1 and 2 mostly happen as stated right now.  As you pointed out, Part 3 does as well, just in another round of parsing.

>  But even if we go down that road, why should we invent our own template syntax

What I proposed in Part 3 I would implement two ways, one for if jinja2 is available and one for if it's not installed.  If jinja2 is available, I'd create a `jinja2.Environment` where `variable_start_string` is `#{` and `variable_end_string` is `}`.  That way you get all the jinja2 filter goodness.  If it's not available, we could write some simple substitution functions--or not support this case at all.  So it's not really anything new even, both in implementation and syntax for the recipe author.  Implementation is still the mature, carefully designed templating system.  The syntax, besides the different variable start/end strings, is also still the same.  Furthermore, that minor difference is a really good thing.  It's an explicit way for recipe authors to know that recipe-dependent variables will be available within the context.

> except that now we'd parsing the contents of each field individually

This is actually a key distinction, and it's important.  Having valid yaml (or json for that matter) after Part 2 means that we can enforce a schema on meta.yaml and have a cleaner, validated data model.  Yes, at this point, we're templating individual fields instead of the file as a whole--and it's a more powerful and flexible approach.  I'd reference the difference between how ansible uses yaml and salt uses yaml as an example.

> > we still have a clear need for flexible matrix support in conda-build

> I'm puzzled by this conclusion

The clear need comes from the very fact that it's already sorta-implemented (with e.g. `--python all`).  The hard-coded command-line flags are what's problematic.  This is a topic in this thread because several of these PRs deal with "`x.x`".  If we didn't have the `--numpy all` matrix builds at all, we wouldn't need `x.x`.

**Comment by stuarteberg** [comment]
Alas, I find myself playing the role of the naysayer, which I do not relish. :-)  My apologies.

But here I go again...

>Furthermore, that minor difference is a really good thing. It's an explicit way for recipe authors to know that recipe-dependent variables will be available within the context.

At the moment, all recipe-dependent variables are already available in all jinja templates, and if the recipe author screws up, she sees a reasonably clear error message like this:

```
Error: Failed to render jinja template in /home/bergs/mypackage/conda-recipe/meta.yaml:
'SOME_VAR' is undefined
```

... so I don't think there will be too much confusion over what is and isn't supported in jinja templates.

>at this point, we're templating individual fields instead of the file as a whole

The ability to use multi-line jinja templates (with jinja's rich control structures) can be very useful at times.  For instance, here are two recipes that exploit jinja control structures to specify a descriptive `version` (or build `string`) based on the package's current git revision:

- [pandas meta.yaml](https://github.com/pydata/pandas/blob/master/conda.recipe/meta.yaml)
- [vigra meta.yaml](https://github.com/ilastik/ilastik-build-conda/blob/vigra-1.11/vigra/meta.yaml)

It's not immediately clear to me how we could achieve the same effect using field-by-field templates.

>If we didn't have the `--numpy all` matrix builds at all, we wouldn't need `x.x`.

Indeed, once #848 is merged, I'd advocate for deprecating `--numpy all` and the `x.x` syntax.  I'm not saying it was wrong to implement them in the first place.  On the contrary, those features undoubtedly filled a critical need during conda/Anaconda's early history. But now we see the need for a more general approach: one that separates the concerns of building a package with a single configuration vs. building several variants it.

Supporting custom configurations via a `--build-config` file or a `--bootstrap` environment as proposed in #848 would be more general, and more explicit, IMHO.  Matrix build tools will surely evolve sophisticated logic to select the configurations they need to build, and they will exploit this new functionality to great effect.  But we should keep that logic out of conda-build itself. Ideally, conda-build should "do one thing and do it well", namely, build a single package, using whatever dependencies the user explicitly specified.

**Comment by ukoethe** [comment]
Thanks for sharing your thoughts with me, @kalefranz. However, I agree with everything @stuarteberg said, and would like to add the following thoughts:

1. conda is just now gaining a lot of momentum (look at the rapid growth of `conda-forge`, for example). This is the best that can happen to the project (and Continuum), and it would be a *big* mistake to break the momentum by changing the underlying tools in incompatible ways.

2. The fact that outsiders like me and many others are able to understand conda-build and make reasonable suggestions proves that its fundamental design is valid. Of course, there are some rough edges, the documentation should be improved, and desirable functionality is missing, but all of these can be fixed by the normal process of refactoring and enhancement. IMHO, all available manpower should be devoted to implementing these gradual improvements as quickly as possible.

3. Jinja is a pleasure to work with -- it is simple, elegant, and powerful. There is no point in inventing and supporting new syntax (such as `#{GIT_DESCRIBE_TAG}`) when the jinja designers already did all the hard work for us. Supporting jinja templating in conda-build was a good decision! Now, we have to figure out how to make best use of its capabilities.

4. Metadata must be parsed in at least two phases, because many properties (run requirements, features, build strings) can only be finalized after the `_build` environment has been set up. Better documentation of these phases is absolutely essential, and it would be desirable to differentiate them in the structure of the `meta.yaml` file. However, the current design is far from being broken to the point that a rewrite from scratch is necessary and incompatible changes can be justified.

5. What's wrong with parsing `meta.yaml` repeatedly? The time this takes is totally negligible against everything else.

6. I agree with @stuarteberg that concepts like a build matrix should be left to tools working on top of conda-build, like bash scripts or `conda-forge`.

> A jinja2 pass is the first preprocessing step. This step enforces jinja2 `StrictUndefined` mode for variables.

Using `StrictUndefined` during the first pass means that jinja becomes effectively unusable, because one cannot use variables that are undefined before the `_build` environment has been created. I don't see what is wrong with `UndefinedNeverFail`.

**Comment by ukoethe** [comment]
> What I proposed in Part 3 I would implement two ways, one for if jinja2 is available and one for if it's not installed.

Since jinja2 is an official dependency of conda-build (check the `index.json` file!), it is always available. Why waste time for workarounds that are never needed? The only recipe that shouldn't require jinja2 to be installed is the jinja2 recipe itself, but this special case can be solved more directly, I suppose.

> I'd create a `jinja2.Environment` where `variable_start_string` is `#{` and `variable_end_string` is `}`.

The default delimiters `{{` and `}}` are used throughout the jinja documentation. Changing them would only confuse people and break compatibility. This is not justifiable.

**Comment by ukoethe** [comment]
Reading your proposal, I don't quite understand how it helps to address the problems I'd like to see solved in conda-build:

* How to choose between different compilers? (I've talked a lot about Visual Studio versions, but eventually I'd also like to be able to use mingw or clang for Windows for everything.)
* How to refine build dependencies at build time?
* How to select and record build-time options like BLAS and AVX?
* How to refine run dependencies after the build, according to the contents of the `_build` environment?
* How to ensure that conda environments remain consistent over many calls to `conda install`, e.g. via features?
* How to do all this such that it remains portable across platforms, supports long-term evolution, and is easy to understand and well documented?
