### ISSUE TITLE
GIT_DESCRIBE_TAG not defined when SSH is used instead of HTTPS

### ISSUE THREAD

**Issue by sklam** [conda/conda-build#880]
conda-build 1.20.0 

With [this meta.yaml](https://github.com/sklam/conda_build_tag_bug/blob/master/meta.yaml#L6), GIT_DESCRIBE_TAG is not defined.  When the ``git_url`` is changed to use https (https://github.com/sklam/conda_build_tag_bug/blob/master/meta.yaml#L7), GIT_DESCRIBE_TAG is defined as expected.

Last known working version: conda-build 1.17.0

**Comment by ajdes** [comment]
I am also experiencing this issue on os x, conda-build 1.19.2

**Comment by msarahan** [comment]
Please update to a newer version of conda-build.  1.21.2 was released today, and this functionality is explicitly tested

**Comment by ajdes** [comment]
Updated to 1.21.2.  I do see GIT_DESCRIBE_TAG working now when used in the 'package' section, but it fails in the 'source' section as 'git_rev'.  I'm guessing this is because we havent yet checked out the source repo and thus dont have the rev info, however, I thought I read that meta.yml is parsed twice if necessary to address this.  Is this behaving as expected?  If so, can you provide a work around for checking out the latest rev as the source without using GIT_DESCRIBE_TAG?

**Comment by msarahan** [comment]
I think you just want to specify 'HEAD', or 'master' or whatever your current branch is.  By default, it will get the latest revision.  If you provide no git_rev or git_tag at all, you'll get the default branch at its latest revision.

It makes no sense to use GIT_DESCRIBE_TAG in git_rev, because that field is there to specify which version to get, not to describe which version was obtained.  In other words, it's an input, not an output.

by the way, git_rev and git_tag are equivalent in the source field.

**Comment by ajdes** [comment]
The point is I DONT want the latest, I want to use a specific tagged commit as the source.  In this case I am saying I want the latest tagged commit in the repo, and ignore any commits that were made after that tag (i.e. a release in github)

so rather than saying:
source:
  git_url: foo@github.com:Bar/Baz.git
  git_rev: SOME_TAG_I_HAVE_TO_KEEP_UP_TO_DATE

I would like to say:
source:
  git_url: foo@github.com:Bar/Baz.git
  git_rev: {{ THE LATEST TAGGED COMMIT }}

**Comment by msarahan** [comment]
OK, good, thanks for the example.  I don't think there is a way right now.
It would be pretty easy to add, though.  I think we just need to add a bit
more to the existing git_info function, as well as a little bit of special
handling to do some special logic in the source checkout.

I'll take this as a good feature request.  I have a lot on my plate right
now, but I'll work on this sometime soon.
