### ISSUE TITLE
Conda build on Win very slow when removing old build env

### ISSUE THREAD

**Issue by msarahan** [conda/conda-build#980]
Not sure if this is new or old issue.

CC @joelhullcio

**Comment by joelhullcio** [comment]
Removing files from the pkgs/.trash directory fixed the slow build issue for me.

**Comment by msarahan** [comment]
Thanks for that feedback.  I'll try to integrate some better logic so that the slowdown does not happen in the first place.

**Comment by ikalev** [comment]
I had the same issue with one specific installation. Manually deleting ``.trash`` improved the situation only temporarily.

After some debugging, I found out that conda is spending most of the time trying to delete the ``.trash`` directory, which on this specific machine contained 300 temp directories. There were various pyd, dll and exe files in this directory tree, which ``conda build`` would try to delete with ``shutil`` on each run, but couldn't, because there were always locked even after a fresh reboot and no other python processes running. 

This was an old Anaconda installation (1.8) with lots of virtual environments. I speculated that there might be something wrong with the way earlier conda versions used to link packages and decided to reinstall. This solved my problem!
